### ISSUE TITLE
Render bidirectional cycleways

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#10]
The cycleway in https://tiles.phyks.me/#17/48.84245/2.36672 is bidirectional. However, nothing in the render indicates this.

![screenshot_2019-01-26 cyclosm](https://user-images.githubusercontent.com/3856586/51792908-50836c00-21b8-11e9-8283-77a764530f17.png)

Related to #8

**Comment by Phyks** [comment]
Actually, these are really roads, except they are only for bikes. They should probably be rendered with some width, just like a regular road.

**Comment by Florimondable** [comment]
Two way road don't any arrow, should be the same for double way cycleway.
Though oneway cycleway should have arrow.
