### ISSUE TITLE
Filter contour lines

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#106]
Some contour lines are weird, making lot of loop for no real reason I guess :
https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/45.8513/3.1300

We may need to filter the elevation data.

**Comment by Phyks** [comment]
Indeed, this is not really nice. The only (naive) option I have so far is to filter the contour lines on the length of the elevation line (these have quite a small perimeter and could probably be ignored if setting a treshold value of a few tens of meters). This could however come with false positives on volcanos, https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/45.7965/2.9750.

Charles seemed to have some ideas and previous knowledge about filtering and smoothing this out, though.

**Comment by Florimondable** [comment]
Yes we should ask him how to do that
