### ISSUE TITLE
Some cycleways are hidden by roads

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#115]
See the cycleway on Avenue de Flandres for instance here https://cyclosm.github.io/cyclosm-cartocss-style/example.html#14/48.8787/2.3718 (cycleway visible here https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.88589/2.37152).

Maybe we should add an extra layer for cycleway rendering to ensure it is always on top.

**Comment by Phyks** [comment]
See as well https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/48.8634/2.2784 (#141).

**Comment by Florimondable** [comment]
I think this can be solved by the help of attachements something like:
```
#roads_high {
  ...
  cycleway_right/line-width=x
  cycleway_left/line-width=x
  line-width=x
  ...
}
```
A primary highway is rendered after a service road so there cycle tracks will be also rendered after the inline of the service road. And when at low zooms the two primary way (which make the full road) overlap one of the cycle track would be still visible. So we solve the issue of a service road next to a big road hiding the track and the issue of two primary road hiding the cycle track of the other.
May be that breaks intersections ?
Yeah it does :(
I keep this for the record.

**Comment by Florimondable** [comment]
same issue with path https://www.cyclosm.org/#map=18/48.89719/2.40455/cyclosm
