### ISSUE TITLE
Pedestrian areas don't have colors

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#118]
See Place du Marché Sainte-Catherine: https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.85529/2.36233

Color for pedestrian ways is coming from https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L409 which is only applied to OSM ways (not polygons).

Pedestrian squares are drawn in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L96-L113 which does not have colorization.

**Comment by Florimondable** [comment]
Actualy the Place du Marché Sainte Catherine is drawn in light green light, the same way as the center of Place de l'étoile https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.87376/2.29498
