### ISSUE TITLE
Support cycleway:*:oneway

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#119]
We are currently supporting `oneway` tag on `highway=cycleway`. The same scheme should be extended to support `cycleway:left|right:oneway=no`.

**Comment by Florimondable** [comment]
Please don't add on default cycleway (so oneway) an arrow.

**Comment by Phyks** [comment]
> Please don't add on default cycleway (so oneway) an arrow.

We are already doing it on `highway=cycleway` + `oneway=yes`: https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.82399/2.32594.

**Comment by Florimondable** [comment]
And I'm the guy who done that.

**Comment by Phyks** [comment]
I'm not sure what to do with this. Most of the `cycleway:left|right:oneway` are living on `lane` or `share_busway`. We render these with dots and I'm not sure it would be really nice to have an arrow on top of the dots.

@Florimondable what do you think about using a pattern on the casing to have a very slight arrow for the direction? Something like (very subtle)

![2019-10-07-174511](https://user-images.githubusercontent.com/3856586/66327114-92a9a380-e92a-11e9-90ca-e59fc3a4ca5f.png)

**Comment by Florimondable** [comment]
That's smart !

But never felt the need to have that feature, so is it necessary for me ? No.
Though I know some weird cases where it would be good to know the the direction of the lane https://www.google.fr/maps/@48.8435905,2.4577221,3a,75y,301.05h,73.66t/data=!3m6!1e1!3m4!1sHSKW06zdC09DvA2lZ6ROrA!2e0!7i16384!8i8192
(The openstreetmap on that case is not good in my opinion.)

**Comment by Phyks** [comment]
Here is my current render at Z18 and beyond.

https://www.cyclosm.org/#map=19/48.84960/2.36974

![2019-10-14-132450](https://user-images.githubusercontent.com/3856586/66748145-bcad1980-ee86-11e9-9c88-d67dc84054d0.png)


https://www.cyclosm.org/#19/48.79724/2.15395

![2019-10-14-132952](https://user-images.githubusercontent.com/3856586/66748158-c3d42780-ee86-11e9-8609-a7c085e63bcc.png)


https://www.cyclosm.org/#map=18/48.82589/2.32857/cyclosm

![2019-10-14-134309](https://user-images.githubusercontent.com/3856586/66748865-92f4f200-ee88-11e9-978f-ecc212a597a0.png)


Left to do:

- [ ] `cycleway:*:oneway=no`
- [ ] `cycleway:left|right=track`

**Comment by Phyks** [comment]
Bidirectional cycleways tagged on main highway are now larger as well.

https://www.cyclosm.org/#map=18/48.80099/2.43625/cyclosm

![2019-10-14-150801](https://user-images.githubusercontent.com/3856586/66753692-a1490b00-ee94-11e9-99f5-cd7defc98bf5.png)

**Comment by Phyks** [comment]
Done for tracks. https://www.cyclosm.org/#map=18/48.82637/2.32988

![2019-10-14-161321](https://user-images.githubusercontent.com/3856586/66757945-8f1f9a80-ee9d-11e9-8845-199d14b8e142.png)

**Comment by Florimondable** [comment]
not sure to understand why this one is not rendered oriented https://www.openstreetmap.org/way/64609509 but this one is https://www.openstreetmap.org/way/25469382 
https://www.cyclosm.org/#map=20/48.87709/2.36359/cyclosm

**Comment by Phyks** [comment]
I'm only rendering `cycleway:left|right:oneway` and `cycleway:left|right=opposite_*` so far. You are right, I should include direction for these as well.

We just have to be careful about `cycleway:both=*` for which we should not render any arrows (depends on left or right hand side driving). I'd still render an arrow for `cycleway=*` to make the distinction clear and improve tagging.

**Comment by Florimondable** [comment]
> You are right, I should include direction for these as well.
I didn't say that, it was just to understand.
Nevertheless may be we should render them, didn't think it through yet.

**Comment by Phyks** [comment]
I think everything is fine for this in the code currently. Reopen if I missed anything.
