### ISSUE TITLE
Render surface tags?

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#12]
Should `surface` tags be rendered (`paved`/`unpaved`)? What could be a good way to render this?

**Comment by Phyks** [comment]
https://tilemill-project.github.io/tilemill/docs/guides/styling-lines/ line-pattern-file

could be an idea to display a "paved road" effect.

**Comment by Florimondable** [comment]
My thought of how to do it in this discussion :
«Florimond Berthoux [13 h 58]
avec https://tilemill-project.github.io/tilemill/docs/guides/styling-lines/ line-pattern-file il y a moyen d'afficher un effet route pavée
ou alors c'est avec du dash line
l'intérêt du dash line c'est qu'on pourrait rendre avec la même symbolique des différents traitillé les différent revêtements d'une autoroute à un footway
sinon il faudra faire deux symboliques l'une pour les routes avec un effet pavé/caillou, un autre pour les path

Florimond Berthoux [14 h 34]
en réutilisant la symbolique des grade de tracktype sur osm.org https://wiki.openstreetmap.org/wiki/Key:tracktype
en tant que ligne axiale

Lucas Verney [14 h 36]
dash line, ça risque de faire trop de traitillés avec les pistes cyclables, non ?

Florimond Berthoux [14 h 36]
possible
un line pattern file, ça risque aussi de faire très chargé et brouilli
je pense qu'il ne faudrait l'afficher qu'à partir de Z14 (modifié) 
et si c'est du grade1 (revêtement lisse) ne rien affiché

Florimond Berthoux [14 h 45]
il y aurait trois niveaux, suivant le type de vélo utilisable facilement : vélo de route (pneu<=28) - surface lisse, vélo gravel/ville/rando (pneu <=35) surface pavée/caillou fin, vtt (pneu >35) gros caillou/terre à détuire des tags gratype/smoothnees/surface

Lucas Verney [14 h 47]
:+1:

Florimond Berthoux [14 h 47]
ce qui fait que deux dash possible : "- - - - -" ou "- . - . - . -" facilement reconnaissable»

**Comment by sylvainavelo** [comment]
The way road surface is rendered is not clear because it uses two different visual variables at the same time : the width of the outline (seems wider than other roads) and the dashed fill.  Only one should be used.

This is not a usual way of rendering road surface on a map. Usually the dash is applied on the outline, not on the fill.

See the "route empierrée" on IGN France maps : https://www.geoportail.gouv.fr/depot/layers/GEOGRAPHICALGRIDSYSTEMS.MAPS/legendes/GEOGRAPHICALGRIDSYSTEMS.MAPS_25k-legend.png
Or tracks on Ordnance Survey maps: https://www.ordnancesurvey.co.uk/docs/legends/25k-raster-legend.pdf

My suggestion would be to use the same kind of rendering; no change in width or color between a good and a bad surface, just dash the outline of the bad surface.

**Comment by Florimondable** [comment]
About the width, the width is not modified for good or bad surface, the width only between the importance of the road (highway=primary, secondary, tertiary ....) Cycle path with two ways are larger than ones with one way though.

About the outline dash, cycle lane are rendered by outline dash line and cycle track by a blue outline. This is a primary feature, and I don't this can be changed easily. So outline dashed possibilyt is already taken by them and cannot be used for surfaces.

**Comment by sylvainavelo** [comment]
Ok I misundestood why there is such a wide (fat) outline on some very little streets (most of them are cobbled but not all of them indeed). There is no explanation about this style here : https://cyclosm.github.io/cyclosm-cartocss-style/legend.html
Why https://www.openstreetmap.org/way/44650431 has this fat outline and not https://www.openstreetmap.org/way/369974933

Also the endings are strange on these roads : round outline but square fill.

And ok there are a few places with a bad surface AND a bicycle lane like Avenue Foch or Avenue Marceau and this would be impossible to show both info on the outline.

**Comment by Florimondable** [comment]
Wide outline are for Pedestrian streets, living street have also little wider outline than usual streets.
Outline == pavement more or less.

Legend should be updated

**Comment by Phyks** [comment]
Legend updated in https://github.com/cyclosm/cyclosm-cartocss-style/commit/80c2c158cbf08fdd82916b1b91e4acc3a7fda4aa :)

**Comment by sylvainavelo** [comment]
Thanks for the legend update.

It is indeed difficult to show speed limit + pedestrian + surface on one street.

It was unclear for me that speed limit and pedestrian are two different things. In France at least the speed limit in a pedestrian area should always be walking speed.

There are mistakes in the data where I looked:
For instance this street is pedestrian with maxspeed 20: https://www.openstreetmap.org/way/44715465
and next block its always pedestrian with maxspeed 30: https://www.openstreetmap.org/way/44714774

**Comment by Phyks** [comment]
> It was unclear for me that speed limit and pedestrian are two different things. In France at least the speed limit in a pedestrian area should always be walking speed.

In France, this should probably be walking speed indeed. However, we don't aim only for France and want to avoid as much as possible French regulation bias in this render. From https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpedestrian, there is no mention of `maxspeed` on a `highway=pedestrian`. From https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Maxspeed#Default_speed_limits, the situation is very complex:

* 30 km/h in Turkey
* 20km/h in Czech Republic
* walking speed in France or Germany
* and looking at the situation for living street, I guess we can find dozens of other default (by law) maxspeed values in the world :)

> There are mistakes in the data where I looked

I don't have enough knowledge for this specific case (maybe @Florimondable has?). Pedestrians in France should probably not have such maxspeed values, but there can be a lot of weirdness in the signs position and their implications. Looking at the BMO for this specific case, it is probably a mistake, but what is really there should be checked in the reality before editing I think.

**Comment by Florimondable** [comment]
That's the beauty of CyclOSM we can find bugs in the data :D
Phyks is right, the default speed limit change between countries. Nevertheless the default color for pedestrian is the same as walk speed (<10kmh).
And it also good to remember that pedestrian is not allowed for bikes in every countries either..
