### ISSUE TITLE
Support cycleway=shoulder

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#122]
«cycleway=shoulder
    Used for shoulders that are navigable and legal to cycle on, where a high-speed road is legal but not useful infrastructure. Often a sign designates the road as such, e.g. "Motor Vehicles and Bicycles Only."»
https://wiki.openstreetmap.org/wiki/Key:cycleway

examples :
https://www.openstreetmap.org/way/449039306
https://www.openstreetmap.org/way/609992932
https://www.google.com/maps/@44.8825179,4.9418634,3a,75y,191.74h,55.94t/data=!3m6!1e1!3m4!1suG5k8cWH-Z1SKt99ouKHrw!2e0!7i13312!8i6656

**Comment by Florimondable** [comment]
render key shoulder also ?
https://wiki.openstreetmap.org/wiki/Key:shoulder

**Comment by Phyks** [comment]
:+1: for this. `cycleway=shoulder` is especially useful in countries such as the US I think. Having `shoulder` render would be really nice as a complement to cycle routes using regular roads without infrastructure. This is the case for instance for https://cyclosm.github.io/cyclosm-cartocss-style/example.html#13/45.6566/3.0525 and having shoulders on such roads can be a major help

**Comment by Phyks** [comment]
`cycleway=shoulder` are now rendered (but they are not very widely used :/ https://taginfo.openstreetmap.org/tags/cycleway=shoulder#overview).

I'm not sure about the `shoulder` key though. A quick check with Overpass shows me that almost no  `shoulder` key in France is actually on motorways and very little are on really interesting roads such as secondary roads. Given the very low usage of the `shoulder` key and the complexity of the tagging, I'd be more in favor of not rendering it so far.

Regarding the complexity, there is:
* `shoulder=yes|no|left|right|both`
* `shoulder:left=yes|no` / `shoulder:right=yes|no` / `shoulder:both=yes|no`

and then you have to deal with `shoulder:access:bicycle` tags as well as `cycleway=shoulder` + the surface and so on.

It would basically mean duplicating the whole `cycleway` processing logic for shoulders, complexifying a lot the CartoCSS code for basically very little practical use case.

If the situation is different in other countries or areas where shoulder are indeed widely tagged and useful information for bikes, I'd gladly reopen this one though! :)
