### ISSUE TITLE
Rails should not have surface effects

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#127]
It does not make sense to have rails with bad surface indication. See https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.01991/0.16542.

![Capture d’écran 2019-05-10 à 10 56 09](https://user-images.githubusercontent.com/3856586/57515181-50941b80-7312-11e9-9b31-dcfcf59ab4df.png)

**Comment by Florimondable** [comment]
Well no, I disagree it makes sence see Nice Tramway https://www.openstreetmap.org/way/303360461#map=15/43.7140/7.2623
