### ISSUE TITLE
Render highway=crossing?

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#128]
We should probably render `highway=crossing` + `bicycle=yes|designated`. For instance https://www.openstreetmap.org/node/3104431432.

Should we render every `highway=crossing` at high zoom?

**Comment by Florimondable** [comment]
Why not, but I never used it on opencyclemap.
It's an alias to a proper cycleway, or a less good protected junction.

**Comment by Phyks** [comment]
Done, render is

![Capture d’écran 2019-06-03 à 16 51 48](https://user-images.githubusercontent.com/3856586/58811377-fa1fb180-861f-11e9-90c3-3f082402da87.png)
