### ISSUE TITLE
Overlapping cycle routes

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#13]
Overlapping cycle routes should be rendered in a better way. Right now:

* As cycle routes have < 1.0 opacity, they appear stronger when to same type cycle route overlap (stronger blue below).
* Colors are mixed when two different cycle routes types overlap (weird green + blue below).

![screenshot_2019-01-26 cyclosm](https://user-images.githubusercontent.com/3856586/51792942-f7680800-21b8-11e9-976c-e2bda7631e53.png)

Location : https://tiles.phyks.me/#17/48.84896/2.36354

**Comment by Phyks** [comment]
There could be ideas to borrow from Waymarked Trails: https://cycling.waymarkedtrails.org/#?map=15!49.0834!2.194.

**Comment by Phyks** [comment]
A solution could be given by the cheatsheet about blending in https://carto.com/developers/styling/cartocss/#line-comp-op-keyword.

See https://carto.com/developers/styling/cartocss/#line-comp-op-keyword as well.

**Comment by Phyks** [comment]
Closing in favor of #55.

**Comment by Florimondable** [comment]
Not really solved when a lot of cycle route go through the same way, for instance Quai Valmy in Paris :
https://tiles.phyks.me/#18/48.88126/2.36875

The road/cycleway under is no more visible :/

**Comment by Phyks** [comment]
Sure, but the discussion was going on in both this one and #55 (https://github.com/cyclosm/cyclosm-cartocss-style/issues/55#issuecomment-466999367), so I'm just keeping #55 open and focusing on both issues.
