### ISSUE TITLE
Railway in tunnel are still visible

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#130]
see for instance https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.87558/2.31917 a very light line is drawn.

https://www.openstreetmap.org/way/639745511

**Comment by Phyks** [comment]
I think this is coming from the fact that the railway is under construction. I cannot see it for other railways but I can see it [here](https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.80999/2.31803) for another railway under construction. I'll check it further.

**Comment by Phyks** [comment]
I simply removed the railways in tunnel layer altogether in https://github.com/cyclosm/cyclosm-cartocss-style/commit/dd3eefa5e759abdfbebeaacb5f8aa3e9cfd9cfc1. This should fix this issue, let me know if you think I missed something.
