### ISSUE TITLE
Render numbered junction for bicycle routes

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#132]
Render these keys on nodes https://wiki.openstreetmap.org/wiki/Key:rcn%20ref

**Comment by Phyks** [comment]
<3 these junctions, we should definitely render their labels!

**Comment by Phyks** [comment]
Done in last commit. Current render is

![Capture d’écran 2019-06-03 à 15 04 03](https://user-images.githubusercontent.com/3856586/58803939-ec166480-8610-11e9-84f0-25423da6a69e.png)

![Capture d’écran 2019-06-03 à 15 03 29](https://user-images.githubusercontent.com/3856586/58803944-ef115500-8610-11e9-8cc2-a5a6ca0fe2cb.png)

Might be worth fine-tuning upon next tiles regeneration.

**Comment by Florimondable** [comment]
Nice. Not sure about the zoom of the first image, but it look too low to have the markers.

**Comment by Phyks** [comment]
> it look too low to have the markers.

I've just use the same zoom threshold as OpenCycleMap does.
