### ISSUE TITLE
Tramway lines not visible enough

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#134]
See https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.81014/2.29872

![Capture d’écran 2019-06-03 à 11 53 58](https://user-images.githubusercontent.com/3856586/58793404-4f46cd80-85f6-11e9-888e-eb436ac8c5e0.png)

**Comment by Florimondable** [comment]
Special case of a tramway with wheels (no issue for the T3 in Paris) I guess.
https://www.openstreetmap.org/way/264501044#map=14/48.8171/2.3070&layers=C

**Comment by Phyks** [comment]
Indeed, this was a conflict between `highway=bus_guideway` and `railway=tram`. Should be fixed.
