### ISSUE TITLE
bicycle=no not rendered properly

### ISSUE THREAD

**Issue by sylvainavelo** [cyclosm/cyclosm-cartocss-style#135]
In the Père Lachaise cemetery, every road is explicitly forbidden for bicycles (bicycle=no) and this is not visible on the map:
https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/48.8611/2.3965
This was already lacking in OCM.

There are useful things in the cemetery (drinking water and toilets) but there is not clue that these are not accessible with a bicycle.

**Comment by Florimondable** [comment]
Yep its a feature that need some work : how to draw road and path not allowed for bicycle.
For the moment we draw path with bicycle=no in red like here https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.82235/2.32013 or there https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.85574/2.26498

In Père Lachaise the path are footway so drawn in green(green means pedestrian) so bicycle is by default no very welcome on those kind of path. No need for red here.

For the service highway they have a tag bicycle=no but rendered in light blue as 20kmh, here we have a real issue: they appears bicycle friendly whereas they are totaly not.
Road (motorway>road>path) with bicycle=no should be rendered in light red I think.

**Comment by Phyks** [comment]
> For the service highway they have a tag bicycle=no but rendered in light blue as 20kmh, here we have a real issue: they appears bicycle friendly whereas they are totaly not.
Road (motorway>road>path) with bicycle=no should be rendered in light red I think.

Agree on this. You are more familiar with this than me, I'll let you update the cartocss code :)

**Comment by Phyks** [comment]
Closing in favor of #138.
