### ISSUE TITLE
Cannot differentiate cycleway intersection and cycleway on a bridge with an other under

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#137]
Everything is in the title
see the two cycleways next to the bridge Pont de Charenton https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.81732/2.42017
osm.org draw the difference though.

**Comment by Phyks** [comment]
Indeed, we need some casing here I think.

**Comment by Phyks** [comment]
Same thing applies for `footway`, typically https://www.cyclosm.org/#map=20/48.83490/2.37743/cyclosm now that we fixed the `footway` render.

**Comment by Phyks** [comment]
Done.

https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.81732/2.42017
![2019-10-15-142814](https://user-images.githubusercontent.com/3856586/66831568-3e20ac80-ef58-11e9-9026-62a2e3d0fdbc.png)

https://www.cyclosm.org/#map=20/48.83490/2.37743/cyclosm

![2019-10-15-143004](https://user-images.githubusercontent.com/3856586/66831581-4aa50500-ef58-11e9-8837-3f90bb3b2048.png)
