### ISSUE TITLE
Render road with limited access to bicycle

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#138]
For instance https://www.openstreetmap.org/way/5213104#map=18/48.84117/2.32132

**Comment by Florimondable** [comment]
An other example in Pere Lachaise, Paris, a cemetery forbidden for cyclist but service roads rendered as blue due to 20kmh maxspeed.
https://www.cyclosm.org/#map=17/48.86104/2.39497/cyclosm

Idea:
- fade the color ?
- render x on the road ?

**Comment by Phyks** [comment]
> use yellow/orange/red ?

Should not use this in my opinion, way to visible for something we want to avoid (same issue with current primary / secondary).

> render x on the road ?

Having an "- x - x -" pattern on the outline of the way might be nice, no?

**Comment by Florimondable** [comment]
I think render the road in grey can do the job, it already does well for motorway.
Grey doesn't make the road visible and make it think as dead road.
And it's easy to do.

**Comment by Phyks** [comment]
Is grey itself enough? :+1: for having it grey, but there should maybe be something else to make it clear this is not only discouraged but forbidden as well.

**Comment by Phyks** [comment]
See https://github.com/cyclosm/cyclosm-cartocss-style/issues/225

**Comment by Phyks** [comment]
Mostly fixed by #236.

**Comment by Florimondable** [comment]
a map with cross on limited access road is visible with the MTB OSM map http://mtbmap.cz/#zoom=18&lat=45.927382&lon=6.148454
