### ISSUE TITLE
Render class:bicycle ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#139]
Should we implement the rendering for keys https://wiki.openstreetmap.org/wiki/Key:class:bicycle
Used by the local bicycle association in Lannion France, https://www.openstreetmap.org/way/204047465

May be we can use the three colors of maxspeed/access.

**Comment by Phyks** [comment]
I'm not a huge fan of these. The wiki page seems very complicated and subjective. From CyclOSM render point of view,

* There are **6** different categories of cyclists defined. Which one should we consider for CyclOSM? What should be the overloading order?

* From https://wiki.openstreetmap.org/wiki/Key:class:bicycle#Examples_where_no_class:bicycle_is_needed, it seems the example in Lannion is precisely a case where the value should not be set. This is a primary road, with high maxspeed, this is for sure not desirable.

* How should the values of `class:bicycle` overlap with maxspeed or access? (if a road has both maxspeed, access and `class:bicycle` for instance, what are the priorities?)
