### ISSUE TITLE
Render highway=steps

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#14]
Steps are not rendered differently than regular paths at the moment.

![screenshot_2019-01-26 cyclosm](https://user-images.githubusercontent.com/3856586/51792956-4877fc00-21b9-11e9-9a2a-626a56dc30ae.png)

Location: https://tiles.phyks.me/#17/48.84285/2.38746

**Comment by Florimondable** [comment]
Please render also the ramp property for bicycle
https://wiki.openstreetmap.org/wiki/Key:ramp
Bicycle friendly are :
ramp:stroller=yes
ramp:bicycle=yes 
ramp:wheelchair=yes

**Comment by Phyks** [comment]
Done in #41
