### ISSUE TITLE
Side way rendered over main road cycle track

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#141]
Example here with G. Mandel avenue cycle track is rendered under the central alley.
https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/48.8634/2.2784

**Comment by Phyks** [comment]
This is actually another instance of https://github.com/cyclosm/cyclosm-cartocss-style/issues/115.

**Comment by Florimondable** [comment]
Looks like, but I don't think the technical issue is the same, in 115 its same road levels who hide the cycletrack border.
Here we have a low level road hiding the border (cycletrack) of a high level road

**Comment by Florimondable** [comment]
As I look at this junction https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.86391/2.27748 we see that border is always under other ways...

Difficult bug.
