### ISSUE TITLE
Some POIs are hidden at higher zoom

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#142]
See https://cyclosm.github.io/cyclosm-cartocss-style/example.html#17/48.87689/2.36456 and zoom in. The drinking water in the park is hidden.

**Comment by Florimondable** [comment]
same problem with the bicycle parking near the Robinet D'Or restaurant, hidden by its icon depending of the zoom
see https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.87818/2.36487

**Comment by Phyks** [comment]
This seems to be fixed so far.
