### ISSUE TITLE
Path with bicycle=designated

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#143]
A Path with bicyle=designated is renderd like a normal path. Some cycle track are modelised with tags 
highway=path
bicycle=designated
segregated=yes
This means there is a cycle track so we should render them like normal highway=cycleway

If segregated is not present or is =no we should render them more like a cyleway (less green more blue, as wide as cycleway (with the management of oneway)).

**Comment by Florimondable** [comment]
This ticket should be more on how to render green way ( https://wiki.openstreetmap.org/wiki/FR:Bicycle#Voies_vertes )
May be we should render path depending on there width also.

**Comment by Dardy87** [comment]
confirm, the path rules seems too generic, below an example:
https://www.openstreetmap.org/way/132088570
It's a cycleway shared with pedestrian, it should be rendered near to blue.

Instead below a path for bicycle and pedestrian, but the cycleway is segregated
https://www.openstreetmap.org/way/557624769

Both are rendered in the same way (dark green) but they should result as cycleways, not paths

**Comment by Phyks** [comment]
@Florimondable I think this one can be closed after your latest PR (#184). Isn't it?

**Comment by Florimondable** [comment]
I hope so :D
