### ISSUE TITLE
Secondary under bridge don't the right color

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#144]
See here rue Westermeyer https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.81847/2.39573
it is white instead of yellow

**Comment by Phyks** [comment]
This is done on purpose (tunnel style). Do you think it should be the same color?

**Comment by Florimondable** [comment]
It looks like it is white, but may be it's juste faded.
It looks little weird for me.

**Comment by Phyks** [comment]
Indeed, it was only lighten. The lighten effect was too strong, I changed it. https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/roads.mss#L1924-L1940

For a primary:

![Capture d’écran 2019-07-15 à 16 54 41](https://user-images.githubusercontent.com/3856586/61225641-43841600-a721-11e9-9c36-894aacc7fd4b.png)


For a secondary:

![Capture d’écran 2019-07-15 à 16 54 44](https://user-images.githubusercontent.com/3856586/61225658-4a128d80-a721-11e9-952e-b4b8fe736cfe.png)

**Comment by Florimondable** [comment]
Nice
