### ISSUE TITLE
Handle living_street=yes

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#146]
See https://wiki.openstreetmap.org/wiki/Key:living_street

An `highway=secondary` + `living_street=yes` should be considered as an `highway=living_street`, probably with a slight penalty compared to the latter one.

**Comment by althio** [comment]
Maybe something should be kept similar to `highway=secondary` rendering (eg. 'secondary' casing).

See also more related discussion/background https://github.com/gravitystorm/openstreetmap-carto/issues/3514

**Comment by Florimondable** [comment]
«It is supposed to mark a road that has a different classification than 'living street' but is a living street.»
living_street=yes is a something different than a proper living street, so I think we should not trust this tag alone to know if a street is quiet or not.

**Comment by Phyks** [comment]
`living_street=yes` is deprecated as per the wiki and rejected on the main osm.org render.

I'll close this issue for the moment as not relevant directly for CyclOSM render then. It might still be a really useful feature (I think so, at least), so we should probably try to resubmit it to tagging ML?
