### ISSUE TITLE
Render shared_lane?

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#148]
We currently do not render `cycleway=shared_lane`, such as https://www.openstreetmap.org/way/166351574.

In my opinion, these don't have much value for the cyclists, but might have a bit for the contributors. Not sure whether we should render them (and how)?

**Comment by westnordost** [comment]
In my experience, they are better than no cycleway at all (combined with a low speed limit, that is).

One suggestion how to render it:
- render any way where the bicyclists share the way with others dashed (bus lanes, shared lanes, advisory lanes, unsegregated foot+cycleways, bicycle roads that are not exclusive to bicyclists), others with a continuous line
- render the throughput of a road as the width of the line. I.e. bicycle roads, bus lanes, shared lanes are broad, unsegregated foot+cycleways are most thin

**Comment by Phyks** [comment]
This has been fixed in #200.
