### ISSUE TITLE
Render ATM

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#149]
`atm=yes` or `amenity=atm`

**Comment by Phyks** [comment]
Bank now rendered at Z18. ATM (`amenity=atm`) rendered at Z19. Discarded `atm=yes` so far since it seems to be almost exclusively used on banks / post offices.

**Comment by Florimondable** [comment]
For the moment I would like to avoid making Z19 special cases, more zoom level is more work.
For ATM I think they are as important as restaurant and should be seen at least from Z18.

**Comment by Phyks** [comment]
> For ATM I think they are as important as restaurant and should be seen at least from Z18.

Actually, they are a refinement of `amenity=bank`. See https://www.openstreetmap.org/#map=18/48.81846/2.31864 (bank at Z18) and https://www.openstreetmap.org/#map=19/48.81842/2.31886 (bank + atm at Z19). 

Moreover, Z18 is not a large zoom. We go up to 20 on cyclosm.org, we really need this in urban areas I think.

**Comment by Florimondable** [comment]
No they are not a refinement, many countries have just small ATM everywhere and not next to a bank office.

**Comment by Phyks** [comment]
> many countries have just small ATM everywhere and not next to a bank office.

In my experience (US + Iceland), ATMs are almost always in a larger shop. Typically, you know you should be looking for supermarkets / convenience stores and they'll likely have an ATM. Therefore, I'd consider the larger shop (supermarket / convenience for instance) the thing to be rendered and the ATM would be a subfeature upon zooming in.
