### ISSUE TITLE
Render highways depending on number of lanes?

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#15]
Should `lanes` be rendered somehow?

**Comment by Phyks** [comment]
Not sure this is very interesting in the end. Number of lanes is more or less already provided by the `highway` class in OSM. The really interesting metrics seem to be rather:

- The presence of a cycle infrastructure.
- The number of vehicles per hour and the maxspeed.

Plus rendering the number of lanes means taking more space for the large streets which we'd like to dim.

Feel free to comment if you think rendering the number of lanes is interesting in a cycling context!

**Comment by Florimondable** [comment]
Yes, I think we can put this feature aside.
