### ISSUE TITLE
Render bicycle_road=yes

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#150]
See https://taginfo.openstreetmap.org/keys/bicycle_road#overview

**Comment by tordans** [comment]
An example would be https://www.openstreetmap.org/way/36739044

We have a handful of those in Berlin and they are some of the best infrastructure we have.
Overpass query: https://overpass-turbo.eu/s/Mu7

**Comment by Florimondable** [comment]
Yes I'm thinking to make the fill color of the road as blue as cycle track, with the same size and border of the main _highway_ tag. Or may be lighter blue as it's still a shared road.

**Comment by westnordost** [comment]
Many/most bicycle roads I know in Hamburg allow cars as well. Maybe the rendering could be different depending on if bicyclists have the road all for themselves or if they have to expect either destination-traffic or even regular traffic.
In both cases, I always feel slightly tailgated by cars, even if they don't meant to do it. Bicycle roads that allow cars onto the road, to my experience, have some similarity to sharrows (`cycleway=shared_lane`) only that of course the legal status of cars vs bicycles is swapped.

**Comment by Florimondable** [comment]
My first point of view :
Cycle track : only cyclists
Cycle street : many cyclists, few cars

I understand from the tag page https://wiki.openstreetmap.org/wiki/Key:bicycle_road
that in Germany a cycle road is a road with forbidden motor vehicles by default.
Why not, that's local law, but in terms of OSM I would tag them as _highway=cycleway_ (even though I understand and I'm pro for that to split highway tag in more precise tags).
But I do think that the page is too much Germany oriented and the tag should not implied by default _vehicle=no_ (by the way a bicycle is a vehicle...).

So the result is :
_highway=cycleway_ : blue line
_cycle_road=yes_ : border streets and fill in blue (but lighter than cycleway)
_cycle_road=yes_ and _motor_vehicles=no_ : border streets and fill in blue (as cycleway)

**Comment by westnordost** [comment]
> I understand from the tag page https://wiki.openstreetmap.org/wiki/Key:bicycle_road that in Germany a cycle road is a road with forbidden motor vehicles by default.

I have not seen a single such road that is not at least `motorcar=destination` or even `motorcar=yes`. A bicycle road is basically a road that has been converted to "bicycles first".

**Comment by tordans** [comment]
> So the result is :
highway=cycleway : blue line
cycle_road=yes : border streets and fill in blue (but lighter than cycleway)
cycle_road=yes and motor_vehicles=no : border streets and fill in blue (as cycleway)

Sounds good!

> I have not seen a single such road that is not at least motorcar=destination or even motorcar=yes. A bicycle road is basically a road that has been converted to "bicycles first".

Agreed. 

For reference, this tool describes the signs and corresponding tagging (both in the left column) quite good http://osmtools.de/traffic_signs/?signs=244.1,1020-30

```
highway=residential # or similar
bicycle_road=yes
vehicle=destination
maxspeed=30
source:maxspeed=DE:bicycle_road
traffic_sign=DE:244.1,1020-30
```

Reading you comments above I will ask the author if "vehicle" is really the best key.

PS: Btw, a better tagging for "bicycle_road" would IMO be `highway=bicycle_road` but I fear this this ship has sailed long ago and will not happen (at least not for a long while until this type of roads are more common).

**Comment by Phyks** [comment]
> Reading you comments above I will ask the author if "vehicle" is really the best key.

There are many to take into accounts (and not I've never seen `vehicle` much around here): `vehicle`, `motor_vehicle`, `motorcar` etc, by increasing level of imbrication.

From https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation, I would actually say that `vehicle=destination` is wrong for a bicycle road (bicycle transit is allowed).


> a better tagging for "bicycle_road" would IMO be `highway=bicycle_road`

Not sure, we have a similar situation with `highway=living_street` which mixes both the infrastructure (`highway`) and the access restrictions `living_street`). This is really an issue since some streets have a `highway=secondary` status (I mean, they really are a secondary, from the number of vehicles and the general typology of the road), but have some magic signs `living_street` without any further infrastructure, which of course has nothing in common with a true living street.

**Comment by Florimondable** [comment]
Should be rendered as https://wiki.openstreetmap.org/wiki/Key:cyclestreet , example here https://www.cyclosm.org/#map=17/52.05982/5.14883/cyclosm
And I see there is an issue with maxspeed color overtake the cyclestreet color here (the section road just before the example).
