### ISSUE TITLE
Drinking water drinkable quality

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#152]
The quality of a drinking water point could be drawn :
unknown = grey
ok = green
no = red
might be = orange ?

See values of the key https://wiki.openstreetmap.org/wiki/Key:drinking_water

**Comment by Phyks** [comment]
What would be `unknown`? Just an `amenity=drinking_water` with no further precisions?

Not sure we want to make a difference between no precisions (grey) and `drinking_water=conditional` (orange). What do you think?

I would do:

* `drinking_water=yes` > green
* `drinking_water=no` > red
* `drinking_water=conditional` or no `drinking_water` > grey

Additionally, I don't like much the color scale red - green for water. Blue might be more suitable? Maybe usual blue (see bicycle sharing icon for instance) for drinkable water. Grey for unknown is fine. Not sure what to use for non-drinkable (maybe red).

**Comment by quasart** [comment]
In my experience, there is no use to display water tap if the water is not drinkable

**Comment by Phyks** [comment]
We currently only render `amenity=drinking_water` (and therefore, water should be drinkable) and `amenity=water_point + drinking_water=yes` (and therefore, water is drinkable as well).

What items did you have in mind @Florimondable?

**Comment by Florimondable** [comment]
drinking_water=yes
drinking_water:legal=no - There is a label "No drinking water".

Low priority ticket

**Comment by Phyks** [comment]
I agree with @quasart and I think there is no use cases (at least in the countries I'm familiar with, situation might differ in the southern hemisphere?) for displaying water which is not expected to be drinkable.

We should currently render all amenities with drinking water (`amenity=drinking_water` and water tap/point with `drinking_water=yes`). So I guess we can close this one.
