### ISSUE TITLE
Restore contour lines in online tiles

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#157]

**Comment by Florimondable** [comment]
@Phyks what are the difficulties to add contour lines ?

**Comment by Phyks** [comment]
Not much to do, contours lines should be available in db (I should just remember where). Then, it is just a matter of styling.

**Comment by Florimondable** [comment]
https://www.youtube.com/watch?v=HF4hJ_2aNg8
;)

**Comment by Phyks** [comment]
Closed by https://github.com/cyclosm/cyclosm-cartocss-style/pull/525
