### ISSUE TITLE
Label missalignment

### ISSUE THREAD

**Issue by tordans** [cyclosm/cyclosm-cartocss-style#159]
The label "Landwerkanal" at https://www.cyclosm.org/#map=17/52.49460/13.42707/cyclosm is above the buildings but it belongs to the water.

At https://www.openstreetmap.org/#map=17/52.49460/13.42707 it is place below the bridge above the water.

![Bildschirmfoto 2019-09-21 um 17 28 08 Kopie](https://user-images.githubusercontent.com/111561/65375386-3d686380-dc95-11e9-8b08-93699df43f60.jpg)
![Bildschirmfoto 2019-09-21 um 17 28 04 Kopie](https://user-images.githubusercontent.com/111561/65375387-3d686380-dc95-11e9-888a-46beaa6bbbeb.jpg)

**Comment by Phyks** [comment]
Thanks for reporting, this is definitely a bug in our render. I'll have a look at it.

**Comment by Phyks** [comment]
Should be fixed in `master` branch. It will be fixed on cyclosm.org generated tiles upon next version is released (probably within a week or so).
