### ISSUE TITLE
Make bike routes a layer?

### ISSUE THREAD

**Issue by tordans** [cyclosm/cyclosm-cartocss-style#160]
In Berlin, the bike routes are mostly unrelated to the bike infrastructure. As in: Whoever specified them did not make sure that there is actually good cycle infrastructure on the route, it might be regular streets, sometimes with high traffic.

Therefore, the relations are missleading when looking at the map from the point of view that tries to evaluate a good cycle route to drive save. Or to see how good the infrastructure is for a part of the city. 

On the other hand, this is infrastructure that has real world representation in the form of signs (which are being re-newed ATM https://www.infravelo.de/meldung/erneuerung-radwegweisung/; the signs are not in OSM ATM as far as I know).

Example: https://www.cyclosm.org/#map=18/52.48992/13.44018/cyclosm

So I wonder, what is the main message for the map? 
And if maybe the routes should be a second layer that can be activated on demand?

**Comment by Phyks** [comment]
Indeed, bicycle routes are an issue we are still struggling with and I sadly did not have yet a good answer on how they should be handled (see the discussion at https://github.com/cyclosm/cyclosm-cartocss-style/issues/55#issuecomment-466765323 for instance).

From my experience in France, `icn`, `ncn` and `rcn` are usually very good cycle routes with infrastructure and a local organizing authority. We wanted to have them rendered, especially at low scale, for long-distance bicycle touring. We tried to fade them away as much as possible at higher zoom levels to make sure the map focus on the infrastructure and the cycle routes are only eye guides at this scale.

Problem is people tend to add `route=bicycle` relations just to highlight the streets they are using and considering bicycle-friendly in OSM, a bit driven by the OpenCycleMap render. In Paris we have for instance https://www.openstreetmap.org/relation/8704875 which is a very good brand new infrastructure with bidirectional cycle tracks and desserves a relation in my opinion as this is a very structuring axis. But we also have https://www.openstreetmap.org/relation/8642809#map=14/48.8610/2.3394 which is a very bad route listed on maps (and small signs) from the beginning of the century and no longer maintained / without proper infrastructure.

One thing we considered was to remove them alltogether from the render and direct users to rely on [Waymarked Trails](https://cycling.waymarkedtrails.org/) for the overlay layers. This is still open to discussion.

We also plan at some point to have a lighter version of CyclOSM without the cycle routes (and probably with less POIs) to be used as a basis for custom maps (typically Umap).

**Comment by Florimondable** [comment]
> But we also have https://www.openstreetmap.org/relation/8642809#map=14/48.8610/2.3394 which is a very bad route listed on maps (and small signs) from the beginning of the century and no longer maintained / without proper infrastructure.

This is a very used route, may be not the best infrastructure but locally the best.

Here lies the problems with local routes :
- every one have his own preferences (subjective subject)
- official routes may not be maintained (not usable data)

A render map cannot change that state of fact, we can only decide wether we highlight routes or not.
That why I think a light version of CyclOSM could be a solution.

Or may be could improve the render of routes, ideas are welcome.
Fade international routes and regional routes at high zoom ?
Add tag to an official routes saying it is not a good/up-to-date route ? (and render it properly ?)

**Comment by Phyks** [comment]
Other examples. Here, 2.1 and 2.2 are actually quite sporty roads https://www.cyclosm.org/#map=13/45.8605/4.5300/cyclosm (no cycle infrastructure) but still with a local organizing authority and signs.

I suspect AJJ, PPP and PEP here to not have any physical existence on the ground: https://cycling.waymarkedtrails.org/#?map=15!48.8863!2.4005. No organizing authority, no signs but still cycle infrastructure and probably actually used by many cyclists.

Bicycle relations in OSM have too much different use cases and nature :/ This is probably a tagging issue in OSM though :/

**Comment by Dardy87** [comment]
Hello all, just started to follow the project, seems very good!
In my opinion a light version is the best choice, personally I prefer to have the cycle routes in another layer (Waymarked trails are very good), in order to customize the experience.
The cycle layer should show the real infrastructure, If I need to plan a trip I can activate the route layer in order to consider also other streets.
In Italy there are many cycle routes with signs that are not on a dedicated infrastructure.
