### ISSUE TITLE
Prioritize bad surface-style above 30km/h-style

### ISSUE THREAD

**Issue by tordans** [cyclosm/cyclosm-cartocss-style#161]
From the legend:
- gray: Bad surface (cobblestone / gravel / cyclocross)
- light teal: 30 km/h

In my opinion, the styling for this combination (cobblestone + 30km/h) could be simplified.
Example: https://www.cyclosm.org/#map=18/52.48237/13.45105/cyclosm

The way I understand the visulization it should help me to see if the road is feasable to cycle on. So in this case.
- yes, feasible cause 30km/h
- no, not feasible cause cobblestone

For me, the cobblestone is the more important info, so it should "win".
Or to put it differently: The cobblestone also will make the driving speed of the cars slower; is unlikely that someone will drive with 50km/h on cobblestone (or gravel).

The advantage would be to have the map visually cleaner in those cases.

**Comment by Phyks** [comment]
> The cobblestone also will make the driving speed of the cars slower; is unlikely that someone will drive with 50km/h on cobblestone (or gravel).

I've seen people regularly driving at 70km/h in a 50km/h cobblestone street in some places :/


> For me, the cobblestone is the more important info, so it should "win".

I'd think it is important to have both the surface and the max speed rendered. First, to have a consistent render across different highways (maxspeed and surface would both always be rendered, in a different manner so you can see where the visual information is coming from). Then, one of our goal was also to provide visualization tool for the lobbying orgs and mappers, not only cyclists and the info on which streets are 30km/h and which ones are not is quite important for them.

**Comment by Florimondable** [comment]
The bikability of a road depends on the trafic and the surface quality.
We aim different kind of cyclist with different tires and bikes (road bike vs city-trekking bike vs mountain bike). That why we split the quality surface in three categories and we don't want to merge the bikability in one map feature.
This way a cyclist can decide to ride with its own preference on the road he likes.
