### ISSUE TITLE
Very bright green parking lot

### ISSUE THREAD

**Issue by tordans** [cyclosm/cyclosm-cartocss-style#162]
I wonder why those two parking lots are so bright green?
- https://www.cyclosm.org/#map=17/52.48683/13.42457/cyclosm
- OSM: https://www.openstreetmap.org/way/60825550

Its looks more green that the "Pedestrian" design (https://www.cyclosm.org/legend.html)? But this does also not fit the tagging(?).

IMO those parking spaces should be neutral in color, they are nothing special form a cycle point of view.

**Comment by Phyks** [comment]
This one has `maxspeed=5` which according to OSM wiki means everyone should drive at walking speed. Therefore, it is considered by CyclOSM as a pedestrian area and very bike friendly.

**Comment by Florimondable** [comment]
A precisision : it's not considered as pedestrian area, but only as a very pedestrian and bike friendly (just based on maxspeed tag).

I can see one thing missing : there is no information on cyclosm that it is a parking lot (good to know to locate yourself). -> add a P icon ?

The tagging of the way don't say it is a _service=parking_aisle_, and we don't specialized the drawing with the tag service. That could be a good idea to render them smaller.
And we could deduce the bikability of a service highway with the _service_ tag, a _service=emergency_access_ should be very bikable for instance.
