### ISSUE TITLE
Cycling route label under route

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#165]
See label route 2 south of Poole (England) is cut by a maritime route.
https://www.cyclosm.org/#map=10/50.6564/-1.8883/cyclosm
Same issue at the entrance of the Portsmouth harbour
https://www.cyclosm.org/#map=12/50.7884/-1.1196/cyclosm

**Comment by Phyks** [comment]
I've moved bicycle routes on top of the ferry route label which should solve this issue.

![Screenshot_2019-09-27 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/65778700-a8f37a80-e146-11e9-97e1-d3c625c6714f.png)
