### ISSUE TITLE
Distinguish covered parking and bicycle box parking

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#166]
from «Juste un petit bémol : c'est dommage de ne pas différencier un peu plus
les parking vélo, notamment les parking couverts et les boîtes à vélo.»

**Comment by Phyks** [comment]
Which tags would make the distinction between the two types?

**Comment by Phyks** [comment]
- Here is a covered parking (public): https://www.openstreetmap.org/node/559672015
- Here is a covered parking with fee (subscription): https://www.openstreetmap.org/node/5502863121
- Here is a bicycle box parking (covered, with subscription): https://www.openstreetmap.org/node/6340036204

What about having a small hat on top of the bicycle parking if it is covered? That's the only thing we could easily add to distinguish further in my opinion.

**Comment by Florimondable** [comment]
I approve the small hat ô :)
