### ISSUE TITLE
Redo the color palette in the country in bright/fade color

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#167]
link to #155 but crops fields are also too dark.
Water could be more fade also.
(I really like OpenTopoMap colors)

**Comment by Phyks** [comment]
Also related to #194. Might be related to #171 somehow as well, although landuse is not the main feature to focus on.

We should also discard the salmon color for earth background, have it desaturated.

This is important in my opinion and we should have a look at it soon. Probably the best approach is to comment out everything but the landuses and tweak the palette to have a very pale but consistent background.

**Comment by Florimondable** [comment]
Landuse is usefull to find a proper camp site for the night ;)

**Comment by Florimondable** [comment]
Today country color is ok for me, it's quite nice I think.
