### ISSUE TITLE
POIs balance

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#169]
Let's face the difficulty to balance the POIs

A user : «Par ailleurs, certains POI (campings, eau potable, certains magasins) ne
sont rendus qu'à un zoom élevé, alors qu'ils sont aussi pertinents aux
zooms inférieurs.  Exemple :

https://www.cyclosm.org/#map=15/46.7570/-2.0100/cyclosm
https://www.cyclosm.org/#map=16/46.7571/-2.0147/cyclosm »

I can add that are maybe two much label names à Z16 ?

Since we got two more zoom levels (Z19 and Z20), we can may be move down some POIs by one level ?

Remenber the idea here is :
Bicycle first
First aids first
other POIs

Balance between city and country.

**Comment by Phyks** [comment]
I think we improved quite a lot on this recently. Closing this one for the moment, let's reopen specific issues for problems still to be solved.
