### ISSUE TITLE
Render repair station and compressed air

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#17]
See https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dbicycle_repair_station

and https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air

**Comment by Florimondable** [comment]
compressed_air=yes are not rendered (for gaz station for instance).
example https://www.openstreetmap.org/node/25214653

**Comment by Phyks** [comment]
Indeed, only `amenity=compressed_air` was added to render. Reopening to remember to add `compressed_air=yes` tag as well.

**Comment by Phyks** [comment]
Fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/fb7839ea22985a044632b83d173e10ca3945c8a9.
