### ISSUE TITLE
Check color blind accessibility

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#171]
Someone told me that it is hard for him to distinguish trafic (speed) colors we use for roads.
So we're looking forward from color blind people their feeling about the colors used.

From this color blind simulator https://www.color-blindness.com/coblis-color-blindness-simulator/
It seems that Green-Weak/Deuteranomaly and Green-Blind/Deuteranopia makes very hard to distinguish traffic (speed) color on road

![Green-Weak_Deuteranomaly](https://user-images.githubusercontent.com/47089717/65839863-b6109500-e311-11e9-9ed3-62b8ea48a315.png)

![Green-Blind_Deuteranopia](https://user-images.githubusercontent.com/47089717/65839864-b7da5880-e311-11e9-84f1-39b5ade87da5.png)

**Comment by PJDB22** [comment]
Sorry to comment on a closed issue, but I'm color blind (protanopia). I have trouble identifying speed limitation, specially the 30kph. Is it be possible to fade less ? (the light blue looks to me like white).

**Comment by Florimondable** [comment]
Hi, don't be sorry the issue is not closed.
We worked on new colors especially for speeds, can you have a look a the example pictures there https://github.com/cyclosm/cyclosm-cartocss-style/pull/350 ?

**Comment by Phyks** [comment]
I'm closing this one since we improved the current situation with #350. CyclOSM is still far from being perfect, so please do feel free to open issues on specific items which need improvements on the colorblindness accesibility side, they are truly useful!

Best,
