### ISSUE TITLE
Semi-transparent buildings?

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#172]
See https://www.cyclosm.org/#map=18/49.50775/3.49867/cyclosm

**Comment by Florimondable** [comment]
Not sure it opaque building is a good idea.
Do you have a picture of your change ?

**Comment by Phyks** [comment]
Typical example is

![2019-09-26-143253](https://user-images.githubusercontent.com/3856586/65687978-93108780-e06a-11e9-99e4-717e2eb2714a.png)

where buildings look different based on the landuse below.

They now look like
![2019-09-26-143249](https://user-images.githubusercontent.com/3856586/65688002-9e63b300-e06a-11e9-9254-eafa7d339323.png)

where the color is taken to be the one obtained when having semi-transparent buildings on plain landuse (therefore, the render is not changing at all in this case, it is only changed for building on top of a different landuse).

**Comment by Florimondable** [comment]
Hm, i think why the buildings are transparent : relief shading and curves !
If so we need to keep them transparent.

**Comment by Phyks** [comment]
Indeed, that was probably the reason. However, we no longer have shading nor curves at the moment (but they might be back soon). The current render with semi-transparent building is too misleading in my opinion, it's not clear whether this is actually a building or a stadium or anything else in the woods.

I'd be more in favor of keeping this change and investigate more the render when we add back shading and curves. We would probably need a multi-layer render here to have a good render of the buildings in a semi-transparent way, for shading and elevation curves.
