### ISSUE TITLE
Distinguish different types of bicycle lanes

### ISSUE THREAD

**Issue by westnordost** [cyclosm/cyclosm-cartocss-style#173]
In many countries, there are two types of bicycle lanes. Exclusive bicycle lanes and advisory bicycle lanes.

One and a half years ago, I did an extensive research in the quest to establish a tag for that. In a nutshell, it resulted in this tag documentation: https://wiki.openstreetmap.org/wiki/Key:cycleway:lane
The research about the different types of cycle lanes that led to that wiki page: https://westnordost.de/misc/bicycle_lanes.pdf

In my experience, the sharrows (bicycle pictograms on the road) are still better than nothing because car drivers tend to be more respectful of bicycle traffic. (So it would be nice if this was rendered somehow as well.) This might be just a local personal experience, I think the drivers in Hamburg, where I live, are uncertain what the bicycle pictograms mean legally and thus rather drive more careful and considerate. On shared bus lanes, I feel being tailgated by oncoming buses, on sharrows, I don't.

The advisory cycle lanes are to my personal experience actually, even though they give the bicycle a better legal status, only slightly better or about the same as the above. The reason being that they give the bicycles a fixed space, which is usually good, but
- sometimes it is too narrow to be safe (i.e. parking car doors to the right) and car drivers may expect that bicyclists keep strictly within their lanes
- cars often drive or halt on these lanes. Being an own lane, it is more stressful to change into the car lane to overtake the obstacle than if the bicycle pictogram was just printed on the road.

**Comment by westnordost** [comment]
FYI here is an overview what can be tagged with StreetComplete and how the are displayed in the UI in the different countries:

![cyclelanes](https://user-images.githubusercontent.com/4661658/65583126-f0c7a580-df7e-11e9-9e9e-8bcc89bf99c3.png)

**Comment by Florimondable** [comment]
Not sure to understand what feature you're asking :
Would you like to see if a highway with a lane with sharrow to be on the map ?

(For me a cycle lane is always without motor vehicles, but it is because we have not much sharrows in France)

About the street complete image, I wonder how they tag "dashe cycle lane" (for me it's a regular cycle lane) and "suggestion cycle lane".

**Comment by westnordost** [comment]
I am mainly asking for to have a visual distinction for the different values of ways tagged with `cycleway:lane`.

**Comment by Florimondable** [comment]
Ok, so we could render them :
_cycleway=lane + cycleway:lane=advisory_ : the default for cycleway=lane
_cycleway=shared_lane + cycleway:lane=pictogram_ and _cycleway=shared_lane_ : as shared bus lane, spaced dash line (as it is shared it is a third quality lane)

By the way don't understand what is precisely _cycleway=shared_lane + cycleway:lane=advisory_, but I think this is too much detail for this map.

**Comment by Phyks** [comment]
> as shared bus lane, spaced dash line (as it is shared it is a third quality lane)

In my personal experience, `cycleway=shared_busway` is better than `cycleway=shared_lane` since the lane is only shared with public transport (bus, taxis, …) vehicles, and not with a lot of different vehicles. These drivers should in theory be somehow aware of the sharing of the space with cyclist and take precautions. Plus sharing with public transport means fewer traffic than a regular lane.

**Comment by westnordost** [comment]
> By the way, I don't understand what is precisely cycleway=shared_lane + cycleway:lane=advisory

This only exists in Netherlands and Belgium, see https://nl.wikipedia.org/wiki/Fietsstrook#Fietssuggestiestrook_in_Nederland

**Comment by Florimondable** [comment]
> 
> 
> > as shared bus lane, spaced dash line (as it is shared it is a third quality lane)
> 
> In my personal experience, `cycleway=shared_busway` is better than `cycleway=shared_lane` since the lane is only shared with public transport (bus, taxis, …) vehicles, and not with a lot of different vehicles. These drivers should in theory be somehow aware of the sharing of the space with cyclist and take precautions. Plus sharing with public transport means fewer traffic than a regular lane.

That depends mainly of the traffic at the end.
Either way, I don't think it's a good idea to add a fourth cycle infrastructure map feature.

**Comment by Florimondable** [comment]
I think we can close this issue since #200

**Comment by westnordost** [comment]
If it is not planned to render the distinction between advisory and exclusive lanes then yes. But at least in Germany

**Comment by westnordost** [comment]
(pressed the wrong button)

**Comment by Florimondable** [comment]
> If it is not planned to render the distinction between advisory and exclusive lanes then yes. At least in Germany, they are quite some two different qualities of cycleways.

Distinction between advisory and exclusive are is planned.

**Comment by westnordost** [comment]
Well then better leave this open except of you already have another ticket for that.

**Comment by Florimondable** [comment]
Sorry I wrote "is" but I meant "is not" 😓

**Comment by westnordost** [comment]
Ok, too bad

**Comment by Phyks** [comment]
> If it is not planned to render the distinction between advisory and exclusive lanes then yes

Same as @Florimondable, I don't see a very good way to render them at the moment. Plus I have some troubles really perceiving the details of this kind of infrastructure (French cyclist, this does not exist in France and I've never had the occasion to ride a bicycle on such an infrastructure).

This being said, if this is something really important for some countries (Germany?), we could totally discuss how to represent it. But this means we need some local contributor to tackle this issue to have both a meaningful representation and a representation which fits with CyclOSM design guidelines.

**Comment by westnordost** [comment]
If you ever come to Hamburg, you can stay at my place and we can do a cycling tour of the city together :-) 

Am 29. November 2019 18:24:33 MEZ schrieb Lucas Verney <notifications@github.com>:
>> If it is not planned to render the distinction between advisory and
>exclusive lanes then yes
>
>Same as @Florimondable, I don't see a very good way to render them at
>the moment. Plus I have some troubles really perceiving the details of
>this kind of infrastructure (French cyclist, this does not exist in
>France and I've never had the occasion to ride a bicycle on such an
>infrastructure).
>
>This being said, if this is something really important for some
>countries (Germany?), we could totally discuss how to represent it. But
>this means we need some local contributor to tackle this issue to have
>both a meaningful representation and a representation which fits with
>CyclOSM design guidelines.
