### ISSUE TITLE
Harbour icon POI at Z16 is useless

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#176]
https://www.cyclosm.org/#map=16/48.8505/2.2828/cyclosm

**Comment by Phyks** [comment]
Sure, it looks weird in Paris. But look in Cherbourg, I'd say this is useful to have it at Z16 https://www.cyclosm.org/#map=15/49.6463/-1.6169/cyclosm.

There are for ferries and cruises, so there is almost always a very large boat parked there and it can be useful to orient on the map.
