### ISSUE TITLE
Don't render motorcycle_parking in red

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#177]
Red should be a color for danger, here with bicyle=yes it should be a more welcome color

**Comment by Florimondable** [comment]
After #198 I think we're good, yellow color for safe bicycle parking is ok.

**Comment by Phyks** [comment]
> yellow color for safe bicycle parking is ok

But yellow color should not be used for avoid / danger (typically `highway=primary|secondary` for instance).

**Comment by Florimondable** [comment]
Yeah, should we use purple ? We already using too much blue colors, and it's hard to distinguish

**Comment by Phyks** [comment]
Probably rather try to use symbols? wavy / barber wire casing etc?

> We already using too much blue colors, and it's hard to distinguish

The rule is generally at most 6 meaningful colors. This is one of the thing to rework soon.
