### ISSUE TITLE
Minimise highway with access=no

### ISSUE THREAD

**Issue by hugobqd** [cyclosm/cyclosm-cartocss-style#179]
For example, the access of the footway of this bridge is for forbidden :
https://www.cyclosm.org/#map=18/47.39160/0.64887/cyclosm

It could be faded, dashed or just light grey

**Comment by Phyks** [comment]
Thanks for the report, that's definitely something we should work on.

As a footway, bicycles have no access to this way and it should be faded in the next update, following https://github.com/cyclosm/cyclosm-cartocss-style/pull/178. Render of roads forbidden to bicycles should still be improved, see for instance https://github.com/cyclosm/cyclosm-cartocss-style/issues/138..

**Comment by Florimondable** [comment]
duplicate of #138
