### ISSUE TITLE
Spurious waterways rendered

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#180]
We should not render "La Bièvre" here: https://www.cyclosm.org/#map=19/48.84484/2.36516/cyclosm. Not sure where it is coming from.

![2019-09-26-115228](https://user-images.githubusercontent.com/3856586/65678723-225e7080-e054-11e9-81e8-14e4da12c690.png)

**Comment by Florimondable** [comment]
Can you also check underground water tank https://www.cyclosm.org/#map=19/48.88221/2.27954/cyclosm

**Comment by Phyks** [comment]
Yes, this one probably lacks a tag, something like tunnel=yes or so (maybe location=underground?) at least.
