### ISSUE TITLE
Emphaze cycle routes at low zoom

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#182]
from user : «Pour le coup, ça dépend du zoom.  À zoom élevé, effectivement, les
infrastructures sont sûrement plus intéressantes.  Mais à zoom faible, ce
sont les itinéraires qui devraient sauter au yeux.
Par exemple, au zoom 8, le trait gagnerait à être plus épais :

  https://www.cyclosm.org/#map=8/45.244/3.027/cyclosm

On distingue à peine les V70 et V74 au sud de Clermont-Ferrand (alors
qu'il s'agit d'itinéraires nationaux), et on voit encore moins bien le
GTMC en marron [https://www.openstreetmap.org/relation/3858890]»

**Comment by Phyks** [comment]
Should be fixed now.
