### ISSUE TITLE
opposite_lane rendering

### ISSUE THREAD

**Issue by quasart** [cyclosm/cyclosm-cartocss-style#188]
Hello everybody !

I've noticed two cycle lanes are rendered in both sides of the road when it's tagged `cycleway=opposite_lane`
Example : https://www.openstreetmap.org/way/312817142

This is wrong because we generally have only one (left side in France)

When reading tag wiki page https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dopposite_lane
I understand we should render nothing as we don't know where the lane is.

Correct line rendering is possible only if `cycleway:left=lane` is added.

I guess `cycleway=opposite_track` have the same issue.

**Comment by Phyks** [comment]
Indeed, `cycleway=opposite_lane` is unprecise with respect to the side of the street the cycleway applies. Then, there are three options:
* Try to "guess" the side of the street on which this apply, by using an heuristic based on right hand side or left hand side driving. Problem is this is very difficult to do in the render itself and the result can be very wrong (as bicycle lanes are sadly usually drawn where there is enough room…).
* Be conservative and do not display a side.
* Display it on both sides, using `cycleway` as a somewhat alias of `cycleway:both`.

I'd love to get rid of the `cycleway` tagging and just never display it, to promote `cycleway:left/right`. Sadly, this scheme is very much used around and it would result in a lot of cycle tracks/lanes to not be displayed in CyclOSM. Therefore, CyclOSM decides to do the latter, which seems to be the best compromise now: the user has the info about the existence of a cycle lane, and the mapper sees this is unexpected to have both sides and can go and edit to use a lateralized scheme.

Any `cycleway` value has the same value, `opposite_lane` (or track) but also regular `lane` or `track`.

Do you have a better idea to handle this?

**Comment by quasart** [comment]
Interesting

It's not a better idea, but I see a 4th option :
* to display it in the middle of the road, with a line, or with different arrows (longer ?)

**Comment by Florimondable** [comment]
Phyks explained well our choice.
I'd like just to precise something : `cycleway=opposite_xxx` is not bad tagging it is just not precise enough for rendering, but for routing it is fine.
