### ISSUE TITLE
Performance gain by merging casings

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#189]
I think we could merge normal casing and cycleway:right/left casing (and segregated path casing) in one rendering and have some performance gain.

That would result in the lost of normal casing under cycleway:right/left casing, but that not a problem I think.

**Comment by Phyks** [comment]
Sure, but if we move cycleways to a dedicated layer to be sure they are on top of everything else (#154, #136), this cannot be done :)

**Comment by Florimondable** [comment]
I don't think we want `cycleway=*` on top of everything, road intersections would be cut.

**Comment by Phyks** [comment]
> That would result in the lost of normal casing under cycleway:right/left casing, but that not a problem I think.

I like the casing behind the cycleway (especially the dotted ones, casing is important in this case in my opinion).


We don't have much performance issues at the moment and there are probably some easy wins to do on the SQL side for instance. Unless we indeed want to merge the casings for design purpose, I'd be in favor of closing this one.
