### ISSUE TITLE
Render factories

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#19]
They are easy to spot in the landscape and can be a source of pollution / noise when looking for a place to stay overnight.

Should we render factories? How?

**Comment by Phyks** [comment]
@Florimondable Isn't this done through the render of landuse=industrial at the moment as well as man made chimneys etc?

Otherwise, would you have the tags to render? Thanks

**Comment by Florimondable** [comment]
osm.org use landuse=industial
There is also bulding=industrial or buidling=warehouse, but osm.org don't render it (it render the building as usual building).
The landuse is enough I think.
