### ISSUE TITLE
Render back surface from Z14 

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#190]
As a gravel biker I'd like to be able to see track surfaces and path surface from zoom 14.
Example https://www.cyclosm.org/#map=14/49.7616/3.9646/cyclosm

**Comment by Phyks** [comment]
This one contradicts #156. Closing #156 in favor of this one.

**Comment by Florimondable** [comment]
fix by a479044dd5a168bd37bb90853a61185576fb6c54
