### ISSUE TITLE
Render sport raceway

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#191]
Render `highway=raceway` 
https://wiki.openstreetmap.org/wiki/Tag:highway%3Draceway

Example : https://www.cyclosm.org/#map=16/49.8005/3.9998/cyclosm

**Comment by Phyks** [comment]
Rendered as tracks now, IGN style.

![Screenshot_2019-10-09 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/66476849-e0dbb580-ea96-11e9-9e48-075476d73449.png)
