### ISSUE TITLE
Bridge Cycleway is rendered under bridge main road.

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#192]
The cycleways on the bridge are rendered under the bridge, should be rendered over the bridge to be seen from low zooms.
https://www.cyclosm.org/#map=17/48.81965/2.40017/cyclosm

**Comment by Phyks** [comment]
There could be an issue in CyclOSM code, which should now be fixed. Real issue is bad tagging here, I fixed it in https://www.openstreetmap.org/changeset/76087914#map=18/48.82036/2.40066.

**Comment by Phyks** [comment]
There seems to still be an issue in CyclOSM, see https://www.cyclosm.org/#map=17/48.81965/2.40017/cyclosm.

**Comment by Phyks** [comment]
I missed the fact that bridges always get a `+100` `z_order` bonus automatically, no matter the layer value: https://github.com/openstreetmap/osm2pgsql/blob/cc601f688cca6957db425da8751fcbc9ecb5d609/src/tagtransform-c.cpp#L70-L72. This is now fixed.

**Comment by Florimondable** [comment]
oh my
