### ISSUE TITLE
Way not rendered

### ISSUE THREAD

**Issue by Culdesac49** [cyclosm/cyclosm-cartocss-style#193]
A way is not rendered in Paris
see https://www.cyclosm.org/#map=20/48.84518/2.31125/cyclosm
Rue de Sèvres between Bd Garibaldi et Bd Pasteur

**Comment by Phyks** [comment]
This is really weird, not sure what is happening. It works perfectly for me on my local machine, even with the cyclosm.org database. Definitely a bug, will look into this.

Might be related to #175

**Comment by Phyks** [comment]
Seems this is fixed.
