### ISSUE TITLE
Not enough city names in country at ~Z11

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#195]
See https://www.cyclosm.org/#map=11/48.2750/3.6797/cyclosm
The difficulty here is that in urban areas the number of city names is ok.

**Comment by Phyks** [comment]
Sure, and the amount of city names is very hard to calibrate. For the record, we are using the exact same strategy as the osm.org tiles here.

**Comment by Florimondable** [comment]
Idea : in the SQL request we could order by place priority (bigger city first) and then cut the result by selecting only the X first. So if I'm not mistaken the megatile will be rendered only with the selected names. Depending of the names density we will have village names or not.

**Comment by Phyks** [comment]
Isn't it exactly what we are currently doing? https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L1150-L1194

**Comment by Florimondable** [comment]
> Isn't it exactly what we are currently doing? https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L1150-L1194

Not really, there is no cut in the result list.

Anyhow, it seems that's not the first issue, in France village is from 10000 inhabitant and below (until 100), which group places with very different size and services. Village is rendered only from z12, my first example is at 11 where I think we can render place between 10000 and 2000 inhabitant. At least for France.

**Comment by Florimondable** [comment]
For the record in France the population tag has been moved for many commune from the place node to the relation. So we lost the hierachy exemple :

avant
![9-48 85889-2 34765-ref](https://user-images.githubusercontent.com/47089717/74969386-c9391400-541c-11ea-9fea-5606dc6b1be7.png)

après
![9-48 85889-2 34765-test](https://user-images.githubusercontent.com/47089717/74969384-c9391400-541c-11ea-824b-c0dde05ed5ec.png)

**Comment by Phyks** [comment]
We are using exactly the same code as openstreetmap-carto here https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L1237-L1281

This should be an issue for them as well, isn't it?
