### ISSUE TITLE
Draw linear barrier like fence, city wall, ...

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#196]
Bercy park is divided in two part, one inside a fence not bikable, the other full open.
This must be rendered to avoid unpleasant surprise.
https://www.cyclosm.org/#map=19/48.83607/2.38154/cyclosm
https://www.openstreetmap.org/way/165439667#map=18/48.83577/2.38254

and retaining_wall ? 
https://www.openstreetmap.org/way/143562587#map=18/48.83623/2.38015

**Comment by Phyks** [comment]
Indeed, and same thing for any linear barrier maybe? https://www.openstreetmap.org/way/703103253

**Comment by Florimondable** [comment]
Yes, like citywall https://www.openstreetmap.org/way/146466925#map=17/49.56471/3.63039
(Bollard is not the most important linear to do at first though.)

**Comment by Florimondable** [comment]
fixed by #303
