### ISSUE TITLE
Render arrows for oriented bicycle routes

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#201]
Opacity instruction cannot be applied on a per-zoom level, see https://github.com/cyclosm/cyclosm-cartocss-style/commit/ce3fc7e0019f9ccdda867807e2a3c85673df8620.

To actually get the render we were expected, we would need to split the bicycle routes layers into per-zoom layers and apply different opacity.

Related to #131, #160 and #182. My opinion on this is we should rework these in depths:

* Bicycle routes should be displayed at low zoom with quite strong color to be well visible.
* They should start to fade out at Z9/Z10.
* At something like Z14 they should just provide a halo on the side of the road to make it visible for anyone actively looking for them (therefore rendered *below* the road with a slightly larger width). Opacity and overlapping would be much easier to handle, we would not mind a stronger halo.
* No need for arrows, see #131 as these would only be visible at high zoom were the cycle route is actually not much visible. Arrows  and directions are easy to infer from the rest of the items (infra / directions of traffic) and someone really looking into them will anyways use a GPX or a layer.

@Florimondable what do you think about this plan?

**Comment by Florimondable** [comment]
«At something like Z14 they should just provide a halo on the side of the road to make it visible for anyone actively looking for them (therefore rendered below the road with a slightly larger width). Opacity and overlapping would be much easier to handle, we would not mind a stronger halo.»
I don't think changing the way routes are rendered will look good when switching zoom levels.

I disagree, we still need the direction of the routes at medium-high zooms.

**Comment by Phyks** [comment]
Most of the current issues should have been solved in https://github.com/cyclosm/cyclosm-cartocss-style/commit/dd53e0c27c8ba7f03cf506d959bfc9421a959ff7. Still some fine-tuning to do probably and the question of arrows for direction.

**Comment by Phyks** [comment]
Duplicate of #131. Closing this one.
