### ISSUE TITLE
East Asia characters not drawn properly

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#202]
See around Korea mostly, Japan and China too.
https://www.cyclosm.org/#map=6/35.595/129.716/cyclosm

**Comment by Phyks** [comment]
Rendering server bug, I sent a message to Jocelyn, this should be fixed soon (well, 3 days for the tiles expiry).

**Comment by Florimondable** [comment]
Seems to fixed :+1:
