### ISSUE TITLE
Render motorway with bicycle=yes

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#203]
In some countries cyclists may be able to ride on a motorway.
Could render those roads with a traditional red/orange motorway color.

**Comment by Phyks** [comment]
Typical example is https://www.openstreetmap.org/way/43877500#map=16/41.9774/-73.9467 which you probably really want to take unless you want a 50km detour (although this one has a bicycle relation on top, so it is a bit cheaty).

> Could render those roads with a traditional red/orange motorway color.

Another idea : use the motorway color (very pale, greyish) slightly saturated with blue. I really want to avoid red/orange for things which should not be seen at first on the map.

**Comment by Phyks** [comment]
Another idea, just render them as a third-grade infrastructure as you usually have to cycle on the shoulder.

What do you think?

**Comment by Florimondable** [comment]
Why not, not a bad idea, but that would complicate the key. Because grey color means no bicycle access with the new feature coming, so making a cycle shoulder on a grey motorway would mean a weird tagging.

So I think I'd prefer to try with orange/red pale.
A quick image editing :
![try_motorway_pinky](https://user-images.githubusercontent.com/47089717/69371156-8c377700-0c9f-11ea-8c0a-29ed8863a660.png)

**Comment by Phyks** [comment]
Indeed. My only concern with this is discoverability by users (without digging in the legend).

**Comment by Phyks** [comment]
Done with a very pale red.

![2019-12-01-185025](https://user-images.githubusercontent.com/3856586/69917903-724e1f00-146b-11ea-825c-0c53fd76bed0.png)

Note these are fake data, just for the purpose of testing the render.

**Comment by Florimondable** [comment]
Great, could have been more pale I think, as pale as the yellow in the picture I think
