### ISSUE TITLE
Try to simplify geometries

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#205]
Using https://postgis.net/docs/ST_SnapToGrid.html.

**Comment by Florimondable** [comment]
Which geometries for what purpose ?

**Comment by Phyks** [comment]
First, try with the bicycle routes, but we can then add more. The goal is to reduce the network traffic between the database VM and the render VM by lossy compressing the data (we don't need very refined data at low zooms). See for instance https://github.com/cquest/osmfr-cartocss/blob/master/osmfr.yml.

**Comment by Phyks** [comment]
Done for low zoom levels in 6155ef6e9b839c8da1e4e1836af983b881a7e7ca.

SQL tuning helper script now shows the size of the fetched data.
