### ISSUE TITLE
Rework road network colors

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#206]
Once landuses have been reworked in pale colors (#167) we should rework the road network colors.

After discussing with a designer, here are a few raw feedbacks:

* Green for pedestrian is catching a bit too much the eye, hiding a bit the blue for bicycles.
* We have too many colors. We should not distinguish `motorway`, `primary` and `secondary`. We can have light variations in the grey scale among them, but they are basically equally bad for bicycles. At https://www.cyclosm.org/#map=17/48.84223/2.32261/cyclosm, we only see "Avenue du Maine" the large "boulevard" which are very bad (and forbidden to bicycles :).
* Tertiary road network is the most interesting for bicycles. We might be able to enlarge it a bit to make it more present and readable.
* Casing is too strong and darkens a bit too much the map, https://www.cyclosm.org/#map=15/48.8584/2.3519/cyclosm

* We can also play on the casing with barber fence-like casing (- x - x - x).

Her opinion was that it might be better to hide everything except landuse and road network layers and try to color back with greyscales except for bicycle-friendly axes where we would put colors to emphasize them.

**Comment by Florimondable** [comment]
«Green for pedestrian is catching a bit too much the eye, hiding a bit the blue for bicycles.» done by #174 ? 
« We should not distinguish motorway, primary and secondary. » I Disagree, a secondary is still more bikable than a primary so this is a usefull information, specialy for road cycling who may prefer secondary than primary and bad tertiary. Or when you can't avoid big roads.
