### ISSUE TITLE
Render administrative boundaries

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#209]
Should be very light, hinted, this is not the main focus of the map.

Use case: for lobbying / associations. https://www.cyclosm.org/#map=16/48.8525/2.4318/cyclosm where does Vincennes ends? Where does Montreuil starts?

**Comment by Phyks** [comment]
As well as country borders.

**Comment by Florimondable** [comment]
I think countries and states are very important borders for legal situation. Others not much.
