### ISSUE TITLE
Render food shops

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#21]
In particular:

- [ ] `shop=supermarket`
- [ ] `shop=bakery`
- [ ] `shop=convenience`
- [ ] `shop=green_grocer`
- [ ] `shop=pastry`

**Comment by Florimondable** [comment]
Render shop=convenience
https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dconvenience
«Une épicerie ou supérette (au Québec, un dépanneur) est un petit commerce local...»

Example https://www.openstreetmap.org/node/25214653

Should render also amenity=fuel ?

**Comment by Phyks** [comment]
In my opinion, `amenity=fuel` should only be for selling fuel and the convenience shop eventually there should be tagged separately, as done on https://www.openstreetmap.org/node/25214653. Not sure how this is usually tagged in OSM though.

`shop=convenience` is already rendered, the issue here is due to the multiple values for the `shop` I think, and `osm2pgsql` is probably not importing it well. I created https://github.com/cyclosm/cyclosm-cartocss-style/issues/62 to track this.
