### ISSUE TITLE
Bus way rendered as no car road

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#210]
Rue du Renard have a bus way https://www.openstreetmap.org/way/555199446
It is rendered with the color cyan "no motor vehicle access" though it has bus and taxis driving on it.
see https://www.cyclosm.org/#map=20/48.85835/2.35202/cyclosm

tags:
```
access=no
bicycle=yes
psv=yes
```

**Comment by Phyks** [comment]
https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L475 should be refined with `vehicle` (beware, this one applies to bicycles as well!), `motor_vehicle` and `psv`. Eventually taking into account `motorcar` and `bus` as well.

**Comment by Phyks** [comment]
I think it would end up with something like

```
SELECT (
    (access = 'no' ) AND (
        vehicle IS NOT NULL AND vehicle != 'no' AND (
            motor_vehicle != 'no'
            OR motorcar != 'no'
            OR psv != 'no'
            OR bus != 'no'
        )
        OR (
            motor_vehicle IS NOT NULL AND motor_vehicle != 'no'
            OR motorcar IS NOT NULL AND motorcar != 'no'
            OR psv IS NOT NULL AND psv != 'no'
            OR bus IS NOT NULL AND bus != 'no'
        )
    ) OR (
        vehicle = 'no' AND (
            motor_vehicle IS NOT NULL AND motor_vehicle != 'no'
            OR motorcar IS NOT NULL AND motorcar != 'no'
            OR psv IS NOT NULL AND psv != 'no'
            OR bus IS NOT NULL AND bus != 'no'
        ) OR (
            motor_vehicle != 'no'
            AND motorcar != 'no'
            AND psv != 'no'
            AND bus != 'no'
        )
    ) OR
) AS motor_vehicle
…
```

where I ignored the distinction between `yes` and less permissive access values such as `destination`. I should benchmark something like this in the roads layer to measure the performance impact on SQL queries.

**Comment by Phyks** [comment]
I came up with

```
CASE
  WHEN (
    tags->'psv' != 'no' OR tags->'motorcar' != 'no' OR tags->'bus' != 'no'
    OR tags->'motor_vehicle' != 'no'
    OR tags->'vehicle' != 'no'
    OR access != 'no' OR access IS NULL
    ) THEN 'yes'
  ELSE 'no'
END AS motor_vehicle,
```

which should do the trick.
