### ISSUE TITLE
render cycleway=opposite_lane

### ISSUE THREAD

**Issue by MathiasVadot** [cyclosm/cyclosm-cartocss-style#213]
It is currently 2 lanes on a street with the tag cycleway = opposite_lane
Logically the street as only one lane. 
![image](https://user-images.githubusercontent.com/16226890/66487453-a11fc880-eaac-11e9-8604-f264d51620b4.png)

**Comment by Florimondable** [comment]
Same as #188, in french :

Bonjour Mathias, malheureusement cycleway=opposite_lane ne permet de connaitre le côté de la bande. On pourrait définir que par défaut ça veut dire à gauche, mais en Angleterre c'est à droite.
Donc faudrait faire le rendu suivant l'endroit. De plus on peut avoir des bande de contre sens à droite (cas d'infra étrange :/)
On recommande de mettre cycleway:left=opposite_lane qui est plus précis.

**Comment by MathiasVadot** [comment]
a oui je n'avais pas pensé aux pays qui roulent à gauche.. ok donc la représentation est prévu pour afficher une seul bande dans le cas cycleway:left=opposite_lane
