### ISSUE TITLE
Footway + bicycle=yes is path

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#215]
User issue:
https://www.reddit.com/r/openstreetmap/comments/d8mv1y/cyclosm_worldwide_release_at_sotm2019/f1wnomx/
«See for example https://www.cyclosm.org/#map=17/47.39015/8.40058/cyclosm along Bernstrasse there is an essentially perfect cycleway (https://www.mapillary.com/app/?lat=47.39439698&lng=8.40583019&z=17&pKey=yMkm9H1k-FXRo_XexcyMrQ&focus=photo), on the other hand the forest tracks nearby are just barely usable for cycling.»

Analysis :
https://www.openstreetmap.org/way/104156324#map=17/47.38849/8.39765
The tagging is may-be wrong here, it should be more a path.
But here lies the ticket if your read the footway page https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway 
«Where a pathway is designated for pedestrians but is also allowed for bicycles you can use highway=footway and bicycle=yes.»
So footway with bicycle access tags should be rendered as we do for path.

**Comment by Phyks** [comment]
This is `highway=footway` + `bicycle=designated`, which in my opinion is a bad tagging (if it is "designated", it should be a path, since both are on equal ground).

`highway=footway` + `bicycle=yes` is different though, this is a valid tagging for a footway which is accessible to bikes. I would render it in a similar way to a path, although I'd like to have some hint of the difference. Comparing with https://www.cyclosm.org/#map=20/48.81728/2.31540/cyclosm, we could slightly reduce the width of the blue and increase the width of the green (or completely swap the green and blue) to give this idea of pedestrian-first.

**Comment by Phyks** [comment]
Note that our validation rules are written with `designated` in mind and would consider the current tagging in your example as invalid https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/validator/cyclosm.validator.mapcss#L13.

**Comment by lamyseba** [comment]
Hi! Here in France we've got something called "voie verte". It's a path for pedestrian and bicycle. But it is a pedestrian-first path. 
The french openstreetmap wiki recommends to tag this with `highway=path` and `bicycle=designated` and `foot=designated.` 
https://wiki.openstreetmap.org/wiki/FR:Bicycle#Voies_vertes
This kind of legislation, wich was primarily designed to be used on path away from urban areas, is also used inside urban areas, converting broad footway into a path open for cycling. But it keeps being pedestrian-first. Through this kind of path is a very safe place to ride, you cannot expect to go as fast as you would on a separate cycle path. The proposal of swaping green and blue to show this seems interesting to me.

**Comment by lamyseba** [comment]
Or maybe I did not well understood what is meant by "path designated for bicycle". Anyway the colours (blue) are very similar with "separate cycleway", and I'm barely able to distinguish them on the map

**Comment by Florimondable** [comment]
Examples here https://www.cyclosm.org/#map=17/48.81840/2.46227/cyclosm
Yes colors are similar, may be one day we should rework them.

**Comment by Florimondable** [comment]
Here a discussion on tagging showing that it's a mess, and a footway + bicycle is used by a lot of people, so we should render them as path.

**Comment by Florimondable** [comment]
We aim to render : cycle way, designated bicycle path (seggregated or not), path, foot way, bridle way
Since interpretation of tags `cycleway`, `path` and `footway` is wide, and access tags is used to counter balanced that I propose this:

path + bicycle=designated -> designated path
footway|bridleway + bicycle=yes -> path
footway|bridleway + bicycle=designated -> designated path

**Comment by andrewharvey** [comment]
> We aim to render : cycle way, designated bicycle path (seggregated or not), path, foot way, bridle way
> Since interpretation of tags cycleway, path and footway is wide, and access tags is used to counter balanced that I propose this:
> 
> path + bicycle=designated -> designated path
> footway|bridleway + bicycle=yes -> path
> footway|bridleway + bicycle=designated -> designated path

Sounds great.

Since we use =designated if a feature is signposted for that access class, a regular pedestrian footpath that is signposted for bicycles would be highway=footway + bicycle=designated, and should still be rendered as off road cycle infrastructure.

**Comment by Florimondable** [comment]
bridleway + bicycle=designated is used a lot in England
