### ISSUE TITLE
CyclOSM style for Maperitive (.mrules)

### ISSUE THREAD

**Issue by Symbian9** [cyclosm/cyclosm-cartocss-style#216]
Create `cyclosm.mrules` rendering style for [*Maperitive*](http://maperitive.net/)

1. http://maperitive.net/docs/Rulesets.html
1.1. http://maperitive.net/docs/#Rendering%20Symbols
1.2. http://maperitive.net/docs/#Rendering%20Properties
2. https://github.com/klangfarbe/sublime-maperitive

FTR, I has it on own TODO, but any help would be great.

### REFERENCES

- https://github.com/IvoVargas/better-carto-maperitive-render-rules
- https://github.com/VS-DavidSouth/Maperitive_rules_scripts
- https://github.com/EugenyN/Magellan
- https://github.com/OndrejSpanel/maperitive-rules-cz-hiking
- https://github.com/hdevillepoix/OSM-MTBO-Maperitive
- https://github.com/werzum/ContourLines

**Comment by Phyks** [comment]
Hi,

Do you know about tools to easily convert from CartoCSS to Maperitive mrules? Without such tools, I'm not sure we have the workforce to convert it to Maperitive (and especially maintain the two versions in the long run :/).

Best,
