### ISSUE TITLE
Steps - Brighter? Fader?

### ISSUE THREAD

**Issue by quasart** [cyclosm/cyclosm-cartocss-style#217]
Hello,
Because stairs are very annoying when cycling, and simply impossible to use if you have a cargo or a wheelchair, I think they should be red.

**Comment by Phyks** [comment]
So far, stairs have been considered a pedestrian feature and rendered in green (which is pedestrian color). The legend is built around this idea that blue is for bikes and green for pedestrians and the intensity of the color shows how walkable / bikable a way is.

One problem I see with using red for "danger" / "not suited" is that red is very eye catchy and it would probably put a lot of emphasis on these features that we precisely want to hide away.

**Comment by quasart** [comment]
Red color choice may be too extreme, and I'm aware you should not display too much for readability. But I think stairs should catch eyes because they are "not suitable" for wheels, and green hides them too much.

As a lazy cyclist, I want to use the shorter route even if I need to dismount from my bike and push it along a pedestrian path I find on the map, but I want notice stairs to chose alternative route without stairs when possible.

If I had a heavy cargo, it's even impossible to cross them. A path with stairs becomes a dead end.

Pedestrian areas in city center may be open to bicycles and full of stairs. A very big natural park may only have a couple. In both cases, I think highlighting them is valuable. In the second one, the stairs should even be visible from zoom=16 IMHO.

And after all, stairs accessibility is even bad for some pedestrians : stroller, reduced mobility or wheeled-luggage.

**Comment by quasart** [comment]
Here you can find examples of `way[highway=path][bike=yes]` that end to stepways 
https://www.cyclosm.org/#map=18/47.19147/-1.57208/cyclosm

stairs are quite hard to notice if you're not looking for them :
https://www.openstreetmap.org/way/31023340
https://www.openstreetmap.org/way/222047316

**Comment by quasart** [comment]
Not sure if it's possible with carto, but what do you think about highlighing stepways that have both endings connected to ways accessible to bikes ?
This way pedestrian area are no impacted

**Comment by Florimondable** [comment]
Not sure it is technically feasible

**Comment by Phyks** [comment]
> Here you can find examples of way[highway=path][bike=yes] that end to stepways

Oh, this is indeed a very tricky example!

> highlighing stepways that have both endings connected to ways accessible to bikes ?

This is definitely possible but is probably quite resource-intensive for the database (sophisticated queries involved). We should try and benchmark this, to see if the performance impact on tiles (it would mainly be operating at high zoom) is reasonable.

**Comment by Florimondable** [comment]
I guess we can close this ticket ?

**Comment by quasart** [comment]
Hello, I love the new brown footway color : It fixed this issue, thanks

**Comment by Phyks** [comment]
Thanks for the feedback!
