### ISSUE TITLE
motor_vehicle=no not in Cyan (no car access color)

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#222]
Route de Suresnes is not in "low speed or no car access" cyan color
https://www.cyclosm.org/#map=20/48.87113/2.27180/cyclosm
https://www.openstreetmap.org/way/24680602/history
but have a `motor_vehicle=no`

Every road in the wood are broken on that :(
It's a regression.

**Comment by Phyks** [comment]
Fixed
