### ISSUE TITLE
secured parking icon proposition

### ISSUE THREAD

**Issue by quasart** [cyclosm/cyclosm-cartocss-style#226]
Hello everybody,
I like the little roof you've just added on the covered bicycle parking.

I think secured parking icons could follow the same idea : the blue mark could be "locked" inside a little square. Here is a preview/comparison, first line is current, bottom line is what I have in mind
![icons](https://user-images.githubusercontent.com/3080387/67560876-0d8cff80-f71c-11e9-9611-62e0668f250a.png)

This looks more understandable and more consistent to me.

**Comment by Florimondable** [comment]
I like the idea
