### ISSUE TITLE
Render more natural

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#229]
I’m thinking of glaciers, wetland, rocks, sand...

**Comment by Phyks** [comment]
Partially addressed in #273. Still some further investigations and eventual missed landuse to render.

**Comment by Phyks** [comment]
I added render for glaciers.

http://localhost:6789/cyclosm-cartocss-style/#17/45.46054/6.36729
![2020-03-18-225722](https://user-images.githubusercontent.com/3856586/77011310-e1447a80-696b-11ea-88d7-76d8cded9571.png)

Feel free to update colors etc if you have a better idea.

Closing this one as most of the natural / landuse are now rendered. Let's open new issues if we spot additional missing ones.

**Comment by Florimondable** [comment]
Comparing with osm.org, the blue is may be too blue (like water), can you try to make it more white to feel it more like ice. You can use the same color as osm.org.

**Comment by Phyks** [comment]
Indeed, I'll edit it.
