### ISSUE TITLE
Hide routes not for cycling

### ISSUE THREAD

**Issue by lamyseba** [cyclosm/cyclosm-cartocss-style#230]
Hi, First of all congratulation for the great work you do.

 in Pau (France), we've got a motor race every year, and the route of the race is referenced with the type "racetrack". The name of the route is "Circuit de Pau Ville". It has nothing to do with cycling, but the name appears on the cyclosm map, melting with the streets names it passes by. A few day ago there was even a line showing the route, same as the line for cycle routes, but not the same colour. The line disappeared, but the name "Circuit de Pau Ville" still appears.

Could you have cyclosm not showing this kind of route name, that is not for bicyle ? (same as public transport routes).

**Comment by Florimondable** [comment]
Hi, I can't find it do you have a screenshot or a link ?

**Comment by lamyseba** [comment]
https://www.cyclosm.org/#map=18/43.29332/-0.36635/cyclosm
A sample case: Look for Avenue Napoléon Bonaparte, Pau, France
You'lle see written "Avenue Napoléon Bonaparte Circuit de Pau Ville" on the map.

**Comment by Florimondable** [comment]
So we have a relation with:
https://www.openstreetmap.org/relation/9954713#map=17/43.29443/-0.36319
`highway=raceway` must be the issue, not sure it is a valid tagging.
Eitherway there is no good reason to render it names I think.

**Comment by Phyks** [comment]
Osm.org default render has the exact same issue. For me (and it seems according to the wiki), highway=raceway is invalid tagging here.

See the tagging at Monaco for instance https://www.openstreetmap.org/relation/148194#map=16/43.7367/7.4258.

Closing as it is due to bad tagging.
