### ISSUE TITLE
Regression : lost arrow direction on shared path

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#231]
See https://www.cyclosm.org/#map=18/48.81816/2.31628/cyclosm

**Comment by Phyks** [comment]
This was due to these being a `path` with a `oneway:bicycle` and no `oneway`. Should be fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/3e3f9f6350fea1dff6d14058842ecc3b1cdef082.

**Comment by Phyks** [comment]
Reopening this one, handling oneway arrow for bicycles is a mess at the moment.

Part of it is done in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/labels.mss#L416-L460 and part of it is done in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/roads.mss#L936-L967.

We should factor these to have a single place to handle oneway arrow. See as well related issue #260
