### ISSUE TITLE
Cycleway not rendered through tunnel

### ISSUE THREAD

**Issue by DaveF63** [cyclosm/cyclosm-cartocss-style#234]
Hi
https://www.cyclosm.org/#map=15/51.3639/-2.3492

Is there a specific reason Cycleways are not rendered through tunnels?
https://www.openstreetmap.org/way/39042117#map=17/51.36990/-2.36594

**Comment by Florimondable** [comment]
No, this is a bug.
But I can't understand why it's not drawn where as here it's ok https://www.cyclosm.org/#map=19/48.86459/2.31979/cyclosm
https://www.openstreetmap.org/way/724081039

**Comment by Florimondable** [comment]
Same issue here https://www.openstreetmap.org/way/124759292 https://www.cyclosm.org/#map=15/45.0035/3.8913/cyclosm
May be cause of I guess (we don't render underground railway)
```
railway=abandoned
tunnel=yes
```

**Comment by DaveF63** [comment]
So a test for the value of the railway tag needs to be included to ignore abandoned/disused/razed?

**Comment by Florimondable** [comment]
highway tag should prevail over railway one I'd say.

**Comment by Phyks** [comment]
This is indeed a bug. We hide any `railway` with `tunnel=yes` (https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L529). It should probably read

```
railway NOT IN ('light_rail', 'subway', 'narrow_gauge', 'rail', 'tram')
```

instead of the `railway IS NULL` test.

**Comment by Florimondable** [comment]
I'm not sure, I think we can have the real case of a tunnel with a road shared with a train (with rail on it), like :
```
highway=tertiary
railway=tram
```

**Comment by Florimondable** [comment]
few examples in île de France:
https://www.openstreetmap.org/way/190293163
https://www.openstreetmap.org/way/310782687
https://www.openstreetmap.org/way/41080494

I think we should render as long as there is the `highway` tag.
