### ISSUE TITLE
show local cycle routes (lcn) already in zoom level 10

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#237]
**Current situation**
Currently local cycle routes with network=lcn are only rendered from zoom level 11. at that same zoom level the cycle routes rendering changes to distinguish between separated tracks and shared roads. 
**Issue**
This distinction between separated and shared roads is a nice feature but does not provide a clear overview of available routes (including lcn)
**Proposal**
It would be clearer to show the lcn routes already at zoom level 10 to allow for a good view of the all cycle routes (icn+ncn+rcn+lcn).

**Comment by Florimondable** [comment]
Not sure to understand, cycle infrastructure are not rendered at z10, only from z11 as lcn https://www.cyclosm.org/#map=11/49.0273/2.1901/cyclosm

**Comment by patman37** [comment]
at zoom level 11 the rendering of all cycle routes (icn+ncn+rcn) is changed from opaque to the barely visible translucent (but including infrastructure). that means that the lcn are never shown in the highly visible opaque version. it would be nice to have at least one zoom level (z10?) where all cycle routes are rendered in the opaque version.

**Comment by Phyks** [comment]
Linking to https://github.com/cyclosm/cyclosm-cartocss-style/issues/276 since the exact opposite concern as been raised concerning The Netherlands. See as well the discussion in the PR https://github.com/cyclosm/cyclosm-cartocss-style/pull/286.

**Comment by Phyks** [comment]
Should be solved with the merge of #286.
