### ISSUE TITLE
Renders maxspeed in living street

### ISSUE THREAD

**Issue by WeftWiki** [cyclosm/cyclosm-cartocss-style#238]
In France, Living streets are limited to 20kph. Right now it is not depicted on Cyclosm unless the highway is tagged with maxspeed=20 which is not recommended and redundant.

Cyclosm should use the highway maxpseed default values according to local regulations. For example in France it's described in https://www.openstreetmap.org/relation/934933

**Comment by Florimondable** [comment]
I disagree about the statement that in France a living street is always a "zone de rencontre".
«The highway=living_street tag is used to tag living streets or other implementations of shared space.»
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street
Highway tag is about real life road, not about its boards.

**Comment by patman37** [comment]
but the opposite is true : In France a _zone de rencontre_ is always a _living_street_ : **_"La valeur living_street de la clé highway est utilisée pour représenter une voie située en zone de rencontre"_** (https://wiki.openstreetmap.org/wiki/FR:Tag:highway%3Dliving_street)

with the default maxspeed for living street in France as defined in the relation mentioned by  @WeftWiki

We could have _living_streets_ which are not _zone de rencontre_, which would then need their specific maxspeed tag.

**Comment by Florimondable** [comment]
> Cyclosm should use the highway maxpseed default values according to local regulations. For example in France it's described in https://www.openstreetmap.org/relation/934933
Can I say this relation violate the good practice «Don't map your local legislation, if not bound to objects in reality» :p
https://wiki.openstreetmap.org/wiki/Good_practice#Don.27t_map_your_local_legislation.2C_if_not_bound_to_objects_in_reality

> but the opposite is true : In France a _zone de rencontre_ is always a _living_street_ : **_"La valeur living_street de la clé highway est utilisée pour représenter une voie située en zone de rencontre"_** (https://wiki.openstreetmap.org/wiki/FR:Tag:highway%3Dliving_street)
I realy dislike that, we should split the concept of a living street (or a shared space) with the legislation means by the board. I do think highway is a tag representing the pysical reality of the street, not its boads.

The other main issue is that I don’t know how to render things dependings of there location. 😬

**Comment by Phyks** [comment]
> Cyclosm should use the highway maxpseed default values according to local regulations. For example in France it's described in https://www.openstreetmap.org/relation/934933

This is a way too edgy tagging for taking into account in CyclOSM. First, there are only 49 worldwide (https://taginfo.openstreetmap.org/tags/type=defaults#overview), not all of them being default speed limits. These relations are difficult to use, and I'm not aware of much tools (even more render) using them… :/

> In France, Living streets are limited to 20kph. Right now it is not depicted on Cyclosm unless the highway is tagged with maxspeed=20 which is not recommended and redundant.

Indeed, we could render them with a 20km/h color by default, or something like this.

**Comment by majkaz** [comment]
Another voice for rendering as implicit maxspeed 20 km/h for simplicity. 
According to the [english wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street) , 20 km/h is here a maximum for implizit values. Some countries have lower limit, but I don't see that much difference for bicycling there.
The big difference is between residential road (50 km/h in my case) and living street (20 km/h for most cases). If the cars have to go even slower doesn't matter much in comparison to bike speed. And there is no rendering for the lower limits at the moment anyway. 
Of course, there MAY come some country with a higher limit. I don't expect it in reality, the trend seems to be to set the local speed limits even lower then in other countries, not higher...

**Comment by axelos** [comment]
Bonjour,

Concrètement, aujourd’hui la documentation wiki FR indique qu’il ne faut pas indiquer le maxspeed=20 car est une information redondante.
De ce fait, cette documentation devant valoir de « bible », si le rendu cyclosm se base exclusivement sur la clef de vitesse du chemin, alors il y aura de nombreuses Zones de Rencontres non-indiqués sur le rendu.
Ce qui me semble être plutôt dommage car en général ces voiries rassurent les usagers cyclistes.

Axel.

**Comment by DerDings** [comment]
> Another voice for rendering as implicit maxspeed 20 km/h for simplicity. 
> According to the [english wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street) , 20 km/h is here a maximum for implizit values. Some countries have lower limit, but I don't see that much difference for bicycling there.
> The big difference is between residential road (50 km/h in my case) and living street (20 km/h for most cases). If the cars have to go even slower doesn't matter much in comparison to bike speed. And there is no rendering for the lower limits at the moment anyway. 
> Of course, there MAY come some country with a higher limit. I don't expect it in reality, the trend seems to be to set the local speed limits even lower then in other countries, not higher...

This is a good approach for the beginning, even the legend shows living streets rendered that way.

>And there is no rendering for the lower limits at the moment anyway. 

There is the very light green fill which is currently used for pedestrian roads where cycling is allowed. It indicates walking speed.
If (or when) different rendering by country is supported, this color should be used instead in (Australia), Austria, Bosnia and Herzegovina, (Croatia), Germany, Norway and Sweden.
In those countries only walking speed (up to 10 km/h) is allowed in living streets.

>Some countries have lower limit, but I don't see that much difference for bicycling there. 

This is quite important for cyclists because it means doubled (in case of 10 km/h like in Australia) or even tripled (in case of 4-7 km/h like in Germany) travel time for cyclists compared to a 20 km/h road.

In Germany for example, many cyclists prefer traffic-calmed shop areas ("Verkehrsberuhigte Geschäftsbereiche") where you may drive 20 km/h, but avoid living streets because of the reasons stated above.
One would expect a map that aims to be "for every cyclist" to show this difference prominently.
