### ISSUE TITLE
Some UTF-8 characters missing

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#241]
https://www.cyclosm.org/#map=7/33.765/131.517/cyclosm

![Screenshot_2019-11-08 CyclOSM](https://user-images.githubusercontent.com/3856586/68457791-64f19c00-0201-11ea-94e5-b9de62176856.png)

**Comment by Florimondable** [comment]
No issue in higher zooms https://www.cyclosm.org/#map=15/33.7832/130.5525/cyclosm

**Comment by Phyks** [comment]
We have it at all zooms, see https://www.cyclosm.org/#map=14/33.8814/130.6810/cyclosm

**Comment by patman37** [comment]
yes it seems in Japan the prefecture names are not rendered.
![osm prefectures](https://user-images.githubusercontent.com/8955390/68551087-81f8bb80-0409-11ea-9287-c6e9bc44065e.PNG)
![cyclosm prefectures](https://user-images.githubusercontent.com/8955390/68551090-88873300-0409-11ea-9b34-3b8b8bbc15a3.PNG)
https://www.cyclosm.org/#map=9/34.0162/135.1099/cyclosm
in this example the prefectures of Wakayama 和歌山県 , Nara 奈良県and Tokushima 徳島県 are not rendered in Cyclosm

**Comment by Phyks** [comment]
I think the issue was coming from italics/bold fonts which were not supporting all characters. Should be fixed with latest commit.

**Comment by patman37** [comment]
it is not fixed yet in production. was it supposed to be ?

**Comment by patman37** [comment]
I understand now ; it will be fixed in version 0.4 and I see version 0.3.1.

**Comment by Florimondable** [comment]
Yes, it will be fixed in production when the next release will be put into production ;)
