### ISSUE TITLE
Render man_made=water_tap as drinking water point

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#244]
see https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tap
and use drinking_water=yes/no as #152

**Comment by Phyks** [comment]
Done

**Comment by Florimondable** [comment]
this one is not rendered https://www.openstreetmap.org/node/7553285251

**Comment by Phyks** [comment]
It is now. Closing this one.
