### ISSUE TITLE
Render cycle routes tagged on ways

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#245]
There is an old way of tagging cycle routes by adding `lcn=yes` directly on the way.
It seems to be used a lot in Quebec

https://wiki.openstreetmap.org/wiki/Cycle_routes#Tagging_cycle_route_networks

**Comment by Phyks** [comment]
> It is preferred to tag the cycle routes using relations instead of tagging the ways. But please check that a relation doesn't already exist for your chosen route before creating one. Links to country-specific overview pages of cycle networks are below. 

Should we support `lcn=yes` etc then?

**Comment by Phyks** [comment]
From the Taginfo map (https://taginfo.openstreetmap.org/tags/lcn=yes#map), it seems this tagging is mainly used in US, UK and Germany.

For US, https://wiki.openstreetmap.org/wiki/United_States/Bicycle_Networks recommends to map it as relations.

From what I could see, it seems in Germany as well, current state of the art is mapping with relations (https://wiki.openstreetmap.org/wiki/DE:Bicycle/Deutsche_Radfernwege for instance).

For UK, although the wiki mentions using `lcn=` tags (https://wiki.openstreetmap.org/wiki/Cycle_routes#United_Kingdom), when going to the wiki pages for each dedicated cycle network, relations are recommended.

So, this tagging schemes seems to be deprecated in favor of relations and I would be in favor of not rendering it in CyclOSM. We could however render it if this was a maintained and recommended tagging scheme in some parts of the world (but did not find any reference for this at the moment).

**Comment by lumica89** [comment]
Hi, in Germany it is still an offical recommendation to use lcn=yes for cyclepaths that are shown on signs but are normally not assigned to a bike route which has a certain name. So far example a connection between two villages is not necessarily a real relation and has no number, no name and no other identifactor except the destination.

So as you could see here: https://wiki.openstreetmap.org/wiki/DE:Key:network for local networks, there is the recommendation to use lcn=yes. So it would be nice if this is also shown in the map.

Best
Martin

**Comment by Phyks** [comment]
Hi,

Thanks for the feedback on this and the German situation! I don't speak German and the Google translation was unclear. From the translation, I understood `network=lcn` on a relation or `lcn=yes` on the ways. Never the two of them (redundant) and the wording in the translation made me understand that the first one was preferred.

Does it mean something like this https://static.lexpress.fr/medias_10723/w_960,h_540,c_fill,g_north/v1451378291/un-panneau-de-signalisation-sur-la-portion-de-5-km-d-autoroute-pour-cyclistes-a-mulheim-dans-la-ruhr-dans-l-ouest-de-l-allemagne-le-24-decembre-2015_5490202.jpg (bicycle direction, no route label) would be tagged as `lcn=yes` on ways?

I'm wondering what the rendering should be. Should it be drawn as a `lcn` relation (overlay) or rather as "bicycle routes" (slow traffic, blueish fill).

**Comment by lumica89** [comment]
Hi @Phyks, 

to answer your question: Yes, this ia good example where edges would be tagged with lcn=yes or network=lcn (which are both possible and none of them is marked as deprecated in the wiki, but they should not be used together).
Additionally there is currently a draft that proposes not to tag edges directly with lcn=yes, but to use a network-relation instead (https://wiki.openstreetmap.org/wiki/User:JochenB/DE:Relation:network). I'll see when this becomes effective, but it seems for me much better than tagging each edge.

From my point of view the rendering should be drawn as lcn-routes-relations. The difference to a lcn-routes-relation in terms of rendering is then only the missing name and ref value.

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/pull/430.
