### ISSUE TITLE
Path color is wrong in the legend

### ISSUE THREAD

**Issue by hugobqd** [cyclosm/cyclosm-cartocss-style#247]
In the legend, the path line is paint with the color of the footway
![capt](https://user-images.githubusercontent.com/35178/69251018-03421200-0bb1-11ea-8ddf-7940897d1582.jpg)

**Comment by Florimondable** [comment]
This is a ticket for https://github.com/cyclosm/cyclosm-website ;)

But the issue is on the footway key color, it should be green not cyan

**Comment by hugobqd** [comment]
Correct!
