### ISSUE TITLE
Add ramp:luggage=yes/manual as bike friendly

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#248]
https://wiki.openstreetmap.org/wiki/Key:ramp

**Comment by Florimondable** [comment]
And if we can add `ramp:bicycle=automatic` as bike friendly too like here https://parisladefense.com/fr/actualite/faites-place-a-lescalator-velo?utm_source=social&utm_campaign=Escalator_Velo

(the implementation should say that every `ramp:bicycle!=no` should be bike friendly, values list are fine : https://taginfo.openstreetmap.org/keys/ramp%3Abicycle#values )

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/764cbdbba84baf132ceb99ac08c78e9289459329.
