### ISSUE TITLE
Is there a tile service for this style?

### ISSUE THREAD

**Issue by govvin** [cyclosm/cyclosm-cartocss-style#249]
It would be lovely to have a TMS of this style on OsmAnd. Is there a tile server service available?

**Comment by Florimondable** [comment]
Yes : https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png

I will convert this ticket to: communicate the tile server url in the readme :)

**Comment by govvin** [comment]
That's great! Thank you!
