### ISSUE TITLE
missing tooltips

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#250]
**Issue** 
there are missing tool tips for the buttons on the top left (only _zoom in_, _zoom out_ and _show me where I am_ are shown).
**Proposal**
All buttons should have a tool tip description.
![missing tooltips](https://user-images.githubusercontent.com/8955390/69439003-67e2a580-0d46-11ea-93a5-eb9c47262660.png)

**Comment by Florimondable** [comment]
This ticket should be open on the website repository https://github.com/cyclosm/cyclosm-website  ;)

**Comment by Phyks** [comment]
Done. Will be available online for next version.
