### ISSUE TITLE
reference tag of cycle route is half missing

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#251]
**issue**
the cycle route tag is only partly visible. In this example (see screen capture below) the tag should be _V30_ or _V32_ but only _V3_ is visible
**proposal** 
the complete tags should be visible
![cut ref tag of cycle route](https://user-images.githubusercontent.com/8955390/69439998-4aaed680-0d48-11ea-890e-9fb06d1f5abf.PNG)

**Comment by Florimondable** [comment]
Same issue as https://github.com/gravitystorm/openstreetmap-carto/issues/146 as far as I know, unsolvable.

At least it will be solved for road tags as we will remove them with #233 ':D

**Comment by Phyks** [comment]
This is due to the shield lying in between two tiles. There is indeed not much we can do to fight this :/
