### ISSUE TITLE
show osm data delay

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#254]
**Issue**:
currently the OSM data in cyclosm is not up to date. (as far as I can tell)

**Proposal**:
show the delay as in http://osmose.openstreetmap.fr/
![image](https://user-images.githubusercontent.com/8955390/69613608-1c741400-1032-11ea-8be0-5c3957854c44.png)

**Comment by Florimondable** [comment]
It is, check for the delay of the replication of the osm.org database into our : https://munin.openstreetmap.fr/osm11.openstreetmap.fr/osm165.openstreetmap.fr/osm_replication_lag_osm2pgsql.html

**Comment by patman37** [comment]
thank you for the link. Now I can see if the data is up-to-date. However there may be another problem:
last week i completed the existing cycle route "_Au Fil de l'Eau_" (V362) from  _Etaples_ to _Arras_.
in zoom level 10 only the old pieces (before my additions) are visible: https://www.cyclosm.org/#map=10/50.3612/2.4403/cyclosm
![image](https://user-images.githubusercontent.com/8955390/69653913-38000e80-1074-11ea-862f-b11035a3a6f9.png)
if the waymarked trails box is checked the whole route is visible: https://www.cyclosm.org/#map=10/50.3612/2.4403/cyclosm-waymarkedtrails
![image](https://user-images.githubusercontent.com/8955390/69654050-709fe800-1074-11ea-96db-ebc0bd7cc3d9.png)
only if I zoom down to level 14 the complete V362 becomes visible: https://www.cyclosm.org/#map=14/50.3732/2.0726/cyclosm
![image](https://user-images.githubusercontent.com/8955390/69654228-b65cb080-1074-11ea-9e81-c496fcc84adf.png)

Strange isn't it ?
I have the same issue with Firefox 70, Chrome 78 and IE11

**Comment by Phyks** [comment]
Link will be added in the infobox on the website on next version.

> Strange isn't it ?

Zooms below 12 are pre-generated on a weekly basis. And we had server issues last week, so it is possible these tiles are actually older than a week.

**Comment by patman37** [comment]
I see now. Wouldn't it be interesting to describe somewhere these timings so that everybody can understand the situation.

**Comment by Phyks** [comment]
Not optimal, but done in https://github.com/cyclosm/cyclosm-website/commit/632311c8c53c5c29d03add3e412ff21e3b3f9b37.

**Comment by patman37** [comment]
![image](https://user-images.githubusercontent.com/8955390/70037629-2a3c1300-15b7-11ea-9e61-7883ee721fde.png)
What I can observe does not fit with this description. the cycle route relation (v362) I extended two weeks ago still plays hide and seek at different zoom levels https://www.openstreetmap.org/relation/187009/history

- at zoom level 8 the cycle route appears correctly https://www.cyclosm.org/#map=8/50.078/3.301/cyclosm

![image](https://user-images.githubusercontent.com/8955390/70038403-720f6a00-15b8-11ea-997b-d9bb2c28eb65.png)

- at zoom levels 9+10 the old version (before 21 November) reappears https://www.cyclosm.org/#map=9/50.2085/2.6971/cyclosm

![image](https://user-images.githubusercontent.com/8955390/70038757-14c7e880-15b9-11ea-8461-127bc4f3bb66.png)
at 

- at zoom level 11 the new cycle route briefly reappears https://www.cyclosm.org/#map=11/50.2959/2.3092/cyclosm

![image](https://user-images.githubusercontent.com/8955390/70039001-70927180-15b9-11ea-9bc3-613b38b538c1.png)

- and disappears again at zoom level 12 and 13 https://www.cyclosm.org/#map=13/50.3663/2.1011/cyclosm

![image](https://user-images.githubusercontent.com/8955390/70039143-b7806700-15b9-11ea-9fd9-4b713d745164.png)
to 

- to reappear from zoom level 14 https://www.cyclosm.org/#map=14/50.3729/2.0715/cyclosm

![image](https://user-images.githubusercontent.com/8955390/70039270-ee567d00-15b9-11ea-8253-5de67ff59f21.png)

**Comment by Florimondable** [comment]
Yes we have an issue with zooms below 14, you can also see it for 13 since the road shield are still present whereas they have been removed from last update on sunday 1st dec.

It’s like we don’t render all tiles at zoom Z12 and below anymore 🤔 
https://munin.openstreetmap.fr/static/dynazoom.html?plugin_name=osm11.openstreetmap.fr%2Fosm166.openstreetmap.fr%2Frenderd_zoom&start_iso8601=2019-08-25T00%3A11%3A36%2B0200&stop_iso8601=2019-12-12T23%3A11%3A36%2B0100&start_epoch=1566684696&stop_epoch=1576188696&lower_limit=&upper_limit=&size_x=800&size_y=400&cgiurl_graph=%2Fmunin-cgi%2Fmunin-cgi-graph

**Comment by patman37** [comment]
interesting stats. 
So I guess I just have to wait until everything is back to normal.

**Comment by Florimondable** [comment]
Yes, but I think we still have an issue somewhere ;(

**Comment by patman37** [comment]
zoom levels 12-13 seem fixed now. zoom levels 9-10 are still not updated

**Comment by Florimondable** [comment]
and zoom 11, they working on it

**Comment by patman37** [comment]
zoom level 11 was already updated two days ago
