### ISSUE TITLE
No rendering for aerialway=*

### ISSUE THREAD

**Issue by pgavrilov** [cyclosm/cyclosm-cartocss-style#256]
No rendering for aerialway=cable_car and aerialway=chair_lift

https://www.openstreetmap.org/#map=15/47.7054/12.8747
https://www.cyclosm.org/#map=15/47.7052/12.8744/cyclosm
![aerialway OSM](https://user-images.githubusercontent.com/3817702/69670635-63e7b800-10a5-11ea-9d0e-e1e10597e36b.jpg)
![aerialway Cyclosm](https://user-images.githubusercontent.com/3817702/69670636-63e7b800-10a5-11ea-8c90-b78e1bfd72c7.jpg)

**Comment by Phyks** [comment]
`aerialway` are usually not bike-friendly (chair lift at least). Should we render all of them (considering they are easy to spot in the landscape and to orient with) or only the bike-friendly ones (probably just `cable_car` and with `bicycle` hint)?

**Comment by Florimondable** [comment]
Render all of them, use `aerialway:bicycle | yes/summer/no` to render in blue or not, I’d say.

https://wiki.openstreetmap.org/wiki/Key:aerialway

**Comment by quasart** [comment]
Just in case you didn't notice, wiki says about `aerialway:bicycle` :

> By default, cablecar, gondola, and mixed_lift imply yes, and chairlifts, t-bars imply no

**Comment by pgavrilov** [comment]
These objects provide good guidance, and they can help to understand map.

**Comment by Phyks** [comment]
Done. I did not consider the `aerialway:bicycle=summer` edge case so far (it is a synonym for `yes` currently). Rendering it better falls within the scope of #65.

![2019-12-01-183318](https://user-images.githubusercontent.com/3856586/69917714-49c52580-1469-11ea-93b0-7d79ee5e9af6.png)

https://www.cyclosm.org/#16/45.5133/2.8442

**Comment by Florimondable** [comment]
Not link to #65, `aerialway:bicycle` is just an access restriction tag.
I would not render `cable_car` in blue if access to bicycle is not set.

**Comment by Phyks** [comment]
`aerialway:bicycle=summer` is a temporal restriction, no? So I somehow link it to the question of how to render temporal restriction / intermittent features.

**Comment by pgavrilov** [comment]
> Done. I did not consider the `aerialway:bicycle=summer` edge case so far (it is a synonym for `yes` currently). Rendering it better falls within the scope of #65.

I think, aerialways must be shown at least at zoom 14, may be 13.
Note: usually it is some kilometers long object.

**Comment by Florimondable** [comment]
> `aerialway:bicycle=summer` is a temporal restriction, no? So I somehow link it to the question of how to render temporal restriction / intermittent features.

Yes, you're right

> I think, aerialways must be shown at least at zoom 14, may be 13.
> Note: usually it is some kilometers long object.
They are now available from z14, but I think we should render from 13 at least
https://www.cyclosm.org/#map=14/-16.5121/-68.1306/cyclosm

**Comment by Phyks** [comment]
> They are now available from z14, but I think we should render from 13 at least

It is already the case, it should be rendered from Z12, just as on osm.org. See https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L766-L786 and https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/aerialways.mss#L5.

**Comment by Florimondable** [comment]
There is misspell here 
https://github.com/cyclosm/cyclosm-cartocss-style/blob/215299638b0519e1780f7dc3b6550d24b9f42951/project.mml#L779
-> *aeriwaly*

**Comment by Florimondable** [comment]
And bicycle=yes is missing for chair_lift and others

**Comment by Phyks** [comment]
> There is misspell here

Indeed, fixed.

> And bicycle=yes is missing for chair_lift and others

`bicycle` tag seems ultra minoritary from taginfo. I think correct tagging is using `aerialway:bicycle`, isn't it?

**Comment by Florimondable** [comment]
> > And bicycle=yes is missing for chair_lift and others
> 
> `bicycle` tag seems ultra minoritary from taginfo. I think correct tagging is using `aerialway:bicycle`, isn't it?

It's what I meant of course.
(weird tagging scheme btw)
