### ISSUE TITLE
one way cycleway

### ISSUE THREAD

**Issue by quasart** [cyclosm/cyclosm-cartocss-style#257]
Hello everybody, and thank you for this new 0.3.2 release !
Unfortunately I think there is a regression : one-way cycleway have lost their arrows.

**Comment by Florimondable** [comment]
you’re right :(
https://www.cyclosm.org/#map=18/48.87187/2.36304/cyclosm

**Comment by Phyks** [comment]
I'm not sure these were ever rendered actually. It should be fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/91ba4987e1ed9889c4a9d4c8366c7fdbc189eab6 but this commit could definitely use a review @Florimondable.

**Comment by Florimondable** [comment]
Of course they were rendered, I'm sure I worked on them with the cycleway of Les Champs https://www.cyclosm.org/#map=18/48.87093/2.30441/cyclosm
