### ISSUE TITLE
Trunk as bikable by default

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#258]
Trunk should be rendered as bikable by default I think. Unless it has `motorroad=yes` or bicycle related limited access tag it should not be bikable.

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk
https://wiki.openstreetmap.org/wiki/Key:motorroad

Example Pont de Neuilly is bikable 
https://www.cyclosm.org/#map=17/48.88692/2.25543/cyclosm

An other example in France were the first part of the trunk is bikable (not a motorway) until the first out link.
https://www.google.com/maps/@48.1609515,-0.6888836,3a,39.2y,191.64h,90.66t/data=!3m6!1e1!3m4!1s9sDW8f8SM7PwXoicOWJPRA!2e0!7i16384!8i8192

**Comment by Phyks** [comment]
Should be done in latest commit. Render is 
![2019-12-02-193302](https://user-images.githubusercontent.com/3856586/69984992-aba19000-153a-11ea-8caf-371d4b6f1dbb.png)

Note that some parts of the bridge are explicitly tagged with bicycle=no.

**Comment by Florimondable** [comment]
When CyclOSM reveal the bad consistency of some tags :fearful:

**Comment by Mickanside** [comment]
Funny... I came here to suggest the opposite, finding very strange the mention "bicycle explicitly allowed" in the legend compared to the red rendering if bicycle=undefined...

For example, here in Alsace, there are tens of kilometers of expressways, therefore by default prohibited to bicycles: they appear in red on the map ...

Example here in Strasbourg: https://www.cyclosm.org/#map=15/48.5253/7.6726/cyclosm

![image](https://user-images.githubusercontent.com/22372042/143134338-ff9d934d-3d27-41ee-8faa-b0e97dc41457.png)

I think that if we leave it that way, we should at least remove the mention "explicitly allowed"!

**Comment by Florimondable** [comment]
Well, for motorway it’s "explicitly allowed", whereas for trunk is by default. Should be fixed in the legend.
