### ISSUE TITLE
Reduce visibility of access=private

### ISSUE THREAD

**Issue by jodastephen** [cyclosm/cyclosm-cartocss-style#259]
In my area, I've added quite a lot of service roads (`highway=service`) and rear access tracks (`highway=track`) with `access=private`. However, the current style ignores the access level and thus highlights these as highly visible (completely the opposite to your goals).

Here is an example of a `highway=service, access=private`: [link](https://www.cyclosm.org/#map=19/51.41166/-0.23450/cyclosm)

Here is an example of lots of `highway=track, access=private`: [link](https://www.cyclosm.org/#map=16/51.3940/-0.2170/cyclosm)

Can I request that routes with `access=private` are not highlighted in this way? Thanks

**Comment by Phyks** [comment]
Indeed, we could probably reduce their opacity, similary to what we do for amenities.

**Comment by Florimondable** [comment]
> Here is an example of lots of `highway=track, access=private`: [link](https://www.cyclosm.org/#map=16/51.3940/-0.2170/cyclosm)

For me this is bad tagging, track is for agriculture or forest purpose road, here it's a service road like alley or driveway, or path if very narrow.
https://wiki.openstreetmap.org/wiki/Tag:service%3Dalley
https://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway

> 
> Can I request that routes with `access=private` are not highlighted in this way? Thanks
Yes we can work on that, we already did road with forbidden access to bicycle in grey, may be the same here ?

**Comment by Florimondable** [comment]
Be aware that we already fade color for road in tunnels.

**Comment by Florimondable** [comment]
I'm again ok with the Idea: just render with the same color as bicycle=no roads.
Because the result for a cyclist is the same "you can't ride there".

The only problem I can see here is that we don't know if you can walk on the road or not, but already have the issue with bicycle=no color. May be we could have an other color (more white) for road open for walking but not for cycling ?

**Comment by jodastephen** [comment]
My opinion is that anything tagged with `access=private` is indicating no access for wlaking or cycling - it implies `foot=private` and `bicycle=private` in the absence of specific `foot` or `bicycle` tags. As such, I think anything with `access=private` should be "greyed out".

FWIW, the same is true of `access=no` - it implies `foot=no` and `bicycle=no`.

**Comment by Florimondable** [comment]
Yes with d6e66a79aa9e80c5705e7cd29f44c5b8846b90d8
bicycle(or access if no bicycle tag)=no/private will be rendered in grey :)
