### ISSUE TITLE
there should be no blue arrows for oneway:bicycle=no when cycleway:right|left=opposite_track 

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#260]
![image](https://user-images.githubusercontent.com/8955390/70377973-3f98a080-191b-11ea-961d-d66c940e195c.png)
**Issue** : 
there are blue arrows because of _**oneway:bicycle=no**_
but it is only the track on the side which is allowed in opposite direction for bicycles **_cycleway:left=opposite_track_** and there are already arrows there, so there is no need for additional arrows on the street.

**proposal** :
no blue arrows for **_oneway:bicycle=no_** when **_cycleway:right|left=opposite_track_** 

https://www.cyclosm.org/#map=20/48.83170/2.34053/cyclosm

**Comment by Florimondable** [comment]
I disagree, I know there is double information here but the arrow on the cycle track is too small to be easy to be seen.

**Comment by patman37** [comment]
We should be consistent 
in the example below of the _rue de la Tombe-Issoire_ (https://www.cyclosm.org/#map=19/48.82634/2.33225/cyclosm) we have 
- in the lower part blue arrows **and** white arrows in _cycleway:left=opposite_track_ and 
- in the upper part neither blue arrow **nor** white arrow for _cycleway=sidewalk_ + _oneway=yes_

In my view separate cycleways should be rendered following the same principles as cycle tracks : 

- white arrow in cycle track and cycleway 
- no blue arrow in road.

![image](https://user-images.githubusercontent.com/8955390/71733171-3979df00-2e49-11ea-9fac-77341154be71.png)

**Comment by Phyks** [comment]
Render should have been fixed in the meantime. I would be in favor of explicitly marking the direction of every bicycle infrastructure (shark teeths on the lanes, arrows on the tracks) as is currently done online.

I agree with @Florimondable view that double info is not so much trouble here, but would happily discuss this further if you think the current situation is not satisfactory.

Best
