### ISSUE TITLE
Bike lane discontinuity on zoom <=18 but ok on 19

### ISSUE THREAD

**Issue by bagage** [cyclosm/cyclosm-cartocss-style#261]
On zoom 18 and lower, [this bike lane](https://brouter.damsy.net/latest/#map=18/43.65512/3.88026/cyclosm,Chiffrage%20de%20la%20qualit%C3%A9%20de%20route) ([osm way](https://www.openstreetmap.org/way/243921465#map=17/43.65517/3.87633)) seems discontinued:

![image](https://user-images.githubusercontent.com/1451988/70397079-4ef91600-1a0f-11ea-90d0-5957a2d90e53.png)

But zooming to 19, it is displayed as expected:

![image](https://user-images.githubusercontent.com/1451988/70397086-5a4c4180-1a0f-11ea-8176-63b4669b72b1.png)

Maybe the bike lane should be drawn above standard roads?

**Comment by Florimondable** [comment]
No render issue here, there is a bridge https://www.openstreetmap.org/way/185764249
so it’s render over the cycleway.
Cycleways are rendered over every other highways as long as they are at the same "layer"

**Comment by bagage** [comment]
You're right @Florimondable, actually I missed the fact that the bridge is only declared for the road. I fixed the data by declaring it on the bike lane too, I believe it should fix this issue.

However, it seems the bridge is not rendered on cyclosm: is that on purpose?

Anyway, thanks for the fast answer, feel free to close if you consider it solved! :tada:

**Comment by Phyks** [comment]
> However, it seems the bridge is not rendered on cyclosm: is that on purpose?

Sorry for coming back so late on this, this is likely to be solved with #288 !
