### ISSUE TITLE
Train station is too much visible at z12

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#262]
Paris looks like to have varicella https://www.cyclosm.org/#map=12/48.8593/2.3253/cyclosm
Subway stations can be removed
Train stations could be smaller.

**Comment by Phyks** [comment]
Problem is any solution to this should also make the train stations highly visible in the country side: https://www.cyclosm.org/#map=13/48.7559/1.4651/cyclosm.

Concerning subway stations, I guess we should exclude `station=subway` (https://wiki.openstreetmap.org/wiki/Key:station?uselang=fr) unless there is an explicit bicycle access? Would that work globally (Strasbourg where bicycles are allowed in tram stations or San Francisco for instance)?

Last idea, which could work for POIs as well, could be to count objects and only return them at given zoom level if there are less than a given number. Typically, Z12 in Paris, a lot of stations > do not display (until Z13 or 14 where the density is much lower). Z12 in the countryside, only a few stations, display them.

**Comment by Florimondable** [comment]
My PR do the job well
@Florimondable
Render subway station from z14 instead of Z12, to avoid too much stat…
51f8578
@Florimondable
Render halt train station.
2e5f9fc
