### ISSUE TITLE
Draw name of landuses

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#264]
Name of landuse are not labeled for farmland see https://www.cyclosm.org/#map=18/49.78260/3.95963/cyclosm
May be other landuse name should be also rendered.

**Comment by Florimondable** [comment]
Or may be we should not render them :thinking:

**Comment by Phyks** [comment]
I would render them, it somehow acts as an orientation point in the countryside (similar to hamlets etc). Done in commit mentionned above.

**Comment by Florimondable** [comment]
Not sure it’s a good way to tag things

**Comment by Phyks** [comment]
I was wondering how to tag such a place, which is a very useful indication when touring the countryside.

It could be a "lieu dit" with a dedicated place tag, but this requires some administrative formalism which does not always exist. This tagging looks good to me, similar to tagging the name of a school. Osm.org renders it, so I think we are safe on the tagging side.

**Comment by Florimondable** [comment]
https://wiki.openstreetmap.org/wiki/Tag%3Aplace%3Dfarm ;)
anyhow it’s fine for me
