### ISSUE TITLE
Maxspeed on shared path

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#266]
This shared path (https://www.openstreetmap.org/way/396624176#map=16/47.7167/-3.4362&layers=N) is actually a shared sidewalk, limited to 10 km/h for bicycles. It is currently rendered in a very bright blue https://www.cyclosm.org/#map=16/47.7148/-3.4349/cyclosm which makes it look like perfect for any kind of cycling.

We should have a specific render to make it clear it is not meant for any kind of cycling.

There are a lot of such shared sidewalks around Lorient / Plœmeur.

**Comment by Florimondable** [comment]
Render low bicycle maxspeed like #65 with #311, or the cycleway with an other color ?

**Comment by Phyks** [comment]
I'm not sure here. Having a "Max 10km/h" text along it, similar to #311 would be fine in my opinion. Other alternative would be to consider this cycleway is a "walking speed cycleway" and render it as a pedestrian color or something similar. No strong opinion here.
