### ISSUE TITLE
Wind turbine are no rendered

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#267]
see https://www.cyclosm.org/#map=16/49.6858/3.9501/cyclosm

generator:method=wind_turbine
generator:source=wind
power=generator

**Comment by Florimondable** [comment]
Windmill either
https://www.cyclosm.org/#map=19/48.88737/2.33676/cyclosm

**Comment by Phyks** [comment]
It should be rendered https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/amenities.mss#L612-L628.

This is definitely a bug, but I cannot find what is wrong at the moment... :/

**Comment by Phyks** [comment]
Fixed.

Windmill was not rendered because it was a `tourism=attraction` as well (not rendered though) which had superior precedence.

Wind turbine was not rendered due to a typo. Tag `generator:source` is in a dedicated column, not in the `tags` field.
