### ISSUE TITLE
Render MTB routes

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#27]
MTB routes should be rendered. Typical example is https://www.openstreetmap.org/relation/3201448#map=15/48.4726/2.7459&layers=C.

**Comment by Phyks** [comment]
That's a good question actually. I would tend to think that it could be inresting for mountain bike multi-days trips. OpenCycleMap does display them.

A relation such as GTMC (Grande Traversée du Massif Central, https://www.openstreetmap.org/relation/3858890) is quite structuring and I would expect it to appear on a cycle render, isn't it?

**Comment by mjray** [comment]
MTB route https://www.openstreetmap.org/relation/3422897 and similar sub-national UK ones do not appear to be rendering. Is that a mapping problem (I think the unrendered ones do not have a type ncn/rcn/lcn or whatever but that is not required by https://wiki.openstreetmap.org/wiki/Tag:route=mtb and arguably would be incorrect for some standalone single trails such as this example) or a rendering problem and, if so, is it a new bug or should I reopen this one?

**Comment by Phyks** [comment]
This is https://github.com/cyclosm/cyclosm-cartocss-style/issues/379 which will be solved in next version! :)

**Comment by mjray** [comment]
Cool. Thanks. The best type of bugs are one already fixed - but that seems fixed in May and still not showing on map?

**Comment by Phyks** [comment]
Indeed, we are having quite a bit of latency in rolling out next version here. Summer time plus covid events are not really helping here, and we lately had more time trying out the map in the wild than coding =)

We definitely have to roll out a new version in production. Probably by the end of the month, to give us time to review and merge the pending merge requests.
