### ISSUE TITLE
Using Cyclosm tiles for our Android app

### ISSUE THREAD

**Issue by lukedavis8767** [cyclosm/cyclosm-cartocss-style#274]
Hi, we're currently a group of university students working on a final year project: An open-source, free cycling app, providing cycle routes and routing functionality. Cyclosm seems perfect for displaying a raster layer providing information on the cycling routes, which we want to have as a toggleable layer for users, but if we were to release this app with cyclosm incorporated, we worry that it would be troublesome if the app got a lot of downloads and many server requests were made. Is the tile server capable of handling many tile requests? If not, would it be possible for us to host tiles on our own server, providing correct referencing and licencing pointing to cycleosm? I hope the question makes sense, we are all completely new to creating a map based app. Many thanks.

**Comment by Phyks** [comment]
Hi,

Thanks for your interest for CyclOSM! You can definitely use the hosted tile server for an app (see https://github.com/cyclosm/cyclosm-cartocss-style#demonstration) provided that you comply with the OSM tile usage policy (https://operations.osmfoundation.org/policies/tiles/).

This boils down to basically:
* send a valid HTTP user-agent identifying your app
* send a valid HTTP referrer if possible
* if applicable, ensure caching policy is enabled to cache tiles

In case your app gets a lot of traction, it might be required to host your own tile server in the future.

Best,
