### ISSUE TITLE
Highway labels are rendered instead of (international) cycling route labels

### ISSUE THREAD

**Issue by hiddewie** [cyclosm/cyclosm-cartocss-style#275]
See https://www.cyclosm.org/#map=10/45.6184/14.0364/cyclosm and compare with https://www.cyclosm.org/#map=11/45.6359/13.9705/cyclosm

Zoom 10

![image](https://user-images.githubusercontent.com/1073881/71783076-e7b88c80-2fe1-11ea-98f9-605904a31f32.png)

Zoom 11

![image](https://user-images.githubusercontent.com/1073881/71783070-db343400-2fe1-11ea-9f49-a09aa942bea2.png)

The labels A1 and A3 of some highways are visible, while on zoom 11 the EV9 internatinoal cycling route is visible.

**Comment by Phyks** [comment]
Hi,

Thanks for the report! We should have removed highway shields in latest version (see https://github.com/cyclosm/cyclosm-cartocss-style/pull/233). We, however, have some issues with the server for pre-generation of low zoom levels at the moment (timing out, pre-generation is done for zooms < 12) so it's very much likely these tiles were not rendered again.

Flagging as a bug on our infra.

**Comment by hiddewie** [comment]
That would explain the half rendered shield just north east of the A3 shield in the zoom 10 image.

**Comment by Phyks** [comment]
This should have been fixed with our latest work on our server infrastructure! Let me know if you still encounter this issue.

Best,
