### ISSUE TITLE
Render two stage turn

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#284]
see https://lists.openstreetmap.org/pipermail/tagging/2020-January/050002.html

**Comment by Phyks** [comment]
Was there a wiki tagging proposal? If I understood correctly, he went with the lanes tagging solution https://lists.openstreetmap.org/pipermail/tagging/2020-January/050126.html, isn't it?

**Comment by Florimondable** [comment]
No proposal (I'm not a fan of proposal anyhow), and yes they went with lanes.

**Comment by Phyks** [comment]
Can/should we have a special render of their lane solution?

**Comment by jarek** [comment]
Hey all, mailing list poster here. (And big fan of cyclosm - thank you!)

I personally most like the relation tagging (https://www.openstreetmap.org/relation/10597153 as an example). I keep on meaning to use the other tagging methods as a sample of how they'd look in practice and put together a wiki page asking for comments, but haven't gotten around to it yet. I can post the wiki link here when I do, if you'd like.

**Comment by Phyks** [comment]
Thanks for the kind words on CyclOSM!

Such a relation is similar to https://github.com/cyclosm/cyclosm-cartocss-style/issues/4 so the render is likely to be similar.

We would definitely need a wiki proposal and at least some consensus in the OSM community to add a render for it, so please feel free to post it whenever this is happening!

Best
