### ISSUE TITLE
Footway with oneway render as counter flow

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#289]
issue from http://forum.velotaf.com/topic/19182-opencyclemap-cartographie-cycliste-participative/page__view__findpost__p__1016200

«- il semble voir des contresens cyclables là où il n'y en a pas. Par exemple sur un objet comme celui-là, où il ne devrait pas être prévu de saumoner :

bicycle yes
highway footway
oneway yes
segregated no»

https://www.cyclosm.org/#map=18/48.90245/2.24002/cyclosm

**Comment by Phyks** [comment]
This is coming from https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L2234-L2235

I guess it should read:

```
CASE
            WHEN tags->'oneway:bicycle' IS NOT NULL THEN tags->'oneway:bicycle'
            WHEN oneway IS NOT NULL THEN oneway
            ELSE 'no'
          END AS oneway_bicycle
```

(no check on `highway=cycleway`). I introduced it in https://github.com/cyclosm/cyclosm-cartocss-style/commit/91ba4987e1ed9889c4a9d4c8366c7fdbc189eab6, I should not have been as strict.

Do you see any possible side effects?

BTW, is the tagging even correct? `oneway` should also apply to pedestrians, in theory, isn't it? I would expect such a way to be tagged with `oneway:bicycle=yes` instead. And what is a directional (oneway) bicycle shared (segregated=no) space with pedestrians?

**Comment by Florimondable** [comment]
oneway apply only on vehicles not pedestrians (see wiki page)
