### ISSUE TITLE
Footway with motor_vehicle=no is rendered in bright green

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#293]
issue here : https://www.cyclosm.org/#map=16/48.8572/2.6161/cyclosm
https://www.openstreetmap.org/way/254355620
Like they’re car less road.

Bad tagging or bad rendering ?

**Comment by Phyks** [comment]
Bad tagging, `highway=footway` implies `motor_vehicle=no` which should not be added then.

I'd be in favor of keeping the render as is as it has the side effect of hilighting this bad tagging.
