### ISSUE TITLE
Motorway ref is no more rendered

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#294]
See https://www.cyclosm.org/#map=15/48.8396/2.1056/cyclosm

**Comment by Florimondable** [comment]
log when I render a tile :
`Mapnik LOG> 2020-02-13 19:12:17: Marker does not exist: symbols/shields/motorway-trunk_3x1.svg`

**Comment by Phyks** [comment]
Are you using an updated `mapnik.xml` file? This should no longer exist in the code.

**Comment by Florimondable** [comment]
Yes, sorry, it was an old mapnik.xml.
