### ISSUE TITLE
Tile expiry

### ISSUE THREAD

**Issue by hiddewie** [cyclosm/cyclosm-cartocss-style#295]
Connected to #158 

When I view https://www.cyclosm.org/#map=9/38.4030/27.3422/cyclosm I see the EV8 in Turkey. However, when I zoom out 1 level (https://www.cyclosm.org/#map=8/38.335/27.713/cyclosm) I see nothing. 

Zoom 9
![image](https://user-images.githubusercontent.com/1073881/73682162-13ea2a80-46c0-11ea-81a4-c0730868b2d5.png)

Zoom 8
![image](https://user-images.githubusercontent.com/1073881/73682170-1b113880-46c0-11ea-8337-0d313419dd2a.png)

Previously this was also the case on Cyprus (https://www.cyclosm.org/#map=8/35.297/33.470/cyclosm) but this has been updated on all zoom levels.

I think this has to do with map tiles not being updated/flushed from cache.

**Comment by Florimondable** [comment]
Hi, yes we had an issue with the generation of the low zooms.
It didn't start last week, should be fine now.

**Comment by hiddewie** [comment]
Yes it seems solved now, thanks!
