### ISSUE TITLE
Can't see anymore regional route at z8-10

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#297]
Probably a regression after #286

exemple :
https://www.cyclosm.org/#map=10/48.1083/-1.2051/cyclosm
https://cycling.waymarkedtrails.org/#route?id=1019787

**Comment by hiddewie** [comment]
Yes, I see the problem on the live map. I will try to reproduce it locally, although I can't understand why it would cause this problem.

**Comment by hiddewie** [comment]
@Florimondable I made a mistake concerning 'null' tags. This should be solved with the PR. I tried it on some data in France.

**Comment by Florimondable** [comment]
Thank you for your quick answer :)
