### ISSUE TITLE
pedestrian/cycleway tunnel is not rendered as tunnel

### ISSUE THREAD

**Issue by pgavrilov** [cyclosm/cyclosm-cartocss-style#298]
Underground tunnel part of pedestrian way rendered as same above the ground.
https://www.openstreetmap.org/#map=19/47.73124/12.87164
https://www.cyclosm.org/#map=19/47.73134/12.87189/cyclosm

All pedestrian ways here tagged as:
highway=path
surface=asphalt

Tunnel part of way also have tags:
layer=-1
tunnel=yes

**Comment by Phyks** [comment]
Thanks for the report! We'll have a look at this.

**Comment by Phyks** [comment]
Should be addressed by commit mentionned above.

![Screenshot_2020-02-23 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/75116497-5670a880-5669-11ea-8b30-e5dd016c1863.png)
