### ISSUE TITLE
Render bicycle designated road

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#304]
Sometime a road can be designated for cyclist. For instance it is common to have a parking aisle service road next to the main road used as the continuation of a cycleway.
Examples:
https://www.cyclosm.org/#map=18/48.88028/2.30975/cyclosm
https://www.google.fr/maps/@48.8808675,2.3119782,3a,50.5y,312.1h,77.26t/data=!3m6!1e1!3m4!1szA1ADRbRp4v5afXEcO_c8A!2e0!7i16384!8i8192

https://www.cyclosm.org/#map=19/48.89528/2.38341/cyclosm
https://www.google.fr/maps/@48.8949884,2.3827467,3a,75y,60.45h,71.87t/data=!3m6!1e1!3m4!1sMc0LrddKm0Or9orpITPeIg!2e0!7i16384!8i8192

Copenhagen:
https://www.cyclosm.org/#map=17/55.67313/12.57490/cyclosm
https://www.google.fr/maps/@55.6726324,12.5744945,3a,75y,109.74h,71.12t/data=!3m6!1e1!3m4!1s79X7j0cvzJBT-aZATnIsgQ!2e0!7i13312!8i6656

They are not proper cycle street, and they are sometimes tag inside a cycle route to show the itinerary.

When bicycle=designated on a road (may be limited to low highway class (unclassified/residential/service ?) we should render them.
Ideas : render like cyclestreet, or as third quality (wide dash) like shared lane.

**Comment by Florimondable** [comment]
Be aware that in Portland USA there is a lot of bicycle designated roads and with shared lane
http://overpass-turbo.eu/s/QzH

**Comment by Phyks** [comment]
Typical example I know would be https://www.cyclosm.org/#map=19/48.59114/7.72251/cyclosm in Strasbourg (not tagged as `bicycle=designated` but could definitely be IMO, this is part of the official cycle network).

This is a cycle way merging into a parking lane, I would never draw this part as bicycle friendly road, with cars maneuvering to park.

Third quality might be ok.
