### ISSUE TITLE
icons in legend and map should have the same size and color

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#310]
![image](https://user-images.githubusercontent.com/8955390/74762214-acb2a580-527d-11ea-9f9d-667582a692af.png)
the icons bicycle shop and bicycle rentals have different size and color on the map and in the legend it should be same.
https://www.cyclosm.org/#map=18/48.83134/2.34747/cyclosm

**Comment by Florimondable** [comment]
Please add it to the website project https://github.com/cyclosm/cyclosm-website

**Comment by patman37** [comment]
done.
