### ISSUE TITLE
Use average traffic data to know if a road is cyclable or not

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#320]
there is a key here https://wiki.openstreetmap.org/wiki/Key:traffic:hourly
but not much data
So I added some data for Paris from the open data of the city https://opendata.paris.fr/explore/dataset/comptages-routiers-permanents-2019/table/?refine.t_1h=2019&q=q%3E0

Next step is to try a rendering

**Comment by Florimondable** [comment]
So I did a render test on my branch https://github.com/Florimondable/cyclosm-cartocss-style/commits/traffic

Here is the results:
Streets with data `traffic:hourly`:
![traffic_hourly_red_cyclosm](https://user-images.githubusercontent.com/47089717/76167648-82f7ea80-6168-11ea-9d3f-3397ab40b05d.png)

Before:
![traffic_hourly_cyclosm_base](https://user-images.githubusercontent.com/47089717/76167652-92773380-6168-11ea-8ac1-d592aa42954c.png)

After:
![traffic_hourly_colorclassique_cyclosm](https://user-images.githubusercontent.com/47089717/76167661-9d31c880-6168-11ea-98fc-1ce63251bf7d.png)

I like the result, we can see properly the main roads network of Paris East, though I'm not sure about the color thresholds, may be too low.
An other subject is how to treat oneway road and thresholds, I don't think a division by two is good.

**Comment by Florimondable** [comment]
And I need to add data on smaller streets also, to check.

**Comment by Phyks** [comment]
Nice! \o/

**Comment by Florimondable** [comment]
So I went out to get traffic data for small streets of the 10e in Paris, I count traffic for most of the street which I know they have probably too much traffic for quiet cycling.
I also analyse the traffic data of the open data, and found out my threshold was too low (but that is another subject)
Here is my result for 10e :

before :
![10e_traffic_avant_cyclosm](https://user-images.githubusercontent.com/47089717/76687018-75d37380-6620-11ea-8bc8-5ac683671042.png)

after :
![10e_traffic_apres_150_cyclosm](https://user-images.githubusercontent.com/47089717/76687022-7b30be00-6620-11ea-844f-96274a6ae198.png)

Many street are no more blue anymore (30km/h area) but white or yellow, the 30kmh area lie is over :)
