### ISSUE TITLE
Render bicycle parking area

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#322]
Today bicycle parking areas are render as a point, osm.org render them also their surface, we should do the same.

example https://www.openstreetmap.org/#map=19/48.84394/2.37195

**Comment by Phyks** [comment]
We have it rendered as a surface (grey square) with a node in the center. Maybe we should have some background to make it clearer?

**Comment by Florimondable** [comment]
No, the example is badly choosen since there is barrie=fence,
You can check other parking areas http://overpass-turbo.eu/s/RBd

**Comment by Phyks** [comment]
Oh right, my bad.
