### ISSUE TITLE
Rework blue/cyan/green colors ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#324]
It seems some people (how much ?) have difficulties to distinguish the different blue/cyan/green colors we use.

We don't perceive color the same way.
If I can trust this paper http://www.scilogs.fr/questions-de-couleurs/pourquoi-la-perception-des-couleurs-nest-elle-pas-parfaitement-identique-pour-chacun-de-nous/

Old people perceive less blue colors, cones for blue colors vary widely between people.
May be we should change the default color from blue to green, orange ?

We should remember the main design ideas :
- close color for fast reading (bluish == cyclable)
- different colors for detailed rendering
So it's a matter of balance.

(link to #171 though less extreme)

**Comment by Florimondable** [comment]
Switching for green or orange doesn't look a good idea for color blind people (Deuteranomaly)
https://en.wikipedia.org/wiki/Color_blindness
«    Deuteranomaly (most common—6% of males, 0.4% of females):[42] These individuals have a mutated form of the medium-wavelength (green) pigment. The medium-wavelength pigment is shifted towards the red end of the spectrum resulting in a reduction in sensitivity to the green area of the spectrum. Unlike in protanomaly, the intensity of colors is unchanged. The deuteranomalous person is considered "green weak". For example, in the evening, dark green cars appear to be black to deuteranomalous people. As with protanomates, deuteranomates are poor at discriminating small differences in hues in the red, orange, yellow, green region of the spectrum. They make errors in the naming of hues in this region because the hues appear somewhat shifted towards green. However, unlike protanomates, deuteranomalous people do not have the loss of "brightness" problem.

    People with deuteranomaly may be better at distinguishing shades of khaki than people with normal vision and may be at an advantage when looking for, say, predators, food, or camouflaged objects hidden among foliage.»

**Comment by Florimondable** [comment]
The good thing with blue/cyan is that rod sells has its max perception there.

https://commons.wikimedia.org/wiki/File:Spectre_absorption_des_cones.svg?uselang=fr
![673px-Spectre_absorption_des_cones svg](https://user-images.githubusercontent.com/47089717/76684340-86c5ba00-660b-11ea-9c13-422cec1f04d5.png)

**Comment by Phyks** [comment]
> May be we should change the default color from blue to green, orange ?

Changing to green might be ok (however, it would be yet another bike = green which is not very good in my opinion). Orange is quite strong and goes with the idea of danger, imo, I would not change towards orange.

I know red is used for cycling in some countries (Germany for instance), but this is too much country-specific.

**Comment by Florimondable** [comment]
Idea : render footpath and other foot-only area in brown, which give more color space for the bicycle friendly shading, path could be green (warning: in forest visibility).
Brown is not a very welcome color for cyclists : brown -> earth, ground, dirt  (except MTB :).
That would help also to have a better color balance of the map, and to have less "blue only map"

**Comment by Florimondable** [comment]
here a quick test :

footway : light brown
cycleway : darker blue
shared designated path : a little lighter blue
speed colors : wider shading to green

it works I think

![Screenshot_20200416_194823](https://user-images.githubusercontent.com/47089717/79489307-5d89b680-801b-11ea-91ac-1f9a3049ce9f.png)
![Screenshot_20200416_194732](https://user-images.githubusercontent.com/47089717/79489308-5e224d00-801b-11ea-92ab-6fbc6d6bcb0f.png)
![Screenshot_20200416_194627](https://user-images.githubusercontent.com/47089717/79489309-5ebae380-801b-11ea-98a2-2d5f553b6581.png)

**Comment by Florimondable** [comment]
Still working on it, I'm close to something good I think
![Screenshot_20200417_235139](https://user-images.githubusercontent.com/47089717/79616981-acf8e100-8106-11ea-8cc2-6b3ff07cc867.png)
