### ISSUE TITLE
Render drinking_water:refill 

### ISSUE THREAD

**Issue by pqhf5kd** [cyclosm/cyclosm-cartocss-style#325]
drinking_water:refill is a tag that was recently approved to indicate if the establishment participates in a water refill network. The tag is currently being used on less than 100 features but hopefully it will gain traction in the coming months. I feel like the tag is very useful for cyclists in counties, such as the UK, where there are not many water fountains but there are many establishments participating in bottle refill schemes.

Generally features tagged with drinking_water:refill=yes are going to be cafes, bars, restaurants and shops. 

I'm unsure of a suitable way to render the tag, maybe cafes, bars, restaurants and shops could be blue instead of the standard grey if they provide refills?

**Comment by Phyks** [comment]
Indeed, this could be a very useful feature!

> I'm unsure of a suitable way to render the tag, maybe cafes, bars, restaurants and shops could be blue instead of the standard grey if they provide refills?

I'm unsure about the best render for this. I'm not a huge fan of having cafes/bars/restaurants/shops rendered as blue (they would probably be more difficult to spot on the map), but don't have much other ideas at the moment :/

**Comment by Florimondable** [comment]
We can add a small glass of water, flask or a bidon icon over the amenity regular icon ?

**Comment by Phyks** [comment]
Closing as per comment https://github.com/cyclosm/cyclosm-cartocss-style/pull/539#issuecomment-849780498.
