### ISSUE TITLE
Some protected areas has no label rendered

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#329]
see https://www.cyclosm.org/#map=11/48.4037/2.5801/cyclosm

it was present in my PR #309 https://github.com/cyclosm/cyclosm-cartocss-style/pull/309#issuecomment-587181646
A regression in the merge ?

**Comment by Phyks** [comment]
Indeed, faulty commit was https://github.com/cyclosm/cyclosm-cartocss-style/commit/0231c4ca63df387bd3127fec42c95ed777ae7050. Should have been reverted.
