### ISSUE TITLE
Display MTB trail ratings

### ISSUE THREAD

**Issue by Martin868** [cyclosm/cyclosm-cartocss-style#336]
Would be nice to add some MTB trail information. I think the mtb:scale and mtb:scale:imba tags could be processed to add the appropriate coloring to the mtb trails
mtb:scale:imba=0 White (novice)
mtb:scale:imba=1 Green (easy)
mtb:scale:imba=2 Blue (moderate)
mtb:scale:imba=3 Black (difficult)
mtb:scale:imba=4 Red (expert)

Also could be considered is to add the some cooling to the route relations with the tag route=mtb as is done on the openstreetmap.org cycling map - they use orange.

**Comment by Phyks** [comment]
Concerning MTB tags, we have an issue to track this need: #208.

> Also could be considered is to add the some cooling to the route relations with the tag route=mtb as is done on the openstreetmap.org cycling map - they use orange.

Not sure about this point, we should already be doing it. See the "GTMC" mtb route here for instance: https://www.cyclosm.org/#map=15/45.9296/3.1124/cyclosm.

**Comment by Florimondable** [comment]
so on my branch i did a try 
https://github.com/Florimondable/cyclosm-cartocss-style/commit/0c9e23fb00bfe1768183463ce18b33e662244e24 

three possibilities :
- same dashes with colors (mtb:scale=1 blue, mtb:scale=2 red, mtb:scale>=3 black)
- different dashes (mtb:scale=1 "|", mtb:scale=2 "||", mtb:scale>=3 "|||" ) no color
- different dashes with colors

![Screenshot_20200404_124649](https://user-images.githubusercontent.com/47089717/78429357-d892ba80-7674-11ea-8ab2-7eb2e11619dd.png)
![Screenshot_20200404_124150](https://user-images.githubusercontent.com/47089717/78429476-e1838c00-7674-11ea-834f-7c029b3502a3.png)
![Screenshot_20200404_124529](https://user-images.githubusercontent.com/47089717/78429498-e34d4f80-7674-11ea-83d5-3bb49a86c8ce.png)

I like different dashes or different dashes with colors.

**Comment by Phyks** [comment]
Different dashes with colors is nice indeed! Maybe, I would space them a bit more to make surface dashes more readable though?

**Comment by Martin868** [comment]
What people know and understand is colours so that is essential. Also those colours are not to be defined, there is a well know and broadly used standard for this. It is published by IMBA and used by all Montain Bike parcs and networks. It is similar to the rating system used for downhill skiing and other sports.

mb:scale:imba scale
IMBA 0 - Novice - White
IMBA 1 -  Easy - Green 
IMBA 2 - Moderate - Blue
IMBA 3 - Difficult - Black
IMBA 4 - Expert - Red

The mtb:scale is not as well standardize and is just an OSM thing and have one extra level 5 for very-extreme and a level 6 which is not-ridable. So with that scale I would suggest using the same colours as IMBA, and make 5 Red also. The 6 rating is simply not an mtb trail and could have no coloring like any hiking trail. It is very rarely used, sometimes for abandoned trails.

I personally find the proposed rendering hard to read since the colours are not standing out. But this may just be my eyes.

IMBA rating system

**Comment by Florimondable** [comment]
Thanks for your remarks Martin,
The problem is that we have to key in OSM mtb:scale (from http://www.singletrail-skala.de/) and mtb:scale:imba from IMBA. That's why I choose the german scale colors (which is today much more used in OSM)
It doesn't seems there is only one international scale, so we have two options merge them and having one representation or rendering both.
I think we can try rendering both.

Colors are easier to read at lower zoom level.

**Comment by Martin868** [comment]
The German and Imba are not that different. What would not work with the imba colors ? 

>

**Comment by Florimondable** [comment]
Well, why choosing more IMBA than STS ?
I don't know which one is more used in the world (though mtb:scale is more used in OSM).

Here an example with IMBA colors :
![Screenshot_20200404_160501](https://user-images.githubusercontent.com/47089717/78452842-13551c80-768e-11ea-9be0-3d2447b978dd.png)

**Comment by Martin868** [comment]
I didn’t have statistics on this. But IMBA is an international standard. International Mountain Biking Association. It is active in the USA, Canada, Australia. I don’t know what’s their footprint in Europe.

**Comment by Florimondable** [comment]
See pull request https://github.com/cyclosm/cyclosm-cartocss-style/pull/340#issue-399682256
I decided to render mtb:scale if present otherwise mtb:scale:imba. They have each there own rendering so we cannot misunderstand which scale is rendered.
