### ISSUE TITLE
Render guidepost and map for cyclists

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#341]
« To describe the type(s) of the shown route(s) use the tags hiking=yes, bicycle=yes, mtb=yes, horse=yes or ski=yes. They don't describe the legal access to the guidepost.  »

https://wiki.openstreetmap.org/wiki/Tag:information%3Dmap
https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost

I guess we can simply render them in blue.

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/7b2a402f2eda0da47c0e398eb56b8348ed3c5b53.

Rendered in purple, as other bicycle amenities. Could be blue though, I don't have a strong opinion here.

![2020-04-26-230104](https://user-images.githubusercontent.com/3856586/80319664-f685b200-8811-11ea-81f2-126a664ff88e.png)

http://localhost:6789/cyclosm-cartocss-style/#19/52.73909/-3.92289

**Comment by Florimondable** [comment]
I would render them in blue, purple is not very understand as bicycle

**Comment by Phyks** [comment]
done
