### ISSUE TITLE
Render healthcare & doctors

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#348]
« <florimond> visiblement CyclOSM rend healthcare=hospital/clinic ; je pourrais ajouter pharmacy, et peut-être aussi doctor (qu'on ne rend pas non plus en amenity) »

**Comment by Phyks** [comment]
Pharmacy should already be catched by `amenity=pharmacy`, no? See https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dpharmacy

> Add healthcare=pharmacy and name=*. All are also tagged with amenity=pharmacy in addition. 

We do not render doctors though.

**Comment by Florimondable** [comment]
> Pharmacy should already be catched by `amenity=pharmacy`, no? See https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dpharmacy

Yes, almost

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/440a20f908f93e88e60f0e0e1837f6be2ca5248c. Doctors are rendered from Z18.
