### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by mhajder** [cyclosm/cyclosm-cartocss-style#349]
It would be a good idea to create a full production Dockerfile to make the script easier to run.

**Comment by Phyks** [comment]
Hi,

Thanks for the issue. What would the Dockerfile set up? Would it serve as a duplicate of https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md? Import of OSM data for instance might be an issue : which region to import? plus it can be very long.

If you have some Docker knowledge and are willing to write a PR for this, we'll gladly welcome it! :)

Best

**Comment by mhajder** [comment]
> Hi,
> 
> Thanks for the issue. What would the Dockerfile set up? Would it serve as a duplicate of https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md? Import of OSM data for instance might be an issue : which region to import? plus it can be very long.
> 
> If you have some Docker knowledge and are willing to write a PR for this, we'll gladly welcome it! :)
> 
> Best
I meant something like this:
https://github.com/Overv/openstreetmap-tile-server

You can rewrite that script. Unfortunately, I won't help because I have problems with purely installing this OSM style.

**Comment by mhajder** [comment]
I did it. There is also a ready Docker image to download.
https://github.com/mhajder/openstreetmap-tile-server-cyclosm

**Comment by Phyks** [comment]
Thanks, I added a link in https://github.com/cyclosm/cyclosm-cartocss-style#related-projects!
