### ISSUE TITLE
cyclosm don't work in openlayers?

### ISSUE THREAD

**Issue by nanoflojo** [cyclosm/cyclosm-cartocss-style#353]
The tilelayer https://dev.{s}.tile.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png don't work in openlayers?

**Comment by Phyks** [comment]
OpenLayers does not support the `{s}` I think. What about replacing it with `{a-c}` ?

**Comment by nanoflojo** [comment]
Yes!!!, it's nice.
[http://maparutasmtb.blogspot.com/2019/10/sendas-del-rio-san-juan-y-caslilla.html](url)

**Comment by nanoflojo** [comment]
Yes!!!, it's nice.
[<a target="_blank" href="http://maparutasmtb.blogspot.com/2019/10/sendas-del-rio-san-juan-y-caslilla.html"></a>](url)

**Comment by nanoflojo** [comment]
Yes!! it's nice.
`<a target="_blank" href="http://maparutasmtb.blogspot.com/2019/10/sendas-del-rio-san-juan-y-caslilla.html"></a>`
