### ISSUE TITLE
Idea : use blue shared cycle path for bus/cycle lane

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#356]

**Comment by DerDings** [comment]
Also for `cycleway:*=shared_lane` and `cycleway:*:lane=advisory`? Would both make sense to me, too.

**Comment by DerDings** [comment]
And of course `cycleway:*:segregated=no`, which is also currently not rendered.

**Comment by Florimondable** [comment]
@DerDings Yes of course its the same rendering at the end.

So I try it :

![Screenshot_20210128_205611](https://user-images.githubusercontent.com/47089717/106191634-6e22ac00-61ab-11eb-8168-c43d03dbd851.png)
![Screenshot_20210128_205401](https://user-images.githubusercontent.com/47089717/106191636-6ebb4280-61ab-11eb-93d9-63cac4bc22ac.png)
![Screenshot_20210128_205338](https://user-images.githubusercontent.com/47089717/106191640-6f53d900-61ab-11eb-9d91-13967d3d5bb6.png)

I think the effect is nice, that makes the map emphasizing more on the cycle track, but cycle lanes/bus lanes are still visible.
