### ISSUE TITLE
Render bike station and low small/low priority POI names from z18 instead of z17

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#359]
This information is not important 99,9% of the time so in order to make the map clearer we can move it one level higher.

**Comment by Florimondable** [comment]
We can do also that for other POIs like restaurant, hotel, shops, ... which are small on terrain and not high in priority.
Hospital may keeps its name at z17 though.

**Comment by Phyks** [comment]
Bike stations at Z16/Z17 is useful in my opinion. See https://www.cyclosm.org/#map=16/48.8154/2.3193/cyclosm for instance, there are not so many of them and you see easily how well the city is covered. Z17 would probably be the max distance I'd be willing to walk to find a bike station.

**Comment by Florimondable** [comment]
The point is about the name label, not the icon.
