### ISSUE TITLE
Regressions last color merge

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#363]
1. After reading the code MTB routes should be no more rendered in orange at lower zooms.

2. Lucas Verney(s’ouvre dans un nouvel onglet)  18 h 52
je viens de voir sur https://user-images.githubusercontent.com/47089717/80147216-77933e00-85b3-11ea-8b3b-470dda268eab.png, on n'a pas cassé les area pedestrian (le fond gris) ?

**Comment by Florimondable** [comment]
In the following picture I see two blue dots on Rivoli (left part), happen  only at z15 at some places.
Due to bicycle=designated arrows ?

![15-48 85889-2 34765-optimroads2](https://user-images.githubusercontent.com/47089717/82099050-97c3a200-9706-11ea-89fc-6fb3b1fc241b.png)

**Comment by Florimondable** [comment]
>     1. After reading the code MTB routes should be no more rendered in orange at lower zooms.
Should be fixed.

>     2. Lucas Verney(s’ouvre dans un nouvel onglet)  18 h 52
>        je viens de voir sur https://user-images.githubusercontent.com/47089717/80147216-77933e00-85b3-11ea-8b3b-470dda268eab.png, on n'a pas cassé les area pedestrian (le fond gris) ?
Yes, I don't get what's the problem, there are all multipolygon, the code didn't change

**Comment by Phyks** [comment]
Probably an invalid geometry at some point. Seems this is fixed https://www.cyclosm.org/#map=18/48.87362/2.29575/cyclosm.

**Comment by Florimondable** [comment]
No, it's not fixed in the current master, the problem was from the branch not the current prod release.

**Comment by Phyks** [comment]
I double checked with the current master after the merges. This is indeed fixed. I added https://github.com/cyclosm/cyclosm-cartocss-style/commit/6b7f55b9d674bd8ec05366c49dca9b9ceb79deef to filter out underground buildings.

This can be seen across the square, due to building=transportation on the underground platforms: https://www.cyclosm.org/#map=19/48.87442/2.29530/cyclosm.

**Comment by Phyks** [comment]
I had a typo, fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/29b60ac6c1ac9ffc13cffda5d90825aabb46c12c.

**Comment by Florimondable** [comment]
is this one fixed ? https://github.com/cyclosm/cyclosm-cartocss-style/issues/363#issuecomment-629510842

**Comment by Phyks** [comment]
Missed it. This one is not fixed yet:

![Screenshot_2020-05-21 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/82575240-7b9d8600-9b88-11ea-856a-edce480edf04.png)

**Comment by Phyks** [comment]
Fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/433884edf811ceff9ef0bfb9db0214ab4bcdc207.

**Comment by Florimondable** [comment]
Merci
