### ISSUE TITLE
Some Cycleway name are not rendered

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#369]
example with https://www.openstreetmap.org/way/413363060#map=17/48.85018/2.36708
https://www.cyclosm.org/#map=20/48.84975/2.36691/cyclosm

though it is there https://www.cyclosm.org/#map=19/48.82964/2.43991/cyclosm

**Comment by Phyks** [comment]
Name is rendered but hidden by other features. Tweaking the distances in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/labels.mss#L424-L447 the name appears.

This cycleway is too close to the neighboroughing road. Not sure we really want to fix the render here.

**Comment by Florimondable** [comment]
ok, it's fine though
