### ISSUE TITLE
Show natural park

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#37]
We should show regional / departemental / natural parks as it is done on osm.org: https://www.openstreetmap.org/#map=8/48.243/5.482.

**Comment by Florimondable** [comment]
Should be close, it has been done.

**Comment by Phyks** [comment]
Yes and no, we lack the names and they are not that much visible.

**Comment by Florimondable** [comment]
Within forest they are not very visible, in land it's ok. It's no the most important thing to show in a bicycle map ;)

**Comment by Phyks** [comment]
Depends, it can have some implications on local rules (especially for gravel or camping) for instance.

**Comment by quasart** [comment]
Hello,
I agree it would be useful for people who want to cycle in nature. To my mind it's more important than small cities names to navigate at low zoom.

**Comment by Florimondable** [comment]
The render of natural park darken the map look here https://www.cyclosm.org/#map=12/49.7986/4.2943/cyclosm
That's not very nice :/

**Comment by Florimondable** [comment]
Hi @rem-maps I agree, I'm don't like much the protective area border area.
I created a ticket from your comment #396

**Comment by Phyks** [comment]
@rem-maps thanks a lot for the very detailed report with map captures and details! :)
