### ISSUE TITLE
Footway area are not drawn

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#370]
example here https://www.cyclosm.org/#map=20/48.87813/2.28049/cyclosm

should be rendered like pedestrian (or may be less green more brown ? since footway is less cyclable than pedestrian ?)

**Comment by Phyks** [comment]
This issue makes me realize we have an issue with our current layers. The landuse layer should be split to only reflect landuses. https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L158-L160 should be in a separate layer.

In particular, this causes issue with `tunnels` rendered on top of pedestrian (and eventually footways) areas.

Also see https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway, there is `area:highway:footway` which might be useful to render?

**Comment by Florimondable** [comment]
> In particular, this causes issue with `tunnels` rendered on top of pedestrian (and eventually footways) areas.

Well there's a debate whether tunnels should be hidded by higher level.
