### ISSUE TITLE
Bicycle conditional on subway/route relation

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#371]
Example : In Paris metro line 1 bicycle conditional text is rendered
https://www.cyclosm.org/#map=20/48.87338/2.29690/cyclosm
https://www.cyclosm.org/#map=20/48.87827/2.28111/cyclosm
This is not bad tagging, bicycle is only allowed onboard at some time.

Which is nice in a way but unexpected.
Shall we remove it or improved it ?

**Comment by Phyks** [comment]
I would add `WHERE highway IS NOT NULL` here https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L2484.

It could be useful to have this info, but so far we are not rendering subways (and I think we do not want to render subway rails). Additionnally, such info should be rendered on the stops, not on the rails, which is quite difficult to achieve given the OSM db schema.

**Comment by Florimondable** [comment]
ok
