### ISSUE TITLE
Lost butt endings on roads

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#373]
https://www.cyclosm.org/#map=19/48.85797/2.28217/cyclosm

We now have round endings:

![Screenshot_2020-05-20 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/82499037-3d08bc80-9af1-11ea-90b7-6c08436aa643.png)

**Comment by Florimondable** [comment]
We ever had butt ending see https://www.cyclosm.org/#map=19/48.84738/2.26801/cyclosm
In your example we don't see it because surface dash is hiding it I think : https://www.cyclosm.org/#map=18/48.85785/2.28281/cyclosm

**Comment by Phyks** [comment]
Oops indeed. My bad
