### ISSUE TITLE
Render power supply

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#376]
Render public power supply socket, like normal socket to charge your phone you can find in train station, or outside on the wall of a public building.
see discussion here https://lists.openstreetmap.org/pipermail/talk-fr/2020-May/099257.html
sql request may be more difficult than drinking_water as it is used also for many not free sockets.

**Comment by Florimondable** [comment]
See also https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddevice_charging_station

**Comment by Phyks** [comment]
Charging station done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/eb00c130148285219750c3de5ab4a462a8adfd1c#diff-8d68a3e97bc637b3cd2cb0e6d9e1c8c1eafbc33bf27ca1879784132c5b49e8ad. I'm not sure the render of individual power supply sockets would not clutter the map :/
