### ISSUE TITLE
Mountain Bike Circuit

### ISSUE THREAD

**Issue by pioueo** [cyclosm/cyclosm-cartocss-style#379]
Hello

What modifications must be made in OSM to integrate the marked mountain bike routes into cyclosm?
ex in opencyclemap: https://www.openstreetmap.org/#map=15/48.4664/-4.6070&layers=CN
but in cyclosm no color: https://www.cyclosm.org/#map=15/48.4684/-4.6008/cyclosm

Thanks

**Comment by Phyks** [comment]
Indeed, only 20% of the `route=mtb` routes seem to have a `network` tag. We should probably not expect the network tag to be there.

We could consider that no network tag is the same hierarchy level as lcn.

https://taginfo.openstreetmap.org/tags/route=mtb#combinations

**Comment by pioueo** [comment]
It works with network=lcn.
In Belgium a lot of MTB routes are tagged network=lcn but in France very few.
For me, the idea of Phyks is good.
Félicitations pour le projet, c'est de l'excellent travail.

**Comment by Phyks** [comment]
Done https://github.com/cyclosm/cyclosm-cartocss-style/commit/62e545e9c081c1dec127c843e97979d57372301f

Thanks for the feedback!
