### ISSUE TITLE
Cycle route node long text bad rendering

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#381]
See https://www.cyclosm.org/#map=16/48.4666/-4.5631/cyclosm
the name of the node Milizac is render in white and is barely readable.

**Comment by Phyks** [comment]
Indeed, we were expected numbered junction nodes when we designed this.

However, computing statistics on our world database, there are 2163 `lcn_ref` nodes and 1577 of them apparently have a non-numeric value :/
