### ISSUE TITLE
0.3.6 seems to have broken tile rendering

### ISSUE THREAD

**Issue by Rleahy22** [cyclosm/cyclosm-cartocss-style#383]
Even on the demo site you can see the tile image requests all fail.

https://www.cyclosm.org/#map=12/52.3727/4.8937/cyclosm

<img width="1276" alt="Screen Shot 2020-05-27 at 11 23 37 PM" src="https://user-images.githubusercontent.com/3144003/83095353-23c3bb00-a071-11ea-8b11-68e38cc0b3fe.png">

I have the same problem in an app I made that uses cyclosm

**Comment by Phyks** [comment]
Hi,

We got an IPV4 connectivity issue at our hoster. Pure coincidence, this has nothing to do with the new version.

Many tools provided by the French OSMF chapter are affected :/

Best,
