### ISSUE TITLE
Add private to "No motor vehicle access" color ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#386]
could be renamed "No public motor vehicle access"

**Comment by brainwad** [comment]
Also, maybe agricultural and forestry? Those are really common here in Switzerland and are basically untrafficked.

**Comment by Phyks** [comment]
I think this is already the case: https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L478.

Feel free to reopen if I'm wrong or there is a bug.
