### ISSUE TITLE
Cycle routes are too transparent at medium/high zoom levels

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#39]
![capture d ecran 2019-02-01 a 15 47 37](https://user-images.githubusercontent.com/3856586/52129775-b6e51000-2638-11e9-849f-f2f81cae2cdf.png)

See https://tiles.phyks.me/#14/48.8653/2.3603

It is very difficult to know where the cycling routes are, they tend to be too transparent.

**Comment by Florimondable** [comment]
Not large enough may be, we barely see the cycle track in the north of canal st martin though we should.
We need both infrstructure and routes to be seen.

**Comment by Phyks** [comment]
Indeed. But wouldn't a cycle route always kind of imply that there is a cycleway? (probably not sadly :/)

Yes, we could probably increase the width of the routes a lot then.

Note also that the question North of Canal Saint-Martin is also how to handle superposition of cycle routes (#13). There is an international (green), national (red) and probably local (blue) on this way, each having some transparency. When overlapping, this results in this dark brown color, no longer transparent. Not sure how we should handle it. Maybe we should just show the highest one (international in the previous case for instance)?

**Comment by Florimondable** [comment]
Cycleroute doesn't not (unfortunately) imply the quality of the road, is there cycle track ?, the quality of the surface can be bad, lot of cycle routes have gravel.
I see that OCM doesn't draw international road, and fade a lot the cycle route but they are large, and mixed well. That one way to do it.
Other way maybe is to draw only the highest ranked route, is it possible ?

**Comment by Phyks** [comment]
> I see that OCM doesn't draw international road, and fade a lot the cycle route but they are large, and mixed well. That one way to do it.

:+1:

> Other way maybe is to draw only the highest ranked route, is it possible ?

That could be possible with some SQL dark magic. Not sure if it would be clear for someone following the regional route that when it meets the international one, only the international one is rendered.

**Comment by Florimondable** [comment]
International routes is made of national, regional and local routes.
Routes should be labelled with all possible levels (at high zoom at least).

**Comment by Phyks** [comment]
Mostly fixed in #49.
