### ISSUE TITLE
Color of motorways: Difference between legend and map

### ISSUE THREAD

**Issue by mapper-of-openstreets** [cyclosm/cyclosm-cartocss-style#390]
In the legend, the color of highways is indicated by a reddish color (#F9E1E1, RGB(249;225;225)). In the map, however, motorways are shown with a grey colour (#D4D4D4, RGB(212;212;212)) and are difficult to see on the map.

**Comment by Phyks** [comment]
Indeed, this is now fixed!

> are difficult to see on the map

This is expected. Since motorways are not bikeable at all, we wanted to dim them as much as possible to ensure they do not attract too much the eye.

**Comment by Florimondable** [comment]
To be more precise :
By default trunk are cyclable (red) unless they have bicycle=no or motorroad=yes
By default motorway are NOT cyclable (grey) unless they have bicycle=yes

**Comment by mapper-of-openstreets** [comment]
Many thanks for the information and the quick feedback. Great work, great project!
