### ISSUE TITLE
busway=oppisate_lane of highway=cycleway is not rendered

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#391]
Issue:
on the rue de Rivoli we have a new pop-up cycle lane with
- busway:left=opposite_lane
- highway=cycleway

However, the busway is not rendered:
![image](https://user-images.githubusercontent.com/8955390/83904094-8eef4a80-a75f-11ea-8e8c-4d5d8cb7666d.png)
https://www.cyclosm.org/#map=19/48.86132/2.34052/cyclosm

2 possible solutions:
1. **fix-it in cyclosm**: the busway is rendered as a service road or
2. **fix-it in osm**: we do not allow to have busway*=opposite_lane with highway=cycleway and replace it with :
> - highway=service_road
> - cycleway:left=opposite_lane

**Comment by Florimondable** [comment]
the current way to tag is
highway=service
oneway=yes
cycleway:left=opposite_lane
oneway:bicycle=-1

**Comment by patman37** [comment]
Good! I close this issue.
