### ISSUE TITLE
operator does not exist: integer ~ unknown (CASE WHEN layer~E'^\\d+$')

### ISSUE THREAD

**Issue by nobohan** [cyclosm/cyclosm-cartocss-style#398]
Hello, 

I'm trying to install a tile server with the cyclosm style on a Debian 10 with postgre12.2. 

I've got the following error when renderd is loading the layer "tunnel" :

`Postgis Plugin: ERROR:  operator does not exist: integer ~ unknown
LINE 122: ...cle IN ('yes', 'designated')) THEN CASE WHEN layer~E'^\\d+$'...`

So this is at L552 of `project.mml`

BTW, I have the same error when trying:
`SELECT layer~E'^\\d+$' FROM planet_osm_line`

I'm not sure of what is it but I suspect that my version of postgresql does not handle the pattern matching around 'layer'. If yes, do you know how to make the queries compatible with postgresql 12?

**Comment by nobohan** [comment]
I just realised that the `layer` column has a "integer" datatype, while it should be some "text". A recent change in osm2pgsql?

**Comment by nobohan** [comment]
OK my bad sorry. I was using the openstreetmap-carto.style file for importing the OSM data with `osm2pgsql`, which cast the layer field as integer.

**Comment by Florimondable** [comment]
Ok, at least it's a good thing to know they use this optimization to avoid regular expression as we do. :)
