### ISSUE TITLE
More visible drinking water icon ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#399]
«J'ai une question concernant l'affichage des points d'eau et toilettes.
J'ai remarqué qu'ils apparaissent au niveau de zoom 16, comme dans la carte cycle "historique". Mais  des qu'on passe au zoom 17, quasiment toutes les autres icônes apparaissent et ils sont noyés en zone dense, par exemple un centre-ville. La simple différenciation de couleur bleu / gris ne suffit pas pour les distinguer facilement au milieu des autres informations.
Serait-il possible de trouver une autre couleur ou même une autre icône plus visible ?  La solution de la carte historique est un peu moche avec son icône carrée opaque, il faudrait trouver un intermédiaire.»

**Comment by Phyks** [comment]
Who did post this first? We lack an example…

**Comment by majkaz** [comment]
It was someone else, but I think the similar case is [here](https://www.cyclosm.org/#map=18/49.00765/14.77874/cyclosm).

**Comment by Phyks** [comment]
Indeed, thanks for the link! Maybe improving a bit the weight and darkening it would work?

**Comment by Florimondable** [comment]
Current :
![Screenshot_20201113_152332](https://user-images.githubusercontent.com/47089717/99084622-7bc28f80-25c7-11eb-8b40-2745a80fc789.png)

OSM-carto icon modified :
![Screenshot_20201113_152311](https://user-images.githubusercontent.com/47089717/99084623-7c5b2600-25c7-11eb-9b24-e0095ce47c98.png)

OSM-carto glass only :
![Screenshot_20201113_152151](https://user-images.githubusercontent.com/47089717/99084625-7cf3bc80-25c7-11eb-990a-39f9e913970d.png)

New color ?
![Screenshot_20201113_153950](https://user-images.githubusercontent.com/47089717/99084649-84b36100-25c7-11eb-9ebd-041bb638c3bb.png)

**Comment by Florimondable** [comment]
issue here https://www.cyclosm.org/#map=17/48.83853/2.46100/cyclosm

**Comment by Phyks** [comment]
osm-carto icon would be a great improvement. I don't like so much having only a glass, it does not seem to convey the same meaning (more like café I think).

:+1: for the dark blue render as well!

**Comment by Florimondable** [comment]
dark blue doesn't work well over a cycleway, may be just dark grey ?

![image](https://user-images.githubusercontent.com/47089717/99149526-e8549180-268e-11eb-8e87-c1d86bc5caab.png)

The best contrast is amenity bicycle 
![image](https://user-images.githubusercontent.com/47089717/99149608-6ca71480-268f-11eb-9969-13f7be0fc855.png)

**Comment by Phyks** [comment]
We probably have too many colors on the map, especially for POIs. The blue for drinking water / toilets was initially driven by a blue = water analogy. But we also have blue = bicycle in CyclOSM, which adds confusion. In the end, a drinking water spot is not way more "bicycle" than a pharmacy (which is desaturated and purely grey).

Actually, I'm wondering whether we should not desaturate much more POIs, and simply have dark grey for most of them, except those very specific to bicycle (bicycle shop / bicycle rental). We have also a potential confusion between bicycle rental and bicycle shop (almost the same icon, color is different).
