### ISSUE TITLE
The legend is missing some road types

### ISSUE THREAD

**Issue by kuba-orlik** [cyclosm/cyclosm-cartocss-style#402]
I was trying to understand the surface in [this place of the map](https://www.cyclosm.org/#map=18/52.39765/16.89887/cyclosm) and couldn't figure out what kind of roads were present there, as the color and shape didn't match any of the road line examples in the legend. Here's an example of that:

![image](https://user-images.githubusercontent.com/2697916/86454349-a09c2180-bd0e-11ea-971a-cde1ad6d4cda.png)

What do the dark blue dashed lines symbolize?

**Comment by Florimondable** [comment]
Hi, it's a mix (we cannot put every combination into the keys).
Color+width : track
Dashes : unknown surface quality

**Comment by kuba-orlik** [comment]
Ah, ok. Should've figured that out myself. Thanks for the explanation!
