### ISSUE TITLE
Render `motorcar=no motorcycle=no` like `motor_vehicle=no`

### ISSUE THREAD

**Issue by brainwad** [cyclosm/cyclosm-cartocss-style#406]
`motor_vehicle=no` is rendered as a bright green. But here in Switzerland, there is a distinction between that (tagged when [this sign](https://wiki.openstreetmap.org/w/images/5/5d/Verbot_f%C3%BCr_Motorwagen%2C_Motorr%C3%A4der_und_Motorfahrr%C3%A4der.png) is present), and `motorcar=no motorcycle=no` (tagged when [this sign](https://wiki.openstreetmap.org/w/images/8/86/Verbot_f%C3%BCr_Motorwagen_und_Motorr%C3%A4der.png) is present), which on Cyclosm is coloured white, the same as a street open to cars and motorcycles.

For bicycles, the only differences between the two signs are that roads with the second sign are also shared with 45km/h electric and motorised bicycles (in OSM tags, `mofa=yes`), while the first sign requires them to turn off their motor. But the blue signs for cycleways (`bicycle=designated`) also imply access for 45km/h vehicles. So I think it makes sense to use the same (green) colouring for both variants.

**Comment by Florimondable** [comment]
Agreed, we should also check `motor_vehicle`

**Comment by brainwad** [comment]
I think you already do check that?

**Comment by Florimondable** [comment]
Sorry, `motorcar` I meant.
