### ISSUE TITLE
Assume sidewalks are paved

### ISSUE THREAD

**Issue by brainwad** [cyclosm/cyclosm-cartocss-style#407]
The map renders footways with explicit `surface=paved/asphalt/etc` as solid lines, and dashed otherwise. But most mappers are lazy and don't add `surface` on sidewalks in the city, because it's obvious they will be paved. How about defaulting to solid lines for `footway=sidewalk` unless there is `surface=unpaved/dirt/etc`?

**Comment by quasart** [comment]
I’m not that sure sidewalk implicit surface is asphalt in countryside. 

What do you feel annoying in current default surface rendering ?

**Comment by brainwad** [comment]
I'm talking specifically of sidewalks, not footways in general. Sidewalks are only the ones that are directly alongside a street, separated only by curb or small green area. If there is a larger separation then they should be tagged as independent footways. I think most sidewalks are in cities by sheer weight of volume of streets. And even for country roads, I think sidewalks (as opposed to non-sidewalk footways) are usually going to be paved because they usually only exist alongside paved roads (unpaved roads don't have curbs to separate the roadway from the sidewalk). So along unpaved roads, either walking is done either on the road or its shoulder, or on a separate footway. And along paved roads, it must be unusual for the road to be paved, to have a curb, to have a defined, formal sidewalk, but not to have paved it.

It's annoying because it confuses the meaning of dashed lines (meant to mean unpaved) when I look at the map and the majority of dashed lines are actually paved IRL. See example around my home: https://imgur.com/a/KTfJ9Hq. All of the sidewalks are actually paved, but only ~half of them are tagged with any `surface=`, so half of them appear dashed. The dashed footways in the cemetery and park are mostly unpaved, but they wouldn't be affected by my proposal since they are not sidewalks.

BTW: the key seems reversed for long dashes and the short dashes on paths/footways. It says long dashes = unknown, medium dashes = bad surface and short dashes = very bad, but actually unknown is drawn with medium dashes and bad surfaces are drawn with long dashes.

**Comment by Phyks** [comment]
Hi,

> And even for country roads, I think sidewalks (as opposed to non-sidewalk footways) are usually going to be paved because they usually only exist alongside paved roads (unpaved roads don't have curbs to separate the roadway from the sidewalk).

Please, beware that CyclOSM is meant for global coverage. We cannot expect sidewalks (even in the city) to be paved by default, just because this is mostly the case in Europe.

> And along paved roads, it must be unusual for the road to be paved, to have a curb, to have a defined, formal sidewalk, but not to have paved it.

Separate sidewalks (tagged with `footway=sidewalk`) are tagged in a way that makes it next to impossible to find the nearby "real" way, to check whether it is paved or not. Same applies for "sidewalk in the city", it is very difficult to render different things depending on countryside / city with OSM data and Mapnik (or requires heavy pre-processing which we are trying to avoid).
