### ISSUE TITLE
Render sidewalk= similar to cycleway=track

### ISSUE THREAD

**Issue by brainwad** [cyclosm/cyclosm-cartocss-style#409]
In addition to `cycleway=`, which are used for tagging cycle facilities without creating separate ways, there is a similar tag `sidewalk=`. In particular it is the recommended way to tag a sidewalk attached to a road where bicycles are allowed but not designated [according to the German wiki](https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren). Unlike `cycleway=`, where the value specifies the type and side is specified as a suffix to the key (e.g. `cycleway:right=track`), `sidewalk=` specifies the side (e.g. `sidewalk=left`).

This could be rendered using borders that match the rendering of `highway=footway` today: a green line if `sidewalk:(<side>:)bicycle=yes`, otherwise brown. These can also be oneway, either for vehicles in general (using `sidewalk:(<side>:)oneway=` or for bicycles specifically using `sidewalk:(<side>:)oneway:bicycle=`, so ideally they would get direction arrows if anything is specified.

There are also cases where one side of a road has both a marked cycle lane (on the road) and a sidewalk where cycling is also permitted (they can also be in opposite directions). Ideally in this case both borders would be rendered, with the bike lane on the inside and the sidewalk on the outside.

**Comment by Phyks** [comment]
Would you have some typical OSM examples (best tagging for what is on ground examples) of this? This would be helpful to investigate rendering. Thanks!

**Comment by brainwad** [comment]
The tagging per [wiki](https://wiki.openstreetmap.org/wiki/Key:sidewalk) is `sidewalk:[left|right|both]:bicycle=*`. Most usages are `yes` (e.g. https://www.openstreetmap.org/way/5030161, https://www.openstreetmap.org/way/540071931, https://www.openstreetmap.org/way/540071931, https://www.openstreetmap.org/way/46748836)
; `designated` should be uncommon but is sometimes used instead of `cycleway=track`, when the "track" is shared with pedestrians (this pattern occurs a lot in Germany, so maybe the German tagging guidelines lead people to this? e.g. https://www.openstreetmap.org/way/76062084, https://www.openstreetmap.org/way/865354107, https://www.openstreetmap.org/way/38177009). The only other common value is`dismount`, which is the reasonable default and so can just be ignored, IMO.

I would suggest rendering exactly like a `cycleway=track` if if the sidewalk is tagged as `designated`, and otherwise similar to a track, but with path colour and width instead.

I actually experimented with implementing this before, and I found that, at least around me, there is a huge problem with duplicate sidewalks. Some users love to draw in new sidewalks with separate ways (i.e. `highway=footway footway=sidewalk`) but don't check for existing `sidewalk` tags on the neighbouring roads. So when I rendered the sidewalks, they were duplicated everywhere. As you know it's almost impossible to do the deduplication within the limitations of CartoCSS... I would therefore suggest not rendering `sidewalk` tags without `:bicycle` tagging.

**Comment by brainwad** [comment]
I hacked up what I suggested above, here are some screenshots:

![image](https://user-images.githubusercontent.com/19811858/100390829-fcef3d00-3031-11eb-97e8-a95e02e750a5.png)
![image](https://user-images.githubusercontent.com/19811858/100391347-69b70700-3033-11eb-8e79-bad354c0b5cf.png)

**Comment by Phyks** [comment]
Ok, I get it. Render proposal looks ok to me at first sight. Could you open a PR so we can work on this more in depth? Thanks!
