### ISSUE TITLE
Integration of CyclOSM in Mapbox SDK

### ISSUE THREAD

**Issue by HelloJowet** [cyclosm/cyclosm-cartocss-style#410]
Hi,

I am currently working on an app that contains the Mapbox Android SDK.
I would like to integrate the CyclOSM routes into the Mapbox SDK Map.
Is there a way to display the routes as a layer or style above the map?
I am fairly new to this field. So please excuse me if I missed something.

Kind regards
Jonas

**Comment by Phyks** [comment]
Hi,

CyclOSM is provided as ready-to-use raster tiles (PNG images) at https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm-lite/{z}/{x}/{y}.png. You can reuse them under the same policy as OSM tiles.

You cannot split a single layer from CyclOSM style easily (both routes and background are on the same PNG images).

Alternatively, you might want to consider https://cycling.waymarkedtrails.org/ which provides tiles with routes only.

Best,
