### ISSUE TITLE
Make natural=tree_row more prominent

### ISSUE THREAD

**Issue by majkaz** [cyclosm/cyclosm-cartocss-style#425]
Just an idea to consider: Display natural=tree_row more prominent (wider). 
It seems that it is rendered under other features, so it shouldn't interfere with roads etc. At the moment, you can barely see it - example [here](https://www.cyclosm.org/#map=16/48.9640/14.5597/cyclosm).
It might not be important for bike commuting, but for long distance bike travel in summer, this would be something I would pay attention to.

**Comment by Phyks** [comment]
I would welcome more feedback here. I think this is wide enough and visible from zoom 17 and above. They are simply not drawn at zoom 15. So the matter should be with zoom 16.

CyclOSM is a dynamic map, so I would expect it to be ok to have just a hint of these `natural=tree_row` at zoom 16 and require a zoom in/out to confirm further. But I'm definitely open to feedback and discussion here.
