### ISSUE TITLE
Any difference between cycleway:left=track + cycleway:left:oneway=-1 and cycleway:left=opposite_track?

### ISSUE THREAD

**Issue by westnordost** [cyclosm/cyclosm-cartocss-style#426]
I'd like to ask you if there is any difference in rendering or if it does make a difference in some other way (more difficult to find out, different meaning etc) if there is a street tagged with this:

```
...
oneway = yes
oneway:bicycle = no
cycleway:left = lane
cycleway:left:oneway = -1
cycleway:right = lane
```

...or with this?

```
...
oneway = yes
cycleway:left = opposite_lane
cycleway:right = lane
```

It **looks like** these are synonymous, or even the latter being slightly discouraged/old but I wanted to check with you as the actual data user how this data is interpreted.

I'm asking because I am implementing resurveying cycleways in StreetComplete right now and there is contradictory information about this kind of `opposite` tagging in the wiki. StreetComplete so far only tags the former scheme. So when the user provides a new answer on resurveying, by default, if  it will overwrite the previous value.

Also, because StreetComplete will also have to interpret and display current data, do you interpret

```
...
oneway = yes
cycleway = opposite_lane
```
the same as the two above?

**Comment by Florimondable** [comment]
> I'd like to ask you if there is any difference in rendering or if it does make a difference in some other way (more difficult to find out, different meaning etc) if there is a street tagged with this:
> 
> ```
> ...
> oneway = yes
> oneway:bicycle = no
> cycleway:left = lane
> cycleway:left:oneway = -1
> cycleway:right = lane
> ```
> 
> ...or with this?
> 
> ```
> ...
> oneway = yes
> cycleway:left = opposite_lane
> cycleway:right = lane
> ```
> 
> It **looks like** these are synonymous, or even the latter being slightly discouraged/old but I wanted to check with you as the actual data user how this data is interpreted.

I think we render them the same way, and means the same thing.
I do prefer to use the cycleway:x=opposite_lane as it's shorter to write :)

> 
> I'm asking because I am implementing resurveying cycleways in StreetComplete right now and there is contradictory information about this kind of `opposite` tagging in the wiki. StreetComplete so far only tags the former scheme. So when the user provides a new answer on resurveying, by default, if it will overwrite the previous value.
> 
> Also, because StreetComplete will also have to interpret and display current data, do you interpret
> 
> ```
> ...
> oneway = yes
> cycleway = opposite_lane
> ```
> 
> the same as the two above?

No, we render this we a dashed border on both side as we don't know on which is the cycle lane.
We consider this as a lack of precision of the tag.

**Comment by westnordost** [comment]
OK, thank you!

**Comment by westnordost** [comment]
> No, we render this we a dashed border on both side as we don't know on which is the cycle lane.

Actually, that should be pretty clear. It is ... 
- on the left side if it is in a country that drives on the right and `oneway=yes`
- on the right side if it in a country that drives on the right and `oneway=yes`
- on the left side if it is in a country that drives on the left and `oneway=-1`
- on the right side if it in a country that drives on the left and `oneway=-1`

A contraflow lane that would be (in countries where people drive on the right side) on the right side of oncoming traffic would be silly.

**Comment by westnordost** [comment]
Actually, two more questions:

How do you interpret
```
oneway = yes
cycleway:right = opposite
```
in countries where people drive on the right side?

And, how do you interpret 
```
cycleway = opposite
```
(or any other opposite-tagging) on roads that are actually not oneway?

**Comment by Phyks** [comment]
> I do prefer to use the cycleway:x=opposite_lane as it's shorter to write :)

I do prefer the opposite, as it is consistent across many different patterns. Just a matter of tastes, I would consider them to be strictly equivalent.

> Actually, that should be pretty clear. It is ...

In principle, yes. This is also the tagging description in the wiki. In CyclOSM we do not assume anything though since it is quite difficult to know which is the driving side at render time. StreetComplete might handle this more easily.

> A contraflow lane that would be (in countries where people drive on the right side) on the right side of oncoming traffic would be silly.

It is weird, but it exists. It should however be described with proper lateralized tagging.


Concerning your latest message, I would consider:
*  `oneway=yes` + `cycleway:right=opposite` to be a one way road with an opposite contraflow on the right side.
* `cycleway=opposite` on non-oneway road is a tagging error in my opinion (it should mean a contraflow on each side). It might be implicitly fixed to `cycleway:[opposite direction of driving]=opposite`?

**Comment by westnordost** [comment]
Thanks for your answers!

StreetComplete now treats any `oneway` road + a `cycleway` as having a cycleway only defined on one side (`cycleway=track` = track on right side, `cycleway=opposite_track` = track on left side in opposite direction) but will re-tag with proper `cycleway:right/left` and `oneway:bicycle` when a user re-answers it.

**Comment by westnordost** [comment]
Thanks for your answers!

StreetComplete now treats any `oneway` road + a `cycleway` as having a cycleway only defined on one side (`cycleway=track` = track on right side, `cycleway=opposite_track` = track on left side in opposite direction) but will re-tag with proper `cycleway:right/left` and `oneway:bicycle` when a user re-answers it.
