### ISSUE TITLE
oneway:bicycle=no + cycleway:left:oneway=no

### ISSUE THREAD

**Issue by axelos** [cyclosm/cyclosm-cartocss-style#429]
Bonjour,

Pour un cas de piste cyclable bidirectionnel sur la même chaussée que les voies de circulations pour automobiles, qui eux sont en sens unique, le cas M2d de la page wiki a été utilisé, avec la spécificité qu’il ne s’agit pas d’une bande mais d’une piste cyclable (cycleway:left=track).

https://www.cyclosm.org/#map=17/48.68108/6.17647/cyclosm
https://openstreetcam.org/details/2826770/6/track-info

Sur le rendu cyclosm.org, on voit bien la piste le long du chemin, cependant on voit aussi des flèches indiquant un double sens cyclable. Cela est inapproprié.

Merci pour la lecture !

**Comment by Phyks** [comment]
Bonjour,

Merci pour ce retour. Effectivement, ce rendu ne semble pas idéal... À l'inverse, en enlevant les flèches de double sens cyclable, je ne pense pas que le message que la bande est à double sens (seule la largeur du trait l'indique) soit transparent. Peut-être la solution ici serait-elle d'inclure des double flèches blanches sur la bande cyclable, comme ce qui est déjà fait (à sens unique) pour les contresens cyclables, voir https://www.cyclosm.org/#map=20/48.68444/6.17244/cyclosm.

**Comment by Florimondable** [comment]
L'idée c'est de n'afficher une flèche que pour les pistes à sens unique
https://www.cyclosm.org/#map=20/48.87478/2.36053/cyclosm
visible juste à côté https://www.cyclosm.org/#map=19/48.68423/6.17296/cyclosm

Je comprends que ça peut prêter à confusion.

**Comment by axelos** [comment]
Bonjour,

Merci pour vos retours. Libre à vous de décider au mieux ce qui est bon pour la lisibilité, cependant à titre personnel je pense que le concept actuel prête effectivement à confusion et mérite d’être révisé.

Merci pour la carte qui est tout de même excellente dans son ensemble :) .
