### ISSUE TITLE
Shared cycleway rendered under road tagged with railway=abandoned

### ISSUE THREAD

**Issue by brainwad** [cyclosm/cyclosm-cartocss-style#431]
The z-order for paths should be higher than roads, so they are not clipped at medium zoom. In this picture, the path continues as far as the entrance to the driveway loop next to the restaurant, but it's barely visible beyond the cemetary, due to being quite close to the road:
![image](https://user-images.githubusercontent.com/19811858/92724066-510b4f00-f36a-11ea-86d4-47a9a0abff3e.png)

**Comment by quasart** [comment]
It’s the case already, see z_order in project.mml. Something must be messed up by the specific tagging of this example

**Comment by brainwad** [comment]
The tagging seems perfectly ordinary:
```
bicycle=designated
foot=designated
highway=path
segregated=no
surface=asphalt
```

I suspect the answer is that the road (https://www.openstreetmap.org/way/38594180) is tagged as `railway=abandoned`. Are railways rendering on top of cycleways? IMO all cycle facilities should render on top of everything else, even railways...

**Comment by brainwad** [comment]
I checked in Kosmtik - the z_order of most roads is 33, but the z_order of this one is 71, much higher than the 39 forced for cycleways. The problem seems to come from osm2pgsql's default behaviour?
