### ISSUE TITLE
cycleway:both=lane is not rendered?

### ISSUE THREAD

**Issue by fabiobettani** [cyclosm/cyclosm-cartocss-style#439]
I see that parts of via Luigi Galvani, Milan, Italy and via Pola, Milan, Italy have been tagged with "cycleway:both=lane", but cyclosm apparently doesn't render any bike lane (not even with the Live feature). Is there anything not working correctly?
I see that support for "cycleway:both" was suggested, and marked as accomplished, in 2019. Is there possibly a bug at work here?

**Comment by Florimondable** [comment]
Thanks for the report.

It's here https://www.cyclosm.org/#map=18/45.48770/9.19675/cyclosm_live

**Comment by Phyks** [comment]
Thanks for the report! We had a temporary server issue (running out of disk space) last week. We have been lagging behind OSM database for a while but should be recovering soon.
