### ISSUE TITLE
Closed linear leisure=track+sport=cycling ways are rendered as an area

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#442]
see :
https://www.openstreetmap.org/way/158239095
https://www.cyclosm.org/#map=19/48.82535/2.48268/cyclosm

**Comment by Florimondable** [comment]
But this one is correctly rendered https://www.openstreetmap.org/way/28836778
It has area=no, but closed leisure=track way should be treated as linear by default.

**Comment by quasart** [comment]
according to [osm wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure=track?uselang=en) :

> It's unclear/undecided whether closed ways should be treated as areas for this tag so it is advised to always add an area=yes/no tag in the case of closed ways.

**Comment by Florimondable** [comment]
and « The default OSM Carto stylesheet displays an area only if area=yes is present. »
We should do the same

**Comment by Florimondable** [comment]
So after looking it up, it seems that by default osm2pgsql create a polygon for leisure tagged closed way. OSM Carto has a osm2pgsql import script which create an exception for leisure=track|slipway.

So I guess we will not change this default behaviour (otherwise we have to reimport the whole OSM world).

**Comment by Phyks** [comment]
Same, I guess we can close this one.
