### ISSUE TITLE
Wrong rendering color for cycle path?

### ISSUE THREAD

**Issue by nsomlai** [cyclosm/cyclosm-cartocss-style#443]
https://www.cyclosm.org/#map=14/46.3963/20.3576/cyclosm

The long cycle path going south near road 4414 has a faint purple color (RCN?) even at higher zoom levels. Cannot figure out why, there is nothing specific in OSM that should cause this. It should be the usual dark blue in my opinion.

![Screenshot_1](https://user-images.githubusercontent.com/752057/96693513-9ff3cd80-1387-11eb-9183-fd77e099b847.png)

**Comment by Florimondable** [comment]
Hi,
Tagged with vehicle=no, bicycle is a vehicle hence the cycle path is rendered with a forbidden color.
Should be replace wether by motor_vehicle=no or bicycle=yes, or just remove the tag.

Regards.

**Comment by nsomlai** [comment]
Missed that, thanks! Removed the tag in OSM. Cycle path implies motor_vehicle=no so we should be good.
