### ISSUE TITLE
More visible cycle shop icon

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#448]
specialy in z15

**Comment by Florimondable** [comment]
two proposals

Size correction :
![Screenshot_20201107_181805](https://user-images.githubusercontent.com/47089717/98447517-a2934880-2125-11eb-83cf-3367cd49ff96.png)

Framed :
![Screenshot_20201107_181042](https://user-images.githubusercontent.com/47089717/98447518-a3c47580-2125-11eb-836c-9bc556cf442c.png)

**Comment by Phyks** [comment]
:+1:, I'd be more in favor of first option, framed is a bit too strong in my opinion.

**Comment by Florimondable** [comment]
duplicate of #185
