### ISSUE TITLE
Highway=path/track should be rendered differently than a route

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#45]
Probably in brownish dotted line, as on osm.org.

**Comment by Florimondable** [comment]
Well that depends, a good path (wide and with a good surface) should be rendered as large as a cycleway.
A track is for 4 wheeled vehicules, so it should be rendered large enough.
Path and track can be used to tag "voie verte", which are cycle friendly.
Of course track and path is a playground for gravel and mountain bike so they should be well treated :)

**Comment by Phyks** [comment]
Closing this, it would make sense to keep path/track as large as cycleway or roads. Distinction should be made on surface, which is #12
