### ISSUE TITLE
Motorway Link are red instead of grey (Bicycle are not allowed there)

### ISSUE THREAD

**Issue by tdelmas** [cyclosm/cyclosm-cartocss-style#452]
There: https://www.cyclosm.org/#map=19/48.81742/2.41731/cyclosm_live

![image](https://user-images.githubusercontent.com/1955774/99145527-04950600-2670-11eb-9178-1549dec4b4d5.png)

On this picture, the grey and red roads are forbidden to bicycles.

The `motorway_link` is (kinda) red (Probably "Primary" -"Highway infrastructure") but "Bicycle not allowed" is "grey" and according to https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Default  for `motorway_link`, `bicycle=no` by default.

![image](https://user-images.githubusercontent.com/1955774/99145724-6d30b280-2671-11eb-98b3-5d49d2feeefd.png)

![image](https://user-images.githubusercontent.com/1955774/99145787-d1537680-2671-11eb-98e6-5ee0ceb8c3e9.png)

**So by default, motorway_link should be grey are they are forbidden for bicycles.**

**Comment by Phyks** [comment]
Hi,

Thanks for the very detailed report (and @brainwad for the quick fix).

Best,

**Comment by tdelmas** [comment]
Thank you both, @Phyks and @brainwad !
