### ISSUE TITLE
Island names are not rendered

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#456]

**Comment by Phyks** [comment]
Do you have a specific example? We have it here https://www.cyclosm.org/#map=13/48.0582/-4.8017/cyclosm.

**Comment by Florimondable** [comment]
https://www.cyclosm.org/#map=13/48.4648/-5.0925/cyclosm
Elbe https://www.cyclosm.org/#map=9/42.6582/10.4370/cyclosm
https://www.cyclosm.org/#map=10/-16.0682/-5.7033/cyclosm

**Comment by Florimondable** [comment]
Why closing ?

**Comment by Phyks** [comment]
Sorry, I missed to link the commit with the issue. I fixed it in https://github.com/cyclosm/cyclosm-cartocss-style/commit/f0067b7ef2b88af8c324687120fe6dc1e5ddf64a.
