### ISSUE TITLE
Translation of key

### ISSUE THREAD

**Issue by PJDB22** [cyclosm/cyclosm-cartocss-style#467]
It seems that key is only in English. Do you have any plan to localize it depending on browser preferences ?

**Comment by Phyks** [comment]
Maintaining the legend and ensuring it is always in sync with the style code base is a really time-consuming task. I'm not sure it would be really feasible to have localization.

We however had a long term plan on moving from the current legend to an automatically generated one, relying on a fake OSM world: https://github.com/cyclosm/cyclosm-cartocss-style/issues/109. With such a setup, we could envision having localized legend more easily through the usual `name:{localization}` (fake, here) OSM tags.

I'm closing this one and merging it with the previously opened issue https://github.com/cyclosm/cyclosm-cartocss-style/issues/109.

**Comment by Phyks** [comment]
P.S.: Of course, if you have a working setup available in the short term and easy to maintain, we are warmly welcoming any PR!

**Comment by Florimondable** [comment]
This should be a ticket for https://github.com/cyclosm/cyclosm-website
