### ISSUE TITLE
how to render bicycle parkings without racks nor stands ?

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#469]
![IMG_20201116_150857](https://user-images.githubusercontent.com/8955390/101460921-82c88d80-393a-11eb-9457-017c6cc43e62.jpg)
### issue
there are many bicycle parking for free floating bicycles and e-scooters without racks nor stands. In OpenStreetMap they are tagged as `bicycle_parking=floor `in accordance with the OSM wiki.
in cyclosm they are rendered as any bicycle parking 
![image](https://user-images.githubusercontent.com/8955390/101461405-1e59fe00-393b-11eb-8716-613c1340f9b3.png)
this is misleading as it is only appropriate for free floating bicycles and of little use for cyclists using their personal bicycles.
### solution
a bicycle parking tagged with `bicycle_parking=floor` should be rendered in a different colour. maybe grey blue (same hue but only 50% saturation)
![image](https://user-images.githubusercontent.com/8955390/101462904-0a170080-393d-11eb-96ff-0b6ba679f056.png)

we would have 3 types of bicycle parking
1. standard bicycle parking (amenity=bicycle_parking except bicycle_parking=floor) blue (unchanged)
2. mixed parking for motorcycle and bicycles (amenity=motorcycle_parking and bicycle=yes) greenish blue (unchanged)
3. bicycle parking without stand/rack (amenity=bicycle_parking and bicycle_parking=floor) grey blue (proposed)

**Comment by Florimondable** [comment]
Hi, duplicate of #268

**Comment by patman37** [comment]
oh sorry! i made a search but with the wrong key words. half circle or half grey: whatever you choose.
I will close this issue here
