### ISSUE TITLE
Add covid19 vaccination places ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#477]
https://wiki.openstreetmap.org/wiki/Key:vaccination
vaccination=covid19

**Comment by quasart** [comment]
Hello,
As this is not related to cycling, I feel this feature would be too much out of topic.
Otherwise it could be displayed above the raster map with dynamic request (with overpass turbo ?)

**Comment by Phyks** [comment]
Same impression here, vaccines will be definitely useful, but a bit far from cycling.
