### ISSUE TITLE
Render trail symbols? (osmc:symbol)

### ISSUE THREAD

**Issue by michaelblyons** [cyclosm/cyclosm-cartocss-style#478]
Is there an interest (perhaps long-term) in adding support for route symbols with [`osmc:symbol`](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol)?

**Comment by Phyks** [comment]
Isn't this mostly for hikers / foot? Would you have an example with an added value for cycling, to help discuss rendering more in depth?

Thanks!
