### ISSUE TITLE
Render Dam and Dykes

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#481]
Example https://www.cyclosm.org/#map=17/49.74473/3.79254/cyclosm

**Comment by Florimondable** [comment]
Not sure dykes is very necessary, and there is the area and the linear feature to manage.
May be it should be render with embankment and cutting.

**Comment by Phyks** [comment]
Dams are now rendered. Not sure of the interest of having dykes rendered, plus regular osm.org style does not render them either https://github.com/gravitystorm/openstreetmap-carto/issues/823. We can probably close this one, isn't it?
