### ISSUE TITLE
suggestion: only render bicycle roads with shared way color if sidewalk=no

### ISSUE THREAD

**Issue by DerDings** [cyclosm/cyclosm-cartocss-style#486]
Bicycle roads come with additional rights for cyclists an additional restrictions for motorized traffic. Put pedestrians are still allowed.
So I suggest drawing them with the lighter shared way color if there are no sidewalks to separate the pedestrians.

Maybe I would go even further and _only_ use the darker cycle way blue on bicycle roads with
`"sidewalk" ~ "yes|left|right|both|separate"
or
"foot" ~ "no|use_sidepath`"
otherwise always use the lighter shared way color.

The blue arrows indicating the bicycle designation may remain unchanged.

**Comment by DerDings** [comment]
I found out that the shared way colour is already used (it was altered by a route overlay, so I didn't see it). So I changed the title of the issue. I still think it will be useful to use differently colors depending on the presence of pedestrians on the carriageway.

Please give me some feedback if this is wanted. If so, I will try to create a pull request. This would be my first pull request, so it may take a while.

**Comment by Florimondable** [comment]
Do you have examples ? Not sure to understand the need.

**Comment by DerDings** [comment]
> 
> 
> Do you have examples ? Not sure to understand the need.

This is a bicycle road which needs to be shared with pedestrians:
![obscura1612196366334](https://user-images.githubusercontent.com/42044179/106486635-23a67580-64b2-11eb-91bd-7773fefe4dd8.jpg)

Different section of the same road: There is a sidewalk, so pedestrians are out of the way.
![obscura1612196349697](https://user-images.githubusercontent.com/42044179/106486786-4b95d900-64b2-11eb-8b24-955699ca2a19.jpg)

**Comment by Phyks** [comment]
Linked to #397

**Comment by reinhard-mueller** [comment]
I think this is about a slightly different thing than #397. #397 is about cycleways (highway=cycleway or cycleway=track), while this issue is about bicycle roads (bicycle_road=yes). So I would suggest to keep this open.
