### ISSUE TITLE
[question] ways are rendered differently

### ISSUE THREAD

**Issue by govvin** [cyclosm/cyclosm-cartocss-style#488]
In these two examples:
[![image](https://user-images.githubusercontent.com/5821688/104542231-1427cf80-565e-11eb-9ede-441b71bb537f.png)](https://osm.org/go/4zhHVEOQR?m=)

[![image](https://user-images.githubusercontent.com/5821688/104542086-d1fe8e00-565d-11eb-9c84-e7e3e80f8ce8.png)](https://osm.org/go/4zhSFGAy9?m=)

What does the blue shade on the road indicate? As far as I can tell, the tags are the same for those road segments.

**Comment by quasart** [comment]
This means it belongs to a bicycle route in OSM database

**Comment by govvin** [comment]
Thanks for the reply @quasart 

However, I don't see any lcn=* tags or membership in any route relations for these segments.  How would I know which routes they belong to?

**Comment by Phyks** [comment]
@govvin would you have a link to the specific location please?
