### ISSUE TITLE
Irak and Mongolia name not rendered for some alphabets

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#489]
See https://www.openstreetmap.org/#map=3/31.43/56.60&layers=Y

**Comment by Phyks** [comment]
We were missing a fallback, fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/6be6c861f82b864960480d58dc14bab517374472.

**Comment by soshial** [comment]
Mongolia still not rendered properly.

**Comment by Phyks** [comment]
See https://github.com/cyclosm/cyclosm-cartocss-style/issues/563#issuecomment-841683946.
