### ISSUE TITLE
make the license more visible

### ISSUE THREAD

**Issue by Marc-marc-marc** [cyclosm/cyclosm-cartocss-style#490]
it would be nice to have the [license](https://github.com/cyclosm/cyclosm-cartocss-style#licenses) set at the depot level and/or a licence file

**Comment by Phyks** [comment]
Happy to merged any PR improving this.

**Comment by Marc-marc-marc** [comment]
PR done.
but it does not seem possible to propose a modification of the parameters of a depot with a PR. this is done in the parameters
