### ISSUE TITLE
Hard to see tunnels: cycleways on different levels look like they cross each other

### ISSUE THREAD

**Issue by jdhoek** [cyclosm/cyclosm-cartocss-style#492]
Where a cycleway passes under another through a tunnel, the rendering doesn't clearly show that there is a tunnel. This makes it look as if the cycleways cross instead of one going underneath the other.

Example ([OSM](https://www.openstreetmap.org/#map=19/53.19189/5.78003&layers=N)):

![Screenshot from 2021-01-16 14-19-35](https://user-images.githubusercontent.com/683699/104812948-1c227380-5806-11eb-9fff-95d77e187c5b.png)

It does look like tunnels are in a lighter blue, but I find it hard to tell.

OSM-Carto for comparison:

![Screenshot from 2021-01-16 14-19-46](https://user-images.githubusercontent.com/683699/104812949-22b0eb00-5806-11eb-817b-d8bce66ed25f.png)

-----

Nice to see the CyclOSM layer on openstreetmap.org as well. I find it very useful as a mapper to quickly see different renderings styles for different purposes after working on an area. :+1:

**Comment by Phyks** [comment]
Tunnels are indeed in lighter blue. Thanks for the feedback. I can confirm the contrast is quite clear on my desktop screen, but super hard to read on my smartphone screen. We should probably make it more striking.

**Comment by Florimondable** [comment]
The dashing of OSMCarto is nice, we already draw the outline of tunnel roads with dashes.
