### ISSUE TITLE
Render traffic_calming=*

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#5]

**Comment by Phyks** [comment]
Done for traffic calming values in 'yes', 'bump', 'dip', 'choker', 'cushion', 'hump', 'rumble_strip'.

Render is 

<img width="448" alt="capture d ecran 2019-02-12 a 19 31 47" src="https://user-images.githubusercontent.com/3856586/52659202-17a7fe80-2efd-11e9-91d5-9a5e29266296.png">

**Comment by Florimondable** [comment]
Table https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dtable should be added too ?
They are very common in Paris and will be more and more.
