### ISSUE TITLE
Treat a living_street as if it has a speed limit

### ISSUE THREAD

**Issue by geozeisig** [cyclosm/cyclosm-cartocss-style#500]
Treat a living_street as if it has a speed limit of max 20 km/h.
[Tag:highway=living_street](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street): _The implicit speed limits set in legislation vary from "walking speed" up to 20 km/h, in some countries, the speed limit is given explicitly on the sign._
If we don't do it that way,  have to add maxspeed to every living_street.

**Comment by Florimondable** [comment]
duplicate of #238
