### ISSUE TITLE
Bicycle crossing missing ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#503]
here : https://www.openstreetmap.org/node/2468846741#map=20/45.41069/11.89603&layers=Y
though this one is ok https://www.openstreetmap.org/node/713160518

**Comment by Phyks** [comment]
My wild guess is that it conflicts with a nearby node, such as https://www.openstreetmap.org/node/3766349043, but this is quite weird.

**Comment by Phyks** [comment]
My bad, this is due to the exclusion of service highway here https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/project.mml#L1700.

This can probably be safely removed.
