### ISSUE TITLE
traffic_calming=table rendering takes precedence over highway=crossing

### ISSUE THREAD

**Issue by voschix** [cyclosm/cyclosm-cartocss-style#521]
When the crossing node is tagged highway=crossing and traffic_calming=table, only the table is rendered, but not the road crossing.
[Example](https://www.openstreetmap.org/node/1912641207)
[Mapillary image](https://www.mapillary.com/map/im/S6kPpsaCgaqh6ZXEcoZd9X)

Ideally the two symbols could be superimposed. 
If that is not possible, I would give preference to the crossing.

**Comment by Phyks** [comment]
I think this is a duplicate of https://github.com/cyclosm/cyclosm-cartocss-style/issues/503. Let's continue the discussion there.
