### ISSUE TITLE
Commercial areas are not easy to spot

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#526]
See https://www.openstreetmap.org/#map=16/48.7818/2.2180

![2021-02-27-190558](https://user-images.githubusercontent.com/3856586/109395859-dc839700-792e-11eb-8ec5-4365d97fc95d.png)
![2021-02-27-190606](https://user-images.githubusercontent.com/3856586/109395860-dd1c2d80-792e-11eb-9623-bdebe4f7b0f9.png)

**Comment by Cuervino** [comment]
1. This specific area is a mix of shops/mall (landuse=retail), and of office area ("landuse"="commercial"). 
2. From the cyclist point of view, what would he benefit from having this information of commercial?
Where to go for shopping? That those areas have massive "rush hour" traffic-zone?

![2021-03-01_11h18_14](https://user-images.githubusercontent.com/28654802/109483690-d81ac380-7a7f-11eb-8ea3-8544cf7f10a9.png)

![image](https://user-images.githubusercontent.com/28654802/109483797-f54f9200-7a7f-11eb-8ea9-67d30eca85d2.png)

**Comment by Phyks** [comment]
Sorry, this was a quick reminder, I should probably have added more details. This is a very large regional mall (called "Velizy 2" in the first picture).

Due to its size, it is likely this shopping mall will be of interest for people living nearby (they might want to go there do some shopping). It is also a very useful place to quickly guess where you are located.

In my case, I was using BRouter to draw some route such as http://brouter.de/brouter-web/#map=14/48.7925/2.2494/cyclosm,Waymarked_Trails-Cycling&lonlats=2.299404,48.810481;2.2203,48.781907. The end point was really difficult to place correctly due to very few labels in the area.

**Comment by Phyks** [comment]
I know this place having similar issue http://brouter.de/brouter-web/#map=17/45.64777/-1.05226/cyclosm,Waymarked_Trails-Cycling.

Also note that although big shopping malls are usually not cycle-friendly they can be of interest for 1) knowing this place is probably not bike-friendly, 2) knowing you can buy basically everything you might want there, which can be handy in long distance trips.

**Comment by matkoniecz** [comment]
I am not convinced that it is something that should be prominent in this map style.

Trying to display everything will end badly, we have no need for OSM Carto that is trying to display also all bicycle infrastructure in addition to displaying everything.
