### ISSUE TITLE
railway=station not rendered for areas or missing for some other reason

### ISSUE THREAD

**Issue by matkoniecz** [cyclosm/cyclosm-cartocss-style#527]
https://www.openstreetmap.org/way/575701389#map=18/52.22876/21.00297&layers=Y

Originally reported in https://www.facebook.com/groups/500589303317858/permalink/3881724981870923/

![screen](https://user-images.githubusercontent.com/899988/110085766-cc861000-7d91-11eb-8ea0-1885aec441bf.png)

**Comment by Phyks** [comment]
We are only considering node train stations, this one is an area. Hence the issue.

See: https://github.com/cyclosm/cyclosm-cartocss-style/blob/e9eda82c18fcf148a5ceb8e04e8f94ef247c76b8/project.mml#L1658-L1671
