### ISSUE TITLE
Give way for cyclist arrows are difficult to read

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#528]
Coming from the north you can go west (turn right).
Coming from the west you can go south (turn right).
The arrows are in the point of view of the cyclist "turn right" so we draw an arrow going to the right.
But with the point of view of the map reader, it would be easier to read if the arrow is pointing toward the direction on the map.
In this example with arrow going west (left) and south (down).

https://www.cyclosm.org/#map=20/48.87775/2.36550/cyclosm_live
![image](https://user-images.githubusercontent.com/47089717/110540054-4cabcd00-8126-11eb-8adb-86fa3b5c01ff.png)

**Comment by Florimondable** [comment]
I think there is a bug on the right one.

![image](https://user-images.githubusercontent.com/47089717/110541076-8c26e900-8127-11eb-8e38-287b3b3a633a.png)


I wonder if it’d be easier to read if the triangle-arrow is on the way from, like the board is in real life.

**Comment by Phyks** [comment]
Indeed, there was a bug with angles. Reworking in #513.
