### ISSUE TITLE
Rendering of train stops

### ISSUE THREAD

**Issue by Ivans-Git** [cyclosm/cyclosm-cartocss-style#529]
For some reason the halt train stops are more important than the most important train stations in the cities, for example: https://i.imgur.com/ILjK1eK.png
https://www.cyclosm.org/#map=13/43.3463/-8.3939/cyclosm

**Comment by Phyks** [comment]
Duplicate of #527.

**Comment by Ivans-Git** [comment]
> Duplicate of #527.

Curiously if the station attributes are in a building and not in a separate point the station is not even shown...
https://www.openstreetmap.org/#map=19/43.35245/-8.40995&layers=Y
