### ISSUE TITLE
Remove "Double way streets for bikes (one way for cars)" symbol

### ISSUE THREAD

**Issue by DerDings** [cyclosm/cyclosm-cartocss-style#532]
I think we should completely remove oneway arrows in `oneway:bicycle=no` streets. They are an (anti-)feature for motorists, not for cyclists.

This way, the blue arrows remain as a symbol for `bicycle=designated` only.

`oneway=no` is considered default and drawn without any additional symbols. From a cyclists perspective, `oneway=no` and `oneway:bicycle=no` are the same, so there is no need to put any additional symbols in this road. 
![grafik](https://user-images.githubusercontent.com/42044179/111075686-821b3680-84e9-11eb-9bc9-4e7e8e0f5b59.png)
Imagine all the "Double way streets for bikes (one way for cars)" symbols would be completely removed [in this example](https://www.cyclosm.org/#map=16/50.0768/8.2507). The map would look a lot neater, while no useful information is removed (as long as you're not a motorist using cyclosm accidentally).

The remaining symbolic would be:

- basic road, no arrow: 
cycleable in both directions (either `!oneway`, `oneway=no and !oneway:bicycle` or `oneway:bicycle=no`)
- ![layer1](https://user-images.githubusercontent.com/42044179/111076732-cd374880-84ed-11eb-86b7-6b3171c022af.png) grey arrow:
cyclable only in the direction of the arrow (`oneway= yes and !oneway:bicycle` or `òneway:bicycle=yes`)

- ![designated](https://user-images.githubusercontent.com/42044179/111076752-e63ff980-84ed-11eb-8d76-d3a2df8e4f1c.png) two blue antipodal arrows:
bicycles designated in both directions (`bicycle=[designated|official]`)
- ![oneway-designated](https://user-images.githubusercontent.com/42044179/111076767-f8ba3300-84ed-11eb-939c-9b1c77bb6521.png) blue arrow:
bicycles designated in one direction (`bicycle:[forward|backward]=[designated|official]`)

- ![oneway-designated](https://user-images.githubusercontent.com/42044179/111077001-150a9f80-84ef-11eb-9ded-2c9f22b06669.png)![layer1](https://user-images.githubusercontent.com/42044179/111077007-1f2c9e00-84ef-11eb-85d5-2486615ab589.png) blue arrow and grey arrow pointing in the same direction:
oneway road designated to cyclists. (combination of the cases above)

This way it would be clear that:
**grey** arrows always indicate roads only cycleable in one direction.
**blue** arrows always indicate designated roads.

**Comment by DerDings** [comment]
Since this makes blue arrows and grey arrow completely different features, #389 won't be a problem anymore.

**Comment by Florimondable** [comment]
I understand the logical point, but in terms of feeling, comfort or security, going on the road against the motor vehicle flow is not the same as riding on a road with vehicle in both direction.

**Comment by DerDings** [comment]
> 
> 
> I understand the logical point, but in terms of feeling, comfort or security, going on the road against the motor vehicle flow is not the same as riding on a road with vehicle in both direction.

I get your point, but in reality, I have never seen a road where this matters.

One way regulations exempting cyclists are used in small streets with discontinuous traffic flow.
But to make cyclists feel "protected" against oncoming traffic in small roads, it needs continuous convoying traffic, which would force the oncoming vehicles to leave enough space.
But there's no difference to me between roads where convoying traffic is not allowed and roads where convoying traffic is not always given because of overall low traffic.

Another case where `oneway:bicycle=no` may be tagged are roads which have a designated cycle way for the opposite direction. Here the quality of the cycle way essentially determines how safe cyclists feel. The direction of the motorized traffic does not. But this cycle way is shown as an independent feature on cyclosm, so I see no need for additional blue+gray arrows here as well.


Maybe you know some countries which allows opposite cycling on heavily used one way roads without any form of cycle way. Then this feature would be important. But I don't think it is done anywhere. Exemptions for cyclists are made to promote cycling, which cannot really be achieved in described situation.

**Comment by Phyks** [comment]
> Maybe you know some countries which allows opposite cycling on heavily used one way roads without any form of cycle way. Then this feature would be important. But I don't think it is done anywhere. Exemptions for cyclists are made to promote cycling, which cannot really be achieved in described situation.

One example is https://www.google.fr/maps/@48.8385989,2.3515876,3a,75y,283.77h,77.27t/data=!3m6!1e1!3m4!1sPNc6NwTJaPExAl4mmQ-1Nw!2e0!7i16384!8i8192. Cyclists can go countraflow, without any specific nor dedicated infrastructure. The highway is used a shortcut by many motorists, implying quite heavy traffic. It is quite narrow as well, meaning motorist or cyclist should give way regularly.

**Comment by DerDings** [comment]
> 
> 
> > Maybe you know some countries which allows opposite cycling on heavily used one way roads without any form of cycle way. Then this feature would be important. But I don't think it is done anywhere. Exemptions for cyclists are made to promote cycling, which cannot really be achieved in described situation.
> 
> One example is https://www.google.fr/maps/@48.8385989,2.3515876,3a,75y,283.77h,77.27t/data=!3m6!1e1!3m4!1sPNc6NwTJaPExAl4mmQ-1Nw!2e0!7i16384!8i8192. Cyclists can go countraflow, without any specific nor dedicated infrastructure. The highway is used a shortcut by many motorists, implying quite heavy traffic. It is quite narrow as well, meaning motorist or cyclist should give way regularly.

Okay now I understand. Where I live, traffic authorities aren't even _allowed_ to place bicycle enablement signs in such narrow roads, due to safety concerns. If they wanted to set up this exception for cyclists, they would need to clear some space first (reduce parking lanes to only one lane or make the whole road walking speed so the sidewalks can be renounced).


This makes me a little bit sad. Partly, because I have to cope with all those unnecessary blue and gray arrows in so many streets. But it makes me sad even more that placing two rows of private, >2m broad vehicles in public space is given more importance than cyclist's safety, even in central European metropolises.

**Comment by Phyks** [comment]
Ok, I understand the misunderstanding now. This is pretty common in France and I could also see similar infrastructure in Europe. The "double arrow" rendering was design with these infrastructures in mind.

Sadly, the only way I see to efficiently fix this is to have geo-specific rendering in CyclOSM, to account for the wide diversity of bicycle maturity across countries. We have a couple of similar issues, but having geo-specific rendering into CyclOSM is way too difficult at the moment (compared to current manpower for instance) :/

**Comment by DerDings** [comment]
While commenting on #389 I had another idea. I hope it is not too complex to implement:

I think this double arrow may be necessary on roads like this
>One example is https://www.google.fr/maps/@48.8385989,2.3515876,3a,75y,283.77h,77.27t/data=!3m6!1e1!3m4!1sPNc6NwTJaPExAl4mmQ-1Nw!2e0!7i16384!8i8192.

But it is not necessary in roads which have a cycle way. It can even be confusing when there is a cycleway shown on the side to also have blue arrows in the middle of the road.
So maybe the arrows could be left out if there is any cycle way tagged on this road, and only be shown in roads without a cycle way.

**Comment by quasart** [comment]
I like this compromise idea

**Comment by DerDings** [comment]
#260
