### ISSUE TITLE
Countours improvements

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#534]
- [ ] From z11 contours in mountain range is too much visible, mountains are orange. (z12-13 are the worst)
https://www.cyclosm.org/#map=11/44.9298/6.2698/cyclosm
We should try to copy OpenTopoMap for there colors intensity 
- [ ] Elevation numbers on the lines are difficult to read
- [ ] There is too much elevation numbers

**Comment by Phyks** [comment]
We have 100m and 50m contours at Z11, plus 20m at Z12, plus 10m at Z13. We might rather have 100m at Z11, plus 50m at Z12. 20m / 10m does not seem useful before Z14/Z15.

**Comment by Phyks** [comment]
Also, in urban areas, contours might be confused with paths:

https://www.cyclosm.org/#map=18/48.81674/2.31852/cyclosm

![Uploading Screenshot_2021-03-17 CyclOSM.png…]()

**Comment by Florimondable** [comment]
10m à z13 is needed in plains areas https://www.cyclosm.org/#map=13/49.8114/3.8993/cyclosm

I just think it's the color/opacity/intensity of the line which leads to this orange moutains, opentopomap don't have this issue

**Comment by quasart** [comment]
Hello,

you could choose a lighter contour line color to make them less visible. Maybe yellow instead of brown to make clear line is not a footway.

With `comp-op: multiply;` it would be still visible on all shades of land color because it darkens instead of painting over.

**Comment by soshial** [comment]
I agree with the topic starter, that at zoom level 12 and 13 mountains covered with forest look quite **brown**.

![Screenshot_20210502_170441](https://user-images.githubusercontent.com/100644/116814181-8b7b6380-ab68-11eb-8fcd-05d587df8344.png)
