### ISSUE TITLE
cyclosm Layer not accessible in any app

### ISSUE THREAD

**Issue by Cuervino** [cyclosm/cyclosm-cartocss-style#544]
Am I the only one in this case?

https://user-images.githubusercontent.com/28654802/112722134-f4d3db00-8f07-11eb-89d7-83d6c07bd3cb.mp4

**Comment by Phyks** [comment]
The third option "CyclOSM (better for BE)" is not expected to work outside of Belgium.

The first two options are working fine here. Could it be a privacy extension (uBlock and so on) messing with requests?

**Comment by Cuervino** [comment]
In fact, "cyclOSM Live" is working, but not "cyclOSM". 
I tried deleting the cache ; on Firefox (in SafeMode to remove the privacy extension possibility) and on Chrome (that has full different settings) on my computer, still doesn't work.
It's not linked with my network, as it's ok on the wifi with my smartphone.
It looks like the png tiles cannot be loaded, even if the rest is fine.
![image](https://user-images.githubusercontent.com/28654802/112750083-acc7bd80-8fc6-11eb-8754-ee5b98e82102.png)

**Comment by Cuervino** [comment]
I restarted my box, and now it's ok. 
I'm closing the issue, thanks!
