### ISSUE TITLE
render route name

### ISSUE THREAD

**Issue by Reedyn** [cyclosm/cyclosm-cartocss-style#546]
At appropriate zoom levels it would be great if the route names were visible. Something similar to how [Thunderforest Outdoors](https://www.thunderforest.com/maps/outdoors/) render it.

```
route=mtb|bicycle
name={Route Name}
```

![image](https://user-images.githubusercontent.com/947063/113268983-4a2d3500-92d8-11eb-8218-33414cae0637.png)

**Comment by Reedyn** [comment]
> I guess you’re example is about this one https://www.openstreetmap.org/relation/12406665
> It’s a foot route, not a bicycle route.

The example was just a style example.


> Bicycle route name are already rendered, see https://www.cyclosm.org/#map=17/59.30710/18.02318/cyclosm

I didn't actually notice this. That's great, but mtb routes don't have their name rendered so that's something that would be nice to have included.

**Comment by Florimondable** [comment]
MTB routes have their name rendered.

**Comment by Reedyn** [comment]
They don't for any of my local routes.

[Se here for example](https://www.cyclosm.org/#map=17/57.78261/14.08935/cyclosm), the bicycle route's name (_Hallbyleden_) is rendered but not the MTB route (_Hallby MTB - Blå slinga_)

![image](https://user-images.githubusercontent.com/947063/113271549-f3752a80-92da-11eb-9598-e506ed1116ec.png)

**Comment by Reedyn** [comment]
After some comparison with MTB routes in other areas that do render the name it seems to do with the network metadata missing. I apologize for the intrusion. Love the map! :)

**Comment by Filip10** [comment]
Hello, can you please tell me how did you solved your problem with MTB routes named not visible? I have the most likely same issue. https://www.cyclosm.org/#map=16/48.6678/20.5667/cyclosm
![obrázok](https://github.com/cyclosm/cyclosm-cartocss-style/assets/25711588/81f3d275-efb4-439b-be82-1183e01533dd)

**Comment by Filip10** [comment]
Okay, thx. I have changed network of each one and grupped them into one new network relation.
