### ISSUE TITLE
Consider rendering man_made=bridge

### ISSUE THREAD

**Issue by matkoniecz** [cyclosm/cyclosm-cartocss-style#551]
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge

https://www.openstreetmap.org/#map=19/50.08651/14.41069&layers=Y

![screen04](https://user-images.githubusercontent.com/899988/114317511-b6920a80-9b08-11eb-914d-c1b350920f21.png)
![screen05](https://user-images.githubusercontent.com/899988/114317513-b7c33780-9b08-11eb-9f8f-07c44d34193b.png)

I would expect that any place with `man_made=bridge` would benefit from rendering it.

See for example https://www.openstreetmap.org/#map=20/50.04962/19.93423&layers=Y

**Comment by quasart** [comment]
I have already thought it would be valuable in the case of a bridge that contains several separated ways : it's rendered today like two bridges.

example : https://www.cyclosm.org/#map=19/47.47405/-0.55734/cyclosm

**Comment by Florimondable** [comment]
Could be rendered the same as buildings, like dams in #502.
