### ISSUE TITLE
when is a street rendered as bad surface or very bad surface?

### ISSUE THREAD

**Issue by joshinils** [cyclosm/cyclosm-cartocss-style#560]
I have looked (both physically with my bike and GoPro and then on osm) at the streets in my neighborhood.
Now I have checked and corrected the `surface` tagging and added some `smoothness` tagging.

How is it decided which `surface` and `smoothness` combinations get shown as "bad surface"? is it only the `surface` tag? For which values then is it a "bad surface"? 
I would not necessarily say that `surface=concrete:plates` is inherently a "bad surface", i would probably tag it with `smoothness=good` or `smoothness=intermediate` according to this chart: https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness however the part i have tagged with only `surface=concrete:plates` is shown as "bad surface".

Also, why are only two values of the `smoothness` scale considered?

**Comment by Phyks** [comment]
Hi,

The surface / smoothness logic is here: https://github.com/cyclosm/cyclosm-cartocss-style/blob/140c8c1/project.mml#L581-L604

Regarding ` surface=concrete:plates`, from my experience these tend to have quite a lot of gaps. Therefore, it is probably ~ ok for a trekking bike, but definitely not something you like riding with a road bike. Situation / signification might differ around the globe. Around here, such surface is at the very best a `smoothness=intermediate`.

Smoothness is preferred to surface, so adding smoothness onto `surface=concrete:plates` should give a proper render.

**Comment by Florimondable** [comment]
I just created a page on the wiki to help people to understand how CyclOSM interprets tags :
https://github.com/cyclosm/cyclosm-cartocss-style/wiki/Tag-to-Render

**Comment by joshinils** [comment]
> I just created a page on the wiki to help people to understand how CyclOSM interprets tags :
> https://github.com/cyclosm/cyclosm-cartocss-style/wiki/Tag-to-Render

Ah, ok. thank you very much.
So I have not tagged a road as MTB-quality around here, makes sense.
Might also be, _because_ I use this chart: https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness

The `concrete:plates` around here are mostly ok, and faar better than `sett`!
Maybe I will tag the worst `sett` with very large stones and deep grooves as `smoothness=horrible` (just as tagging for the renderer though, so idk)

I am trying to tag every street in [Frohnau](https://www.openstreetmap.org/relation/16330) with both `surface` and `smoothness` hence why I asked in the first place.

**Comment by joshinils** [comment]
well, according to the wiki: https://wiki.openstreetmap.org/wiki/Key:smoothness
(and the aforementioned table) would suggest that `horrible` would never occur on a residential road, but I feel like there is a distinction between `bad` and `very_bad` which would make me not want to use one over the over.
So, for normal Roads a finer scale would be better suited than a binary good/bad tag, which to me just says: either good or sett, I could not differentiate intermediate not very_bad.
I think a separate tag for the MTB- type ways would be better anyway along with some form of indicator for the surface _and_ smoothness of a road or path.
