### ISSUE TITLE
Show romanized name under local name in non-Latin writing

### ISSUE THREAD

**Issue by soshial** [cyclosm/cyclosm-cartocss-style#561]
For me as a foreigner it is almost impossible to navigate with **cyclosm** in countries that don't use Latin writing systems. Compare readability between 2 layers.

Other issues:
* _cyclosm_ looks blurry and not sharp compared to very sharp image of _CycleMap_. Is it because I use 4K screen?

**Cycle Map**:
![Screenshot_20210502_164009](https://user-images.githubusercontent.com/100644/116813559-4f92cf00-ab65-11eb-90dc-c3c550fc0a6b.png)

**CyclOSM**:
![Screenshot_20210502_164101](https://user-images.githubusercontent.com/100644/116813576-62a59f00-ab65-11eb-9a70-a54a0d55de13.png)

**Comment by Phyks** [comment]
Hi,

Thanks for the report. We adopt the same strategy as osm.org here by rendering only locale names. 

Always rendering latin alphabet names is perfect for western people but probably makes no sense for anyone using a non-latin alphabet.

So the strategy should probably be more elaborated than just rendering latin names, and I canot come up with anything both usable and lightweight for everyone at the moment. :/

**Comment by soshial** [comment]
I didn't suggest rendering only Latin titles. I suggested rendering both Latin and non-Latin.

**Comment by Phyks** [comment]
Sure, and this works for any non-latin country.

What about a city such as New York? https://www.openstreetmap.org/relation/175905

Should we only render latin name? Otherwise, which non-latin alphabet / names should we render?
