### ISSUE TITLE
Italic (cursive) text for regions doesn't work for some scripts 

### ISSUE THREAD

**Issue by soshial** [cyclosm/cyclosm-cartocss-style#562]
For [Armenian and Georgian](https://www.cyclosm.org/#map=8/41.606/45.110/cyclosm) script regions and parks should be italic, but they are not.

Because of this it is hard to discern cities from regions. Have a look at the screenshot (green are italic: correct; red are not italic but should be):
![Screenshot_20210502_215321](https://user-images.githubusercontent.com/100644/116822663-15d7bd80-ab91-11eb-87ce-67af13825912.png)

**Comment by Phyks** [comment]
Is there the same issues in osm.org style?

Italics font are defined in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/fonts.mss#L184 and are the same as in osm.org style https://github.com/gravitystorm/openstreetmap-carto/blob/master/style/fonts.mss#L192

**Comment by soshial** [comment]
OSM main style doesn't utilize italic much, but it suffers the same problem
with italic.

For example, parks titles should be italic for all languages, but it
doesn't work with Georgian and Armenian languages.
