### ISSUE TITLE
Labels duplicated at zoom=16

### ISSUE THREAD

**Issue by jidanni** [cyclosm/cyclosm-cartocss-style#564]
![20210506T022511](https://user-images.githubusercontent.com/1230959/117190747-6447bf00-ae12-11eb-809e-118063361aa3.jpg)

https://www.openstreetmap.org/#map=16/24.1705/120.8234&layers=Y

**Comment by Phyks** [comment]
Hi,
Thanks for the report! Is there a single object or is it coming from two different objects in the area, with the same name? Additionally, could you point me towards the right object with this specific name?

Thanks,

**Comment by jidanni** [comment]
All I know is:
https://www.openstreetmap.org/#map=15/24.1678/120.8178&layers=Y reddish label.
https://www.openstreetmap.org/#map=16/24.1678/120.8178&layers=Y reddish label + black label.
https://www.openstreetmap.org/#map=17/24.1678/120.8178&layers=Y black label.

There should be no overlap during the transition.

**Comment by Phyks** [comment]
This seems to be a conflict due to the fact that the same object is a `landuse=military` and an aerodrome.

Not sure why it happens here though, I cannot reproduce it with any other such object worldwide.
