### ISSUE TITLE
Render bicycle shops when multiple values are used for a shop tag

### ISSUE THREAD

**Issue by VladimirMorozov** [cyclosm/cyclosm-cartocss-style#573]
Values for shops like this
`shop=bicycle;car_parts`
are not rendered.

https://www.openstreetmap.org/node/8757476652#map=20/59.44422/24.86005&layers=Y
This shop sells both car and bicycle parts and also offers bicycle repairs.
I think it should be rendered the same as a shop=bicycle.

**Comment by Phyks** [comment]
Hi,

Thanks for the report. Sadly, `;` for separating values of a given OSM tag is not standardized across OSM and very few tools can efficiently using it. As such, supporting it in CyclOSM would require either adding support for all `bicycle;*` values, or using a regex-like SQL query to fetch the `shop=*bicycle*` tags. Both are not something that can be envisioned at the scale CyclOSM is operating.

A better workaround is to add `service:bicycle=*` tags that will be rendered in CyclOSM: https://github.com/cyclosm/cyclosm-cartocss-style/blob/140c8c1/project.mml#L1804-L1808.

Best

**Comment by VladimirMorozov** [comment]
@Phyks it does have a service:bicycle:repair=yes tag.

**Comment by quasart** [comment]
It looks like housenumber is rendered with higher priority than bicycle repair amenity

**Comment by Phyks** [comment]
We were missing `service:bicycle:*` nodes which would not have been rendered otherwise (no other tag rendered). This is fixed in https://github.com/cyclosm/cyclosm-cartocss-style/commit/c84bfea3f7a1d7a439f0b710080f44e95ebf5417.

Thanks for pointing out @VladimirMorozov !
