### ISSUE TITLE
sidewalk:left:bicycle=yes is rendered but sidewalk:bicycle=yes is not?

### ISSUE THREAD

**Issue by momu** [cyclosm/cyclosm-cartocss-style#574]
The [way 515846204](https://www.openstreetmap.org/way/515846204) is tagged with (among other keys):
```
highway=tertiary
sidewalk:foot=designated
sidewalk:left:bicycle=yes
sidewalk:left:smoothness=good
sidewalk:left:surface=asphalt
sidewalk:left:traffic_sign=DE:239,1022-10
sidewalk:right:smoothness=intermediate
sidewalk:right:surface=paving_stones
sidewalk:right:traffic_sign=DE:239
sidewalk=both
```
This results in a green line left to the street in the screenshot below. The [way 428329913](https://www.openstreetmap.org/way/428329913) is connected in the south to the way `515846204`. It is tagged like this:
```
highway=tertiary
sidewalk:bicycle=yes
sidewalk:foot=designated
sidewalk:left:smoothness=good
sidewalk:left:surface=asphalt
sidewalk:right:smoothness=intermediate
sidewalk:right:surface=paving_stones
sidewalk:traffic_sign=DE:239,1022-10
sidewalk=both
```
I would expect to see a green line on each side of the road from housenumber `21A` southwards.

![image](https://user-images.githubusercontent.com/1451642/119414381-c5ff9880-bcef-11eb-8f6e-7cca0a0f1d82.png)

Can it be that sidewalk:left:bicycle=yes is rendered but sidewalk:bicycle=yes is not?

**Comment by Phyks** [comment]
CyclOSM supports `sidewalk:both:bicycle` instead of `sidewalk:bicycle` https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/views.sql#L63. From taginfo, it seems this should also be the preferred tagging scheme? https://taginfo.openstreetmap.org/keys/sidewalk:both:bicycle
