### ISSUE TITLE
Make shop=sports with bicycle:service:* tags more visible

### ISSUE THREAD

**Issue by VladimirMorozov** [cyclosm/cyclosm-cartocss-style#579]
Currently I see shop=bicycle at zoom 14 and shop=sports with bicycle:service:* only at zoom 17. Moreover, they have a special icon where bicycle is less visible. Is there a reason behind this? 

![11](https://user-images.githubusercontent.com/2279813/120693857-378ad400-c4b2-11eb-89dd-5945d535f91a.PNG)

I don't think that when shop doesn't specialize only on bicycles, it always has a worse mechanic than a bicycle shop. I can't think of any other reason to discriminate against these shops.

Also,
1) Other shops like shop=bicycle;car_parts with bicycle:service:repair=yes are rendered like any other bicycle shop
2) In my country not many people ride in the winter, many bicycle shops specialize also in skiing and offer ski service. They may get tagged as shop=sports since they are not only about bicycles. This will make them less visible.

I think that shop=sports with bicycle:service:* tags should be rendered at the same zoom level as other bicycle shops and their icon should have the same visibility.

**Comment by Phyks** [comment]
Such shop=sports and bicycle:service:retail|rental|repair should be displayed from zoom 16 https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/amenities.mss#L775-L786. There might be a bug there (I think Mapnik might not support nested zoom levels with outer level higher than internal one).

We could probably show them from Z14 and collapse their icons with regular `shop=bicycle` indeed.


Regarding `shop=bicycle;car_parts with bicycle:service:repair=yes`, this should be solved in the upcoming version https://github.com/cyclosm/cyclosm-cartocss-style/issues/573#issuecomment-848942745.
