### ISSUE TITLE
The elements' "addr:housename" is unexpectedly rendered

### ISSUE THREAD

**Issue by govvin** [cyclosm/cyclosm-cartocss-style#582]
On CyclOSM some features are unexpectedly rendered with their addr:housename instead of their name:
![image](https://user-images.githubusercontent.com/5821688/121766991-26178b00-cb88-11eb-95fd-07fcf9f4a73c.png)

This is how they look like in Humanitarian and Mapnik:
![image](https://user-images.githubusercontent.com/5821688/121766960-fc5e6400-cb87-11eb-81a4-b88079b4b77f.png)

![image](https://user-images.githubusercontent.com/5821688/121766972-07b18f80-cb88-11eb-91e7-a5b912e44a80.png)

This is the location: https://www.openstreetmap.org/#map=19/14.60437/121.01888

**Comment by Phyks** [comment]
Our `addr:` rendering is exactly the same as the default osm.org one. The only difference is that osm.org default rendering shows more POI types, which masks the underlying `addr:`.

I guess this is the common issue of `addr:` tagging in OSM, sometimes they should be considered as uniquely defining an address (then, a single point per address => a single point for the whole mall) and sometimes they are used as contact address (leading some mappers to push towards the `contact:addr` scheme).

Not sure there is much we can do here to improve the rendering.
