### ISSUE TITLE
Dangerous condition due mtb:scale=6 rendered like mtb:scale=3

### ISSUE THREAD

**Issue by amadvance** [cyclosm/cyclosm-cartocss-style#583]
Hi,

At present the mtb:scale=6 attribute is rendered exactly like the mtb:scale=3. This is a potential dangerous condition as people may enter trails impossible to ride. (The 6 exactly means not rideable).

Note that the mtb:scale=6 is an officially approved difficulty level. See: https://wiki.openstreetmap.org/wiki/Key:mtb:scale

The following screenshot show two nearby trails, one mtb:scale=3 and the other mtb:scale=6. You can easily see that they have identical aspect.

![mtb_scale_3_vs_6](https://user-images.githubusercontent.com/747159/123153245-bfd31800-d465-11eb-995e-1b88cfa27d8c.png)

This is the location of the screenshot: https://www.cyclosm.org/#map=20/45.77212/9.52970/cyclosm

Considering that people may get in serious trouble, whatever solution that remove this hazard is welcome. In case you can just show them as mtb:scale=5, or bycicle=no. 

Thanks!
Andrea

**Comment by quasart** [comment]
Indeed, no style is defined there for scale 6 :

https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/roads.mss#L3606

**Comment by Florimondable** [comment]
condition [mtb_scale<6] should be added to the main condition :
#roads_high::mtbscale[mtb_scale>=0][zoom>=15]

[mtb_scale=x] should be also replace by [mtb_scale>=x]

What I don't understand is level S6 si not defined by the STS http://www.singletrail-skala.de/, is it only used by OSM contributors ?

**Comment by amadvance** [comment]
The S6 is used to mark segments that you cannot ride, and you have to walk them.  It's someway expected that the STS doesn't report it, as they are not rideable.

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/a5bb525fc34a2117cae6a6ef595e5115e2efd796 with an extra dash for mtb_scale=6.

![2021-06-30-234716](https://user-images.githubusercontent.com/3856586/124035941-8cf8c900-d9fd-11eb-9654-488b08c46a6a.png)
