### ISSUE TITLE
do the tags cycleway:bicycle=yes|designated get used?

### ISSUE THREAD

**Issue by joshinils** [cyclosm/cyclosm-cartocss-style#588]
Essentially what I'm asking is, do any of these tags get used?

[`cycleway:right:bicycle`](https://taginfo.openstreetmap.org/keys/cycleway%3Aright%3Abicycle#values)
[`cycleway:left:bicycle`](https://taginfo.openstreetmap.org/keys/cycleway%3Aleft%3Abicycle#values)
[`cycleway:both:bicycle`](https://taginfo.openstreetmap.org/keys/cycleway%3Aboth%3Abicycle#values)
[`cycleway:bicycle`](https://taginfo.openstreetmap.org/keys/cycleway%3Abicycle#values)
[`cycleway:right:lane`](https://taginfo.openstreetmap.org/keys/cycleway%3Aright%3Alane#values)
[`cycleway:left:lane`](https://taginfo.openstreetmap.org/keys/cycleway%3Aleft%3Alane#values)
[`cycleway:both:lane`](https://taginfo.openstreetmap.org/keys/cycleway%3Aboth%3Alane#values)
[`cycleway:lane`](https://taginfo.openstreetmap.org/keys/cycleway%3Alane#values)

All of these can say whether one may (or choose not to) use the cycleway, or is legally obligated to use the cycleway i.e. by way of [signage](https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:237).

**Comment by Phyks** [comment]
I don't see anything in the OSM wiki related to `cycleway:left|right|both:bicycle` tag. This tag has an overwhelming number fo `designated` values which seem definitely redundant to me at first sight.

Not sure about the precise features you are talking about, but I guess this is about exclusive/advisory cycle lanes? We had some feedbacks about it from Germany https://github.com/cyclosm/cyclosm-cartocss-style/issues/173 and have a related open issue https://github.com/cyclosm/cyclosm-cartocss-style/issues/514.

**Comment by joshinils** [comment]
I live in Germany.
the distinction would be that it is not mandatory to use cycleways without signage.
so, the value I pertain to is `*=designated` and `*=yes` (every existing cycleway would be yes by default, so realistically no one would need to tag that).
specifically for `cycleway:bicycle=designated` this would make sense to visualize somehow since I can not (legally) choose not to use a cycleway.

As I understand the legend, the darker shade of blue (Separate cycleway) and a lighter shade of blue (Path designated for bicycles.) mean the _same_ thing to me, a space made for cyclists.
I would distinguish separate as a lane on the street _or_ track on the sidewalk, that is currently shown with the dashed property of a line.
I would also distinguish the mandatory use of the infrastructure provided. To me, the word designated means it is mandatory to use it by way of signage.

`cycleway=lane` means dashed line,
`cycleway:bicycle=designated` means dark blue line
So the tags `cycleway=lane` + `cycleway:bicycle=designated` means a dashed dark blue line.
However a `cycleway=track` would be light blue by default (and not dashed).

For reference, https://www.openstreetmap.org/way/876051943 is drawn in green, since it is tagged as `sidewalk:both:bicycle=yes`

Also, If I map a `cycleway=track` as a separate way, it would get these tags:
`highway=footway`+ `footway=sidewalk` + `bicycle=yes` + `segregated=yes|no` + `oneway:bicycle=yes`
for example: https://www.openstreetmap.org/way/931903143
Here, the `bicycle=yes` means that is not mandatory to use it (no signage), but allowed since it exists. 
This way gets drawn in green, not blue as if it was tagged on the road's way.

**Comment by Florimondable** [comment]
> I would also distinguish the mandatory use of the infrastructure provided. To me, the word designated means it is mandatory to use it by way of signage.

I'm sorry but designated doesn't means its mandatory to use it.
use_sidepath should be used instead https://wiki.openstreetmap.org/wiki/Compulsory_use_of_parallel_way

**Comment by joshinils** [comment]
> > I would also distinguish the mandatory use of the infrastructure provided. To me, the word designated means it is mandatory to use it by way of signage.
> 
> I'm sorry but designated doesn't means its mandatory to use it.
> use_sidepath should be used instead https://wiki.openstreetmap.org/wiki/Compulsory_use_of_parallel_way

sure, but how else can i convey this on a separately mapped way? how do i say this if its a mandatory lane on the street?

---
https://wiki.openstreetmap.org/wiki/Tag:access%3Dofficial says
> For compulsory ways use `bicycle=designated` on the cycleway affected and tag `bicycle=use_sidepath` on the highway which the cyclist should not use.

**Comment by joshinils** [comment]
the difference is, that a separately mapped cycleway as part of a footway (with` segregated=yes`) gets drawn in green, whereas with the tagging as part of the road way it always gets drawn in blue unless it is tagged as `sidewalk:right:bicycle=yes`.
example: https://www.cyclosm.org/#map=20/52.61990/13.31372/cyclosm_live
![image](https://user-images.githubusercontent.com/34302971/125509720-6277bdde-33e7-4600-b6cf-a723c3bd7f57.png)
the infrastructure doesn't change at the intersection, only the way the cycleway is tagged, north as a separate way, south as part of the street:
the [north](https://www.openstreetmap.org/way/961409428#map=20/52.62045/13.31358) has these tags:

|Tags
| bicycle  yes 
|foot  yes 
|footway  sidewalk 
|highway  footway 
|is_sidepath  yes |oneway:bicycle  yes segregated  yes surface  paving_stones

**Comment by Florimondable** [comment]
Use bicycle=designated to render this footway in blue.

**Comment by joshinils** [comment]
> Use bicycle=designated to render this footway in blue.

But it isn't, a cyclist is merely allowed to use it, so `bicycle=yes` is the correct tag, for `bicycle=designated` it needs a sign like:
<img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Zeichen_237_-_Sonderweg_Radfahrer%2C_StVO_1992.svg" width="50" />, <img src="https://upload.wikimedia.org/wikipedia/commons/0/08/Zeichen_240_-_Gemeinsamer_Fu%C3%9F-_und_Radweg%2C_StVO_1992.svg" width="50" /> or <img src="https://upload.wikimedia.org/wikipedia/commons/2/26/Zeichen_241-31.svg" width="50" />
Here, there exists only a segregated cycleway on the sidewalk, which thus permits cycling there.
The wiki https://wiki.openstreetmap.org/wiki/DE:Tag:bicycle%3Ddesignated says to use `designated` for cycleways with this signage, `yes` for ones without, it is a legal distinction.

**Comment by Phyks** [comment]
I don't get your distinction between designated and yes. Is it some German-specific tagging?

As per https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Ddesignated,

> bicycle=designated is applied where cycling is not only legal, but object is explicitly designated for use by cyclists. Note that in many cases it is not necessary to tag it explicitly as it is implied by highway=cycleway or tags such as cycleway:both=lane.

> bicycle=yes is applicable where it is necessary to mark that cycling is legal, but there is no explicit designation for use by cyclists. 

This has nothing to do with the mandatory use of the way by bicycle, but purely with the design of the object. AFAIK, access restrictions (including mandatory use) should be tagged with other tags such as use_sidepath.


From the tagging description, I understand that:

* North of the intersection, it is a footway with a segregation between bicycle and pedestrians. From my tagging experience in OSM, `bicycle=yes` and `segregated=yes` seems a bit contradictory (I expect that if there are segregated spaces, then the object is explicitly meant for bikes, even though it could be a very bad cycleway in practice).
* South of the intersection, there are a sidewalk on both sides as well as a cycle track on both sides. Then, the render is correct here, this is rendered as a cycle track. 

Now, I understand that the object should be the same on both sides of the intersection. There is https://taginfo.openstreetmap.org/keys/sidewalk%3Abicycle#values for this purpose, which is not very much used around.

This is basically case S3 here https://wiki.openstreetmap.org/wiki/Bicycle, but the "implied" description seems to ambiguous to me to be efficiently rendered and distinguished from a regular cycle track on both sides.

**Comment by joshinils** [comment]
> `bicycle=yes` is applicable where it is necessary to mark that cycling is legal, but there is no explicit designation for use by cyclists.

By my understanding, "explicit designation" would be a sign.

---
Yes, it is somewhat a German thing.
The german version of the wiki states:
> Das Merkmal `bicycle=yes` hat eine ähnliche Bedeutung, wird aber verwendet, wenn der Weg nicht ausgeschildert ist. Radfahrer können vorkommen, ohne besondere Berücksichtigung dieser Verkehrsgruppe. 
Google translate:
> The feature `bicycle=yes` has a similar meaning, but is used when the route is not signposted. Cyclists can occur without special consideration of this traffic group. 

Meaning, no sign, but cycling permitted -> `bicycle=yes`, special sign -> `bicycle=designated`.

The problem is sort of a missing tag for "designated, but not mandatory" for which here we use `bicycle=yes`, and there is no "mandatory" tag, so we use `bicycle=designated` if there is such a sign.

Another problem is that with not separately tagged ways I can only say, there is a cycleway, and whether one needs to use it or not via use_sidepath.
(How would i tag that the cycleway is segregated from a sidewalk? how if it is right beside it but segregated via different colour of paving stones?)

However, with a separately mapped cycleway (the sidepath) I can not say that it is a _mandatory_ sidepath (`is_sidepath=yes` specifies something else). I can only specify this on the road-way via `bicycle=use_sidepath`, which requires a sign and makes its use mandatory and marks the road as `bicycle=no`. The negative of which is `bicycle=yes` which noone tags since it is the default.

The sidepath without a sign is mapped as a `highway=footway` + `footway=sidewalk` + `bicycle=yes` + `oneway:bicycle=yes` since I am legally allowed to use it. Since this is directly beside the sidewalk this is not mapped as a separate way, and thus this also gets `segregated=yes`.
If it has a sign, for example <img src="https://upload.wikimedia.org/wikipedia/commons/2/26/Zeichen_241-31.svg" width="50" />, then it would be `highway=path` + `bicycle=designated` + `oneway:bicycle=yes` + `foot=designated` + `segregated=yes` + `traffic_sign=DE:241`.

---

> North of the intersection, it is a footway with a segregation between bicycle and pedestrians. From my tagging experience in OSM, bicycle=yes and segregated=yes seems a bit contradictory (I expect that if there are segregated spaces, then the object is explicitly meant for bikes, even though it could be a very bad cycleway in practice).

It is meant for bikes, explicitly so, but that is about it, no other standard (which a traffic sign needs) are met, like minimum width, surface quality (i.e. `smoothness`) or with what it is paved (i.e. `surface`).

---

> This is basically case S3 here https://wiki.openstreetmap.org/wiki/Bicycle, but the "implied" description seems to ambiguous to me to be efficiently rendered and distinguished from a regular cycle track on both sides.

Yea, but the cycleway is on the inside, the footway on the outside...

---

So by my understanding this means:
`highway=road` + `cycleway=track` means a green line beside the road.
`highway=road` + `cycleway=track` + `bicycle=use_sidepath` means a blue line beside a grey road.

**Comment by Phyks** [comment]
I'm sorry, I'm lost in the discussion and issue here.

I agree with your tagging examples from https://github.com/cyclosm/cyclosm-cartocss-style/issues/588#issuecomment-890410963. However, I do not see the link with the original message of the issue regarding `cycleway:*:bicycle=yes`.

I cannot find any wiki reference for these and their usage seems to indicate they are not popular enough to get a proper render.
