### ISSUE TITLE
One bike parking dot is  missing on zoom 18 (but its number is present)

### ISSUE THREAD

**Issue by tdelmas** [cyclosm/cyclosm-cartocss-style#589]
On https://www.cyclosm.org/#map=18/48.82225/2.41662/cyclosm 

![image](https://user-images.githubusercontent.com/1955774/124776244-932bff80-df3f-11eb-94d1-744d0ca53212.png)

The "4" in the middle of the screenshot is not a street number, but a bike rack.

Others around it are displayed correctly: 
![image](https://user-images.githubusercontent.com/1955774/124776546-d25a5080-df3f-11eb-8d35-dfd67ade44a0.png)

On zoom out (17) is ok:
![image](https://user-images.githubusercontent.com/1955774/124776399-b48ceb80-df3f-11eb-9698-a2de4b05a2b8.png)

And zoom (19) in is also ok:

![image](https://user-images.githubusercontent.com/1955774/124776457-c1114400-df3f-11eb-9abb-987cd826fedc.png)

And it's tags:
```
access=yes
amenity=bicycle_parking
bicycle_parking=stands
capacity=4
covered=no
fee=no
```

are similar to the others around (the one with 6 in the same street on the top right for exemple):
```
access=yes
amenity=bicycle_parking
bicycle_parking=stands
capacity=6
covered=no
fee=no
```

**Comment by Phyks** [comment]
This is basically an occurrence of https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L2049-L2058 and should be solved the same way.

**Comment by gwater** [comment]
This appears to be fixed now, screenshot taken at Zoom level 18 today

![Screenshot 2024-02-28 at 16-26-17 OpenStreetMap](https://github.com/cyclosm/cyclosm-cartocss-style/assets/123790/a79e9a68-109c-4371-b037-0f69d97c2242)
