### ISSUE TITLE
Render cyclsosm in a javascript/ react application as a tile layer in Windows

### ISSUE THREAD

**Issue by datasetsk** [cyclosm/cyclosm-cartocss-style#591]
The application is great. But is there any way to run the application in java script, like accessing open layer tiles? Is there any documentation available explaining how to use this in a web/ mobile application while developing in Windows operating system as existing documentation only supports Linux?

**Comment by Phyks** [comment]
As mentioned in the info popup on cyclosm.org :

A Tile Map Service is available at <code>https://{s}.tile-cyclosm.openstreetmap.fr/[cyclosm|cyclosm-lite]/{z}/{x}/{y}.png</code> under a <a href="https://operations.osmfoundation.org/policies/tiles/">fairuse tile policy</a>.

Feel free to use them if your application meets the fairuse tile policy. You can use Leaflet in Javascript for example https://leafletjs.com/examples.html.
