### ISSUE TITLE
Render heritage ?

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#597]
As a tourist I can find it usefull to know where are the place nearby which worth a visit.
So may be (this is an open request) we could render heritage POI.
May be we shouldn't if it clutter the map.

heritage=1 for international,
may be also heritage=2 for national level.

https://wiki.openstreetmap.org/wiki/Key:heritage

http://gk.historic.place/historische_objekte/l/fr/index.html

**Comment by Phyks** [comment]
osm.org does not render heritage either.

I would expect these to be covered by the `tourism` and `historic`  tags, see https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/views.sql#L198-L210. Do you have an example where such an heritage object was lacking?

**Comment by Florimondable** [comment]
Heritage is more about the quality of the POI than its type ;)
