### ISSUE TITLE
Render relief

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#6]
There should be a render of relief and gradient of the streets, even in urban area. Not sure what the best render option could be? Maybe hillshades as overlays?

**Comment by Phyks** [comment]
Useful links for this:

https://tilemill-project.github.io/tilemill/docs/guides/terrain-data/ and https://github.com/abyrd/velosm#elevation

**Comment by Phyks** [comment]
Actually, we can probably directly use https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/HOWTO_DEM.md. Note that relief data for the entire world should be about 500GB apparently.

**Comment by Phyks** [comment]
First basic version of hillshades based on the OpenTopoMap code is available in https://github.com/Phyks/cyclosm-cartocss-style/commit/b0e5c889a5e816ece0bdf8c1417be1baeeff08f7.

I have two versions, not sure which one is better.

First option is 

![1](https://user-images.githubusercontent.com/3856586/53702999-18052c80-3e0d-11e9-9ecd-6ed00aee0839.png)

with a very strong hillshades overlay.

Second option is 

![2](https://user-images.githubusercontent.com/3856586/53703004-22bfc180-3e0d-11e9-873c-c4d804c07764.png)

using the OpenTopoMap approach of redrawing landuse on top of hillshades to make them softer.

What do you think?

**Comment by Florimondable** [comment]
Look great !

Not sure to understand how it's rendered.
First option : render the map then add the shaded texture, so everything is shade (building, names, land...) ?
Second option : render the landuse, add the shaded texture, render the landuse, render other layers ?

For the result I prefer the first option as the contrast is higher and even in the city we can see the relief.
Eitherway we must able to see the relief in the city, it's one of the issue with opentopomap.

**Comment by Phyks** [comment]
First option is without the `landuse_over_hillshade` layer (https://github.com/Phyks/cyclosm-cartocss-style/commit/b0e5c889a5e816ece0bdf8c1417be1baeeff08f7#diff-2d6c6d06f63a6fab47286addedefc335R148). Just draw the landuse, put hillshades on top, draw the rest on top.

Second option is the full commit https://github.com/Phyks/cyclosm-cartocss-style/commit/b0e5c889a5e816ece0bdf8c1417be1baeeff08f7. Draw the landuse, draw hillshades on top and redraw the landuse in a lighter way on top of it.

This is what OpenTopoMap is doing, but I'm not convinced this is really useful so far https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/opentopomap.xml#L183-L201.

**Comment by Phyks** [comment]
Fixed :)
