### ISSUE TITLE
render bicycle=permissive footway like bicycle=yes footway

### ISSUE THREAD

**Issue by matkoniecz** [cyclosm/cyclosm-cartocss-style#602]
Effect is basically the same in practice (not sure is right of way in UK considered as important part?), but `highway=footway` `bicycle=yes` has special rendering and `highway=footway` `bicycle=permissive` no.

See https://www.openstreetmap.org/way/973317334
![screen](https://user-images.githubusercontent.com/899988/136281307-bc2dae1a-a09d-43c2-8604-0e928f57e16a.png)

See https://www.openstreetmap.org/way/26484615

![screen01](https://user-images.githubusercontent.com/899988/136281354-966ada5f-32fc-484c-a900-dff215b25d12.png)

(rendering changes on edge of park as `bicycle=yes` is result of park rules)

--------------------------

Triggered by https://www.facebook.com/groups/osmpolska/posts/4520494097994005/

**Comment by michaelblyons** [comment]
I also would like this.

**Comment by Phyks** [comment]
Should be done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/9ff385ccca6ec2c5257fbac5db3f5bc5ec349ef9.
