### ISSUE TITLE
Document force tile refresh method

### ISSUE THREAD

**Issue by jidanni** [cyclosm/cyclosm-cartocss-style#605]
Document force tile refresh method somewhere,
perhaps on https://wiki.openstreetmap.org/wiki/CyclOSM , as
simply adding ["/dirty"](https://help.openstreetmap.org/questions/1049/how-to-trigger-a-repaint-for-a-specific-osm-map-tile) doesn't work!

**Comment by Phyks** [comment]
The OSM database behind CyclOSM is tracking minute diffs. The tiles are rendered ASAP, with very small delay from live OSM.

On https://www.cyclosm.org/ there is a "cyclosm-live" alternative which serves tiles directly for contributors. The rest of the CyclOSM maps around have an extra step of caching. Then, cache invalidation is best effort, and at most 3 days.

Weekly cache invalidation is valid only for pre-computed zoom levels (zoom <= 12).
