### ISSUE TITLE
cyclosm layers not showing

### ISSUE THREAD

**Issue by limex** [cyclosm/cyclosm-cartocss-style#608]
Hi,

these layers dont show up:
https://www.cyclosm.org/#map=15/47.0597/15.4817/cyclosm_be
https://www.cyclosm.org/#map=15/47.0597/15.4817/cyclosm_live
https://www.cyclosm.org/#map=15/47.0597/15.4817/cyclosm

While this is working:
https://www.cyclosm.org/#map=15/47.0597/15.4817/opentopomap

Please fix. Thanks in advance.

**Comment by Phyks** [comment]
There is an ongoing issue on our hoster. Tracked at https://github.com/osm-fr/infrastructure/issues/333

**Comment by cquest** [comment]
CyclOSM tiles are back !
