### ISSUE TITLE
Add bike-car wash

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#61]
People doing mountain bike in the mud like to wash their bike in a car-wash amenity
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_wash

Should use only ones with automated=no ?

**Comment by Phyks** [comment]
:+1: for limiting to `automated=no` only.

**Comment by Florimondable** [comment]
I'd say render always car_wash, and if automated=no add a bicycle_friendly graphic to it.
