### ISSUE TITLE
Areas identified in water not useful for biking

### ISSUE THREAD

**Issue by utagawal** [cyclosm/cyclosm-cartocss-style#611]
Some areas distinguished in water are not need at certain zoom levels (see screenshot)

![image](https://user-images.githubusercontent.com/16464382/146782398-12a72117-7751-43e7-9ae4-77693e584c3b.png)

**Comment by Phyks** [comment]
These are national park and marine reserves. We cannot simply exclude them from water and I think they are useful in the main land / along the coast.

Some examples I have in mind are

https://www.cyclosm.org/#map=10/50.5379/1.6507/cyclosm

or https://www.cyclosm.org/#map=10/49.1269/1.9556/cyclosm

as you might want to look them up for planning multi-days trips (to pass more days in scenic places).
