### ISSUE TITLE
Misconfigured TLS certificates for Cycleosm.org, Live tiles not working

### ISSUE THREAD

**Issue by pedroaugustosmribeiro** [cyclosm/cyclosm-cartocss-style#614]
Please regenerate the Let's Encrypt certificates, the main page has an expired certificate, and the Live tiles and BE tiles are not working either, because their tile server (dev.a.tile.openstreetmap.fr) is not listed as an DNS alt name at the presented certificate, so the browser refuses to load.

**Comment by Phyks** [comment]
I cannot reproduce on my side, certificate is valid and everything works as expected. Please provide more details / steps to reproduce.

**Comment by pedroaugustosmribeiro** [comment]
![image](https://user-images.githubusercontent.com/16151069/155210325-d765f686-db37-4e01-aa66-f2e6277b687d.png)
[www.cyclosm.org-1645560555070.log](https://github.com/cyclosm/cyclosm-cartocss-style/files/8119840/www.cyclosm.org-1645560555070.log)
![image](https://user-images.githubusercontent.com/16151069/155211062-4aba5d88-c480-4345-ab4b-a83e733d6ce3.png)

**Comment by pedroaugustosmribeiro** [comment]
[dev.cycleosm.cer.txt](https://github.com/cyclosm/cyclosm-cartocss-style/files/8119867/dev.cycleosm.cer.txt)
[cycleosm.cer.txt](https://github.com/cyclosm/cyclosm-cartocss-style/files/8119868/cycleosm.cer.txt)

**Comment by Phyks** [comment]
Well, current certificate has been emitted on Tue, 04 Jan 2022 18:55:45 GMT by Lets'Encrypt and is valid until Mon, 04 Apr 2022 18:55:44 GMT for cyclosm.org and www.cyclosm.org. I don't know why you are getting such an old certificate.

Additionnally, cyclosm.org is served through [Github Pages](https://github.com/cyclosm/cyclosm-website/tree/gh-pages) so they are managing SSL certificates on their side without any control for us.

**Comment by pedroaugustosmribeiro** [comment]
It might be a caching problem but the main page still loads anyways. However the Live layer doesn't loads at all, because the certificate for osm14.openstreetmap.fr doesn't includes dev.(a,b,c).tile.openstreetmap.fr, if I try to continue anyway manually loading a single tile png, the request timeouts with 502 bad gateway.

**Comment by Phyks** [comment]
So,

* Belgian layer is provided by Champs-Libres, following https://www.champs-libres.coop/blog/post/2020-09-17-cyclosm/. They handle their own hosting and only serve tiles for the belgian territory (404 everywhere else).
* Live layer has been discontinued when we had server issues recently (https://github.com/cyclosm/cyclosm-cartocss-style/issues/606). I'll check with the French local chapter which is kindly hosting us if we could put it back online. In the meantime, I'm disabling it on the website.

**Comment by pedroaugustosmribeiro** [comment]
Thank you
