### ISSUE TITLE
What is the license of generated tiles?

### ISSUE THREAD

**Issue by matkoniecz** [cyclosm/cyclosm-cartocss-style#615]
I admit that I am not 100% sure how licensing of produced work works exactly.

How https://www.cyclosm.org/images/social_media.png file is licensed? I want to fix and describe licensing status of https://wiki.openstreetmap.org/wiki/File:CyclOSM.png

**Comment by Phyks** [comment]
Hi! Indeed, there is no clear license for this file. I think we could license it under CC BY-NC unless someone expresses concerns about this.

**Comment by matkoniecz** [comment]
1) Is it possible to give such license to when you generate from ODBL data? (no idea, personally I licensed my styles as CC0 to avoid problems, resulting in data having ODBL-licensed map data) 

2) If CC is OK and preferred then I would recommend CC-BY-SA-4.0. CC BY-NC has two problem

- not specific, you need also license version
- NC is poorly defined and in many cases it is unclear can it be applied (for example, is it fine to use it in StreetComplete as an illustration)
- NC materials cannot be used in Wikimedia Commons and likely should not be/will not be usable at OSM Wiki

**Comment by Phyks** [comment]
1/ ODBL is about the data / dataset reuse, not derived works such as tiles / social media cards. I do not see anything in the ODBL license preventing from licensing produced work of art under a license such as CC or anything else.

2/ Although I am very supportive of having CyclOSM images published under as less restrictive as possible licenses, I do feel like a too large CC license could be an issue for something as close to a graphic identity as a social media card : I'd fear the risk of mixing what is officially endorsed by CyclOSM and what is simply a byproduct + we need to be especially clear given the commercial interests which might reside in OSM + bike. My personal preference would be to have a CC BY-NC license (or CC BY-NC-SA, but keeping NC) and handling borderline / question about use case on a one to one basis (e.g. obviously StreetComplete would be welcome to use the logo in the app and we could have a one-to-one written assessment that this is a fine usage).

**Comment by matkoniecz** [comment]
It is also about use on Wikimedia Commons/Wikipedia (which excludes noncommercial licenses).

It is also about OSM Wiki, though here policy is only being planned, see https://wiki.openstreetmap.org/wiki/Talk:Wiki#Designing_policy_for_handling_files_without_clear_license

**Comment by matkoniecz** [comment]
> added onto Wikipedia

Only on ones allowing fair use, primarily English Wikipedia.

Though some logos are simple enough to not qualify for copyright protection.

**Comment by matkoniecz** [comment]
> I think we could license it under CC BY-NC unless someone expresses concerns about this.

Which version exactly? CC BY-NC 4.0? Is 

![screen01](https://user-images.githubusercontent.com/899988/173178544-d5e0899a-6bbd-49fb-bbb5-54cb70aebada.png)

licensed under the same license?

Asking as it is used by StreetComplete and currently is listed there as `ic_link_cyclosm.xml            CC-BY-SA          Lucas Verney` which is both without version and mismatching license stated here.
