### ISSUE TITLE
Rendering of intersection names

### ISSUE THREAD

**Issue by Mykolos** [cyclosm/cyclosm-cartocss-style#617]
Many thanks to the development team for your hard work. 👍

I was wondering if you have considered including traffic signal names in the rendering of maps? These are often used for navigation in Japan, where minor street names are not usually posted on signs (and are generally unknown to the average person). I think including these signal names at intersections would make route planning with Cycleosm easier in Japan. 

FYI:
**Named traffic signals/traffic signal systems (Japan... )**
https://wiki.openstreetmap.org/wiki/Tag:highway=traffic_signals

Cheers.

**Comment by Phyks** [comment]
This issue was closed because it has been inactive for more than 6 months.
