### ISSUE TITLE
Start rendering of cycleway at the edge of the road

### ISSUE THREAD

**Issue by mangerlahn** [cyclosm/cyclosm-cartocss-style#619]
Thank you very much for this map!

One thing that nags me is the rendering of merging cycleways and other highways. The cycleway is drawn to the center of the highway lane. I think it would be better if the rendering stopped at the edge of a highway. Even better would be a seamless continuation of separate cycleway and `cycleway:lane/track`. I am not too familiar with Carto and am therefore not sure whether this would be possible to do, so I am curious to hear your thoughts on this.

![Bildschirmfoto 2022-05-05 um 08 45 45](https://user-images.githubusercontent.com/11056766/166874459-7a51fddc-9b33-48a5-b3f9-804fab1aebc5.png)
![Bildschirmfoto 2022-05-05 um 08 49 01](https://user-images.githubusercontent.com/11056766/166874690-4fccd616-26d2-4113-93d8-29c65e15b460.png)

**Comment by Phyks** [comment]
Hi,

I understand this can be visually annoying, but it is quite difficult to make it better (or would require much more computations to be done):

1/ One option would be to display cycleways layer below roads layer. This would achieve the visual effect of having the road blocking the cycleway (and then cycleway starting at the edge) at the cost of missing many cycleway features whose geometry would be hidden by the road (think separate cycleway geometry tagged too close to a large road).
2/ Another option would be to play with offset to effectively offset the end cycleway point to the edge of the road. This is road-dependent and would require cross-computations between road layer and cycleways layer.
