### ISSUE TITLE
Investigate amenities and shops with multiple values

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#62]
https://www.openstreetmap.org/node/25214653 is not rendered as a `shop=convenience` also these should be rendered.

The issue is likely to be due to the multiple values in the `shop` tag and `osm2pgsql` not separating them for import. This should be investigated more in depth.

**Comment by Phyks** [comment]
Checking at the database created by `osm2pgsql`, semicolon-separated values are added as is (so that `shop` value is `convenience;gas`) in the example given. I had a look at `openstreetmap-carto` and they just have the same configuration in database, then ignoring these edge cases (but they are actually as being an `amenity=fuel`).

First option would be to do extra filtering to match these `;` separated values in the SQL queries, but this is likely to result in a lot of overhead.

Second option would be to discard them all together, which is not nice as well.

Looking at [taginfo](https://taginfo.openstreetmap.org/keys/shop#values), the only such combination (in important number) for `shop` or `amenity` is the one in the example: `shop=convenience;gas`.

![screenshot_2019-02-20 shop cles openstreetmap taginfo](https://user-images.githubusercontent.com/3856586/53080406-e761f080-34f8-11e9-8042-9ce583456400.png)


Maybe the best work around would actually to just add this special case and continue to discard other `;`-separated values for tags.

**Comment by Florimondable** [comment]
Agreed, though this workaround should not be use often ;)

**Comment by Phyks** [comment]
https://www.openstreetmap.org/node/1690268656 gets rendered as 
![screenshot_2019-02-20 cyclosm kosmtik](https://user-images.githubusercontent.com/3856586/53086364-3dd52c00-3505-11e9-93e7-8f5d9fb2f2bc.png)

https://www.openstreetmap.org/node/25214653 gets rendered as 
![screenshot_2019-02-20 cyclosm kosmtik2](https://user-images.githubusercontent.com/3856586/53086391-4fb6cf00-3505-11e9-8ee2-c59bdec25ce5.png)

The combined convenience + compressed_air icon will need some rework in the future though.
