### ISSUE TITLE
Render more motor_vehicle=* tags

### ISSUE THREAD

**Issue by kaneap** [cyclosm/cyclosm-cartocss-style#622]
Rendering roads which limit motor vehicle access can help a cyclist find routes which are relatively free of motor traffic. Specific tags that may be rendered are motor_vehicle=destination,agriculture,forestry,delivery,permit. Combinations of these may also be considered (the wiki documents motor_vehicle=agricultural;forestry).

Possible renderings may be a dashed version of the current motor_vehicle=no rendering.

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/7c97017eecd055b83d96304c4e9ae3531d86b63b.
