### ISSUE TITLE
Suggestions for handling contour-lines better

### ISSUE THREAD

**Issue by firsttest12** [cyclosm/cyclosm-cartocss-style#624]
Basically if compare with a map company (Ordanance Survey) that does things well, IMHO a few things stand out:

https://getoutside.ordnancesurvey.co.uk/guides/understanding-map-contour-lines-for-beginners/

1) The contour line should not strike out the number!

2) Numbers need to be bigger;

3) Numbers need to be in a dense/solid colour;

4) In many cases it is not necessary to put numbers on every single line - that declutters the map;

Thanks ;)

**Comment by Phyks** [comment]
Hi,

Contours are really difficult to handle properly to not clutter the map but still provide meaningful and readable insights. This is particularly difficult with a map such as CyclOSM which is entirely computer-generated (without any manual refinement). 

Some work was started in #567, maybe we can continue with the discussion there? Happy to take any suggestions tailored to CyclOSM current render or patches. :)
