### ISSUE TITLE
`fixme:` interpreted as a tag

### ISSUE THREAD

**Issue by tdelmas** [cyclosm/cyclosm-cartocss-style#631]
In the intersection https://www.openstreetmap.org/#map=20/48.84565/2.39560&layers=Y

There are the following tags: 
```
fixme:asl=ajout d'un éventuel Sas cyclable à côté du feu : cycleway=asl
fixme:bicycle:give_way=ajout d'un éventuel Cédez-le-passage cycliste au feu : type=restriction ; restriction:bicycle=give_way
highway=traffic_signals
```

And the render is: 

![image](https://user-images.githubusercontent.com/1955774/188194303-04814776-44fa-48c3-a8a0-87dba3f0de4c.png)

So I guess that 
https://github.com/cyclosm/cyclosm-cartocss-style/blob/ca890ae0713a0d5c37f360950cffcb168dab9278/project.mml#L1515

misinterpreted the `fixme:bicycle:give_way` tag as a `bicycle:give_way`?

**Comment by Phyks** [comment]
The node is part of a valid `bicycle:give_way` relation: https://www.openstreetmap.org/relation/7692084#map=18/48.84642/2.39567&layers=Y. I guess the fixme on the node should be removed, but the render seems correct then?

**Comment by tdelmas** [comment]
You're correct, sorry!
