### ISSUE TITLE
Render cycleway:surface when available, default to surface

### ISSUE THREAD

**Issue by kaneap** [cyclosm/cyclosm-cartocss-style#632]
When a segregated way has tags such as cycleway:smoothness=*, cycleway:surface=*, etc. these tags should be used to determine the cyclability rendering of the way. See https://wiki.openstreetmap.org/wiki/Key:cycleway:surface

**Comment by Phyks** [comment]
If you mean the cyclability rendering of the **main** way (the one bearing the `highway != cycleway` tag) this is quite impossible with our database structure. We simply have no mean to match say a `highway = primary` with its nearby `highway=cycleway` if tagged separately, so no interaction is possible between the two objects.

**Comment by kaneap** [comment]
No, I meant on a segregated way. 
For example `highway=path`, `bicycle=designated`, `foot=designated`,`segregated=yes`, `footway:surface=sett`, `cycleway:surface=asphalt`

**Comment by Phyks** [comment]
Ok, got it. Sure, we could render `cycleway:surface` given its [usage](https://taginfo.openstreetmap.org/keys/cycleway%3Asurface). I'm updating the issue title to reflect this.

**Comment by Phyks** [comment]
Merging with #506
