### ISSUE TITLE
Label trunk_link as not allowed for cyclists

### ISSUE THREAD

**Issue by Stuxburg** [cyclosm/cyclosm-cartocss-style#633]
At least in Germany it is not allowed to cycle on trunk_link. On the map it is not marked as forbidden.

**Comment by kaneap** [comment]
Perhaps the trunk link should be tagged with `motorroad=yes`?

**Comment by ziemek99** [comment]
> Perhaps the trunk link should be tagged with `motorroad=yes`?

It's unnecessary IMO. If `highway=trunk` roads are inaccessible to cyclists, then by logic all roads leading **directly** (w/o intersections with other roads) to and from them should be rendered as inaccessible, too. `highway=trunk_link` perfectly meets those criteria.

**Comment by kaneap** [comment]
`highway=trunk` isn't necessarily inaccessible to cyclists. Note there are at least two interpretations of `highway=trunk`:
1. An expressway (similar to motorways but built to power standards e.g. the yellow Autobahns in Germany) this interpretation is prevalent in Europe.
2. A road providing long distance connections (serving a similar role to a motorway but might only be a two lane rural highway) This interpretation is prevalent in the US and Russia (and probably other sparsely populated regions)

**Comment by Phyks** [comment]
We stick as much as possible to the [worldwide default access restrictions](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Worldwide). That is because we cannot account for local specificities in the style. 

`highway=trunk` and `highway=trunk_line` are both considered bikeable there.
