### ISSUE TITLE
Add cyclosm to NextGIS/QMS for QGIS + ArcGIS 

### ISSUE THREAD

**Issue by ChrizKu** [cyclosm/cyclosm-cartocss-style#634]
Do you want to add the layer to [Quick Map Services](https://qms.nextgis.com/about) so that it's directly available in GIS Software?
>  https://a.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png
_@Phyks in https://github.com/cyclosm/cyclosm-cartocss-style/issues/543#issuecomment-804847763_

**Comment by Phyks** [comment]
Already done by someone else: https://qms.nextgis.com/geoservices/5526/.
