### ISSUE TITLE
Tile service in Qgis : problem rendering ? 

### ISSUE THREAD

**Issue by REIMSMetropole** [cyclosm/cyclosm-cartocss-style#635]
Hi.

We're trying to configure the cycleOSM tile service for our qgis users who manage transport data (therefore the cycling datas). 

We've tried with the xyz tiles connexion in Qgis and the QuickMapService. 

But what we get is seas (we're in the East of France, the pinks lines are our road graph) : 
![image](https://user-images.githubusercontent.com/5716587/192994947-c395c4b7-3ee2-4aa5-ad2f-c792d18666d9.png)

I've tried to change the CRS (which I've assumed is 3857). Nothing works. 

![image](https://user-images.githubusercontent.com/5716587/192994209-58f0e517-3478-4674-9165-7345e0319451.png)

Are we missing something ? Is there a problem on the xyz server ? 

Thanks in advance.

**Comment by lmagreault** [comment]
Wrong URL.
Try : https://a.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/**{y}**.png instead of https://a.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/**{-y}**.png
