### ISSUE TITLE
cycleway:right=separate not rendered

### ISSUE THREAD

**Issue by fabien1309** [cyclosm/cyclosm-cartocss-style#636]
Hello, 

This is my first post in github, so i hope it will be useful.

In my city (https://www.openstreetmap.org/#map=18/45.76799/3.08074), some users tagged a bike lane with those tags : 

cycleway:right=separate
cycleway:right:oneway=yes

The problem is : Cyclosm doesn't render it.  

Is it a bad way to tag this path? (Looking at https://wiki.openstreetmap.org/wiki/Key:cycleway:right, it looks correct).

Or is it something missing in the list of tags processed by CyclOSM?

Thank you !

**Comment by slasherfun** [comment]
Hi,

cycleway:right=separate means that there is a separately mapped cycleway on the right side of the way: it's mostly used as a hint for routing engines, there's no specific rendering expected.
In your case, I don't see any separate way: that's the missing part for a correct rendering.

If you don't want to map a separate way, use cycleway:right=lane for a reserved lane on the road, or cycleway:right=track for a physically separated track next to the road.
