### ISSUE TITLE
render barrier=motorcycle_barrier

### ISSUE THREAD

**Issue by ntzm** [cyclosm/cyclosm-cartocss-style#637]
wiki: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dmotorcycle_barrier

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/a15e454f43fefd785017a003c38ea9adde3d04f0 with the same render as a cycle barrier.
