### ISSUE TITLE
Proposal: render cycleway:[left:|right:|both:]segregated:no similar to shared bicycle/foot path

### ISSUE THREAD

**Issue by reinhard-mueller** [cyclosm/cyclosm-cartocss-style#640]
There are cycling lanes which are at the same time used as a sidewalk, like here: https://www.cyclosm.org/#map=19/47.43148/9.66819/cyclosm (tagged with cycleway:right:segregated=no and sidewalk:right:segregated=no). I suggest that in such a case, the lane should be marked with the lighter blue, much like unsegregated shared bicycle/foot paths.

**Comment by kaneap** [comment]
I believe the reason is that it is a "cycleway" and as such is rendered in dark blue (the cycleway color). This issue has been discussed for separate cycleways at #575, but I believe the same principle applies.

The way cyclosm _wants_ you to tag unsegregated sidepaths for pedestrians and cyclists is with `sidewalk:right:bicycle=designated` (but obviously don't start retagging things just to make the render look nice 😄)

**Comment by reinhard-mueller** [comment]
Unfortunately the German-speaking wiki page https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren tells me to use the `cycleway`+`sidewalk` combination.

I think it would be an improvement for CyclOSM if different widely used methods to tag the same actual thing would lead to the same output. So IMHO a `sidewalk` with `:bicycle=designated`, a `cycleway` with `:foot=designated` and a combined `sidewalk`+`cycleway` with `:segregated=no` should all lead to the same result.

**Comment by Phyks** [comment]
This is indeed very close to https://github.com/cyclosm/cyclosm-cartocss-style/issues/575 and these two issues would deserve being tackled together. Writing the code to handle it is quite simple, but getting the logic right for everyone (worldwide) is something much more difficult.


Would anyone involved in these issues have some time to summarize in a table form what is incorrectly handled at the moment? I could imagine something like (taking a non-controversial example here)


| Combination of tags | OSM wiki page indicating this is a valid tagging scheme at scale (e.g. country level) | Current rendering | Expected rendering | Example data                                                        |
|---------------------|---------------------------------------------------------------------------------------|-------------------|--------------------|---------------------------------------------------------------------|
| highway=cycleway    | https://wiki.openstreetmap.org/wiki/FR:Bicycle#Pistes_cyclables                       | Blue designated   | Blue designated    | https://www.openstreetmap.org/way/664615515#map=18/48.85500/2.34239 |
| ...                 | ...                                                                                   | ...               | ...                | ...                                                                 |
|                     |                                                                                       |                   |                    |                                                                     |


Thanks

**Comment by kaneap** [comment]
| Tags | Wiki page | Current Render | Expected Rendering | Example
| --- | --- | --- | --- | --- |
| cycleway=track, cycleway:segregated=yes | [DE:Bicycle/Radverkehrsanlagen kartieren](https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren#Stra%C3%9Fenbegleitende_Wege) | Blue separate | Blue shared | https://www.openstreetmap.org/way/34788915 |
| highway=cycleway, foot=designated, segregated=no | [Bicycle](https://wiki.openstreetmap.org/wiki/Bicycle#Miscellaneous), [Road signs in Belgium/D Mandatory signs](https://wiki.openstreetmap.org/wiki/Road_signs_in_Belgium/D_Mandatory_signs),  [IT:Road_signs_in_Italy](https://wiki.openstreetmap.org/wiki/IT:Road_signs_in_Italy#Segnali_di_obbligo_(Mandatory_signs)), [Cs:Dopravní značky v Česku](https://wiki.openstreetmap.org/wiki/Cs:Dopravn%C3%AD_zna%C4%8Dky_v_%C4%8Cesku#P%C5%99%C3%ADkazov%C3%A9_dopravn%C3%AD_zna%C4%8Dky_(Mandatory_signs)) | Blue separate | Blue Shared | https://www.openstreetmap.org/way/29266382
| highway=cycleway, sidewalk=yes/right/left/both | [NL:Cycleway](https://wiki.openstreetmap.org/wiki/NL:Cycleway)) | Blue separate | segregated cycleway | https://www.openstreetmap.org/way/256591399

The last one may be more contravercial, but IMO the distinction between a segregated cycle/foot path and a cycleway with a sidewalk is rather arbitrary (The Netherlands has lots of cycleways with sidewalks and has no sign for a segregated foot/cycleway afaik)

**Comment by reinhard-mueller** [comment]
Sorry, I don't quite understand the last one: isn't "Blue separate" the indicator for a segregated cycleway? What exactly would you like to have changed here?

**Comment by reinhard-mueller** [comment]
Another thing: in the first one, you meant to write "segregated=no" rather than "segregated=yes", right?

**Comment by reinhard-mueller** [comment]
Thank you for the edits! I think I now agree with the table, but would like to add some more clarification to avoid misunderstandings:

 * First row: cycleway:segregated=no can also be cycleway:left:segregated=no, cycleway:right:segregated=no or cycleway:both:segregated=no (of course depending on which side of the road we're at).
 * Second row: since segregated=no is the default for this case, "segreated=no/(unset)" would be more precise.

I also think that you actually had a valid point with the third, meanwhile deleted row in some way: a cycleway with bicycle=designated should _not_ turn light blue if it has a sidewalk. So I think as a further improvement, we could add "sidewalk=no/(unset)" to the conditions of line 2.

**Comment by kaneap** [comment]
@reinhard-mueller I updated the table to be more specific about cycleway:both/right/left. 

- In terms of the second issue, I don't know if there is any assumed default for segregation with `highway=cycleway`. I think its a better idea to make mappers explicitly tag that there is no segregation for this to be the case (even if there is `foot=designated`)
- The issue of sidewalks on cycleways I decided was a bit out of scope for this pull request.

**Comment by reinhard-mueller** [comment]
> I updated the table to be more specific about cycleway:both/right/left.

Thank you!

>  In terms of the second issue, I don't know if there is any assumed default for segregation with `highway=cycleway`. I think its a better idea to make mappers explicitly tag that there is no segregation for this to be the case (even if there is `foot=designated`)

I think we should not aim to "educate" mappers about what we consider correct mapping, we should rather try to build the map as usefuly as possible based on current tagging. https://wiki.openstreetmap.org/wiki/Key:segregated says "that segregated=no may be safely assumed in at least some cases", so I think segregated being not set in this case should be rendered the same as segregated=no.

>  The issue of sidewalks on cycleways I decided was a bit out of scope for this pull request.

Thinking about this once again, I find that combination of foot=designated and sidewalk=yes actually makes no sense, so I agree to leave this out.

**Comment by kaneap** [comment]
The part that "segregated=no can be assumed in some cases" is somewhat odd, because it's not entirely clear when it can be assumed (and may vary by region). Nonetheless `segregated=no` can probably be assumed here in the majority of cases
