### ISSUE TITLE
Proposal: show bicycle roads in CyclOSM Lite

### ISSUE THREAD

**Issue by reinhard-mueller** [cyclosm/cyclosm-cartocss-style#641]
I very much like of CyclOSM Lite which can be put as an additional layer on top of other maps!

Bicycle roads (bicycle_road=yes) are a very useful element in cycling infrastructure, most of the time it's better, safer and nicer to go than, for example, a cycling lane at the edge of a primary road. I would therefore suggest that they are added to CyclOSM Lite similarly like they are shown on "proper" CyclOSM.

**Comment by Phyks** [comment]
CyclOSM lite was set up quickly after covid outbreak and the need to display cycling overlays on many different maps. CyclOSM developer community is quite small and CyclOSM-lite is basically unmaintained at the moment. It is diverging more and more with current CyclOSM render and is mostly to be considered legacy from a user perspective.

Therefore, I'm closing this one. However, if anyone is willing to make a PR onto the `lite` branch to add support for rendering `bicycle_road=yes`, I'll happily merge it.
