### ISSUE TITLE
Map not showing up on OSM.ORG today

### ISSUE THREAD

**Issue by jidanni** [cyclosm/cyclosm-cartocss-style#643]
Request URL: https://c.tile-cyclosm.openstreetmap.fr/cyclosm/19/438164/225831.png
Request Method: GET
Status Code: 404

**Comment by Phyks** [comment]
Seems the tile are back online.

**Comment by jidanni** [comment]
Broken again.

**Comment by tdelmas** [comment]
The tiles at zoom level 17/18/19 seams to answer 404 very often (most of the time for some areas), making the map completely unusable when zooming.  https://www.openstreetmap.org/#map=19/48.82085/2.41419&layers=Y
![image](https://user-images.githubusercontent.com/1955774/220751177-8fd714e0-41b8-440a-a3d4-9e305b0c19f8.png)

**Comment by Phyks** [comment]
See https://github.com/osm-fr/infrastructure/issues/411, issue with our hosting (provided by OSM-France).

**Comment by tdelmas** [comment]
Thank you for the feedback!

**Comment by Phyks** [comment]
Update on this one, there were a few issues on the tile server, this should be solved by now, up to traffic issues (CyclOSM tile server is handling **a lot** of requests, we are working on tuning performances).
