### ISSUE TITLE
renderd error, simplified-land-polygons-complete-3857.zip.shp doese not exist.

### ISSUE THREAD

**Issue by comichh** [cyclosm/cyclosm-cartocss-style#646]
When I start renderd, I get the error.
sudo -u user renderd -f -c /etc/renderd.conf

renderd[534200]: An error occurred while loading the map layer 'default_cyclosm': Shape Plugin: shapefile '/home/alfred/src/cyclosm-cartocss-style/http://osmdata.openstreetmap.de/download/simplified-land-polygons-complete-3857.zip.shp' does not exist  encountered during parsing of layer 'land-low' in Layer at line 279 of '/home/alfred/src/cyclosm-cartocss-style/style.xml'

**Comment by Phyks** [comment]
See https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md#shapefiles, you need to download the files accordingly and put them in the corresponding folder. Kosmtik can handle it with the following [plugin](https://github.com/kosmtik/kosmtik-fetch-remote).
