### ISSUE TITLE
Postgis Plugin: ERROR:  column "sport" does not exist

### ISSUE THREAD

**Issue by comichh** [cyclosm/cyclosm-cartocss-style#647]
Hi  

I use OSM Data to import to postgresql. Rendered standard png tiles are correct. osm data is downloaded from "https://planet.openstreetmap.org/" 

Origin OSM data does not have column sport,  but your project.mml need to read  column sport. this error occurs when I start renderd , can I ignore it, or how to get column sport? 

error message : 
renderd[650872]: An error occurred while loading the map layer 'default_cyclosm': Postgis Plugin: ERROR:  column "sport" does not exist
LINE 12:     sport
             ^
in executeQuery Full sql was: 'SELECT * FROM (
  SELECT
    ST_Snaptogrid(way, 0 / 4) AS way,
    way_area AS area,
    COALESCE(
      CASE WHEN landuse IS NOT NULL THEN ('landuse_' || landuse) ELSE NULL END,
      CASE WHEN "natural" IS NOT NULL THEN ('natural_' || "natural") ELSE NULL END,
      CASE WHEN leisure IS NOT NULL THEN ('leisure_' || leisure) ELSE NULL END,
      CASE WHEN amenity IS NOT NULL THEN ('amenity_' || amenity) ELSE NULL END,
      CASE WHEN highway IS NOT NULL THEN ('highway_' || highway) ELSE NULL END
    ) AS type,
    sport

**Comment by Phyks** [comment]
How did you import OSM data into postgresql? You should be using osm2pgsql as stated in [the doc](https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md#openstreetmap-data) to ensure you have all the required tables / columns.

Best
