### ISSUE TITLE
Node-network nodes no longer rendering

### ISSUE THREAD

**Issue by kaneap** [cyclosm/cyclosm-cartocss-style#648]
Before, cyclosm would render the node points (tagged with [network:type=node_network](https://wiki.openstreetmap.org/wiki/Tag:network:type%3Dnode_network) + [rcn_ref=*](https://wiki.openstreetmap.org/wiki/Key:rcn_ref)) but this appears to have been broken somehow.

Compare CyclOSM:
![Screenshot 2023-03-13 143807](https://user-images.githubusercontent.com/35740782/226181381-ace72e54-eb28-4cd8-a36e-14ddb33c85d7.png)
with OpenCycleMap:
![Screenshot 2023-03-13 143728](https://user-images.githubusercontent.com/35740782/226181391-9d33d084-9160-4d09-856a-64a4a8c69c78.png)

This example location is located at https://www.openstreetmap.org/#map=18/52.33948/4.84747.

**Comment by Phyks** [comment]
Indeed. This is not a CyclOSM bug, [this node](https://www.cyclosm.org/#map=19/51.98294/5.91253) is correctly rendered.

Your example node is missing from the database used by the cyclosm.org / cyclosm on osm.org render. There might have been an import glitch, I'm double checking with OSM-FR which is providing us hosting.
