### ISSUE TITLE
Footway with bicycle=yes tag is not rendered

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#649]
issue :
a highway with following tags is not rendered at all in cyclosm
- bicycle=yes
- highway=footway
- horse=yes
- surface=gravel

![image](https://user-images.githubusercontent.com/8955390/230638475-ec31b906-c300-4b23-b8cc-e73a0f7d8a76.png)
https://www.cyclosm.org/#map=16/47.2733/-1.8373/cyclosm

![image](https://user-images.githubusercontent.com/8955390/230638689-5460d036-1572-4906-9538-ff4ee2e8db2e.png)
https://www.openstreetmap.org/edit#map=16/47.2733/-1.8373

A footway should anyway be visible in cyclosm (as it can be used by cyclists after dismounting), but footways with bicycle=yes should definitely be made visible. 

Could this be a regression ?

**Comment by kaneap** [comment]
Footways with bicycle=yes are currently rendered (see [this](https://www.openstreetmap.org/way/562554989) for an example). My guess is that something is wrong in the rendering order causing the landuse=meadow to render on top of the footway, thus obscuring it.

**Comment by Phyks** [comment]
I checked and the way in the first message is missing from the hosted database from OSM-FR. Likely a temporary issue with diff updates as others are there. I'll message the issue to osm-fr which is hosting us.
