### ISSUE TITLE
CyclOSM Tileserver down?

### ISSUE THREAD

**Issue by momentmal** [cyclosm/cyclosm-cartocss-style#655]
I noticed CyclOSM is completely gone everywhere I was able to use it, even on https://www.openstreetmap.org/ - anyone has any info, is it planned maintenance or s.th.? 
https://www.openstreetmap.fr/ only shows the classic OSM style instead.

Thanks

**Comment by Phyks** [comment]
Reported https://github.com/osm-fr/infrastructure/issues/490. Please follow this ticket for updates.

**Comment by punyidea** [comment]
I think the tileserver is gone again, but it does work on openstreetmap.org. I cannot access the ones on maps.openrouteservice.org and brouter.

**Comment by punyidea** [comment]
Ok, I was mistaken about brouter, and it seems this is unique to openrouteservice.org. For this reason I think this should stay closed and I will contact ORS directly.
