### ISSUE TITLE
`bicycle_parking=informal` is not rendered

### ISSUE THREAD

**Issue by 05storm26** [cyclosm/cyclosm-cartocss-style#656]
Bicycle parkings tagged with `amenity=bicycle_parking` and `bicycle_parking=informal` are not rendered.

**Comment by Phyks** [comment]
Indeed, not rendered at the moment. 

Usage is in a steady increase but I'd say it is still a bit too confidential for having a render (1k usage worldwide). https://taginfo.openstreetmap.org/tags/bicycle_parking=informal#chronology

**Comment by 05storm26** [comment]
Why is the exact type of the bicycle parking relevant, for rendering?

Shouldn't all `amenity=bicycle_parking` be rendered the same?

It is not like they are currently rendered differently based on the actual type.

**Comment by 05storm26** [comment]
It's interesting. It seems that I was wrong and informal bicycle parkings are rendered but only if they are tagged on nodes. But they are not rendered on ways:

https://overpass-turbo.eu/s/1yLX

Are bicycle_parking amenities tagged on ways, not nodes, rendered? Or they are not currently rendered at all regardless of the type?

**Comment by Phyks** [comment]
True, we do support them on points and polygons but not on ways. 
It might be worth rendering them but I have no idea for a reasonable design :/
