### ISSUE TITLE
 Production rendering

### ISSUE THREAD

**Issue by nicolashmln** [cyclosm/cyclosm-cartocss-style#658]
Is there a way to use the docker image https://github.com/Overv/openstreetmap-tile-server to serve the tiles for production? As I understood kosmtik is more development oriented.

You can use a custom [carto style](https://github.com/Overv/openstreetmap-tile-server/blob/master/README.md#using-an-alternate-style) and I used the `project.mml` of cyclosm but it doesn't really works (event after a few modifications). What about the `NAME_LUA`, `NAME_STYLE` and `NAME_SQL` variables from the images?

But maybe there is another way for production rendering?

Thanks

**Comment by Phyks** [comment]
I dont know these docker files, sorry. We have a docker setup in the cyclosm repo for easier dev, not really production oriented. 

Production setup is dockerless and documented in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md and https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-12/

**Comment by nicolashmln** [comment]
Looks like the install on debian 12 is almost the same as the docker image, it uses this kind of command `osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script ~/src/openstreetmap-carto/openstreetmap-carto.lua -C 2500 --number-processes 1 -S ~/src/openstreetmap-carto/openstreetmap-carto.style ~/data/azerbaijan-latest.osm.pbf` with the `openstreetmap-carto.lua` and `openstreetmap-carto.style` that cyclosm don't have.

Thanks anyway

**Comment by Phyks** [comment]
These files are special styles to import the pbf into postgresql (here style is not render but db schema). CyclOSM consumes a plain osm2pgsql import, no need for extra lua script.

**Comment by Phyks** [comment]
See as well https://github.com/osm-fr/ansible-scripts/tree/master for the ansible that deploys the production architecture at osm-fr.

**Comment by nicolashmln** [comment]
Thanks for the infos @Phyks . I managed to have cyclosm working based on https://github.com/Overv/openstreetmap-tile-server, without the hillshade (see https://github.com/cyclosm/cyclosm-cartocss-style/issues/621#issuecomment-1783975310) and the contours for now.

Would you be interested with a PR?

**Comment by Phyks** [comment]
You mean a PR for a production-grade Dockerfile? Every PR and addition is nice to have, I might not have the bandwidth to maintain it (although this is not something which should break often), so maybe there should be a disclaimer in the updated files? Thanks!
