### ISSUE TITLE
Tile loading is extremely slow/unreliable, now even unusable

### ISSUE THREAD

**Issue by momentmal** [cyclosm/cyclosm-cartocss-style#659]
The performance of the tile server(s) seem to be extremely low these days which makes using CyclOSM a game of patience **/Edit: or rather completely unusable since about 2 days**, even on very low zoom levels :/ 

Is this a question of financing better server infrastructure? I and probably many others would be willing to continue to support the project financially as CyclOSM has become a staple in daily route planning for many of us.

![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/9054832/d53a7a53-cc5c-4ed2-9ee5-1705c9cbfba5)

**Comment by momentmal** [comment]
any updates? i completely switched to regular OSM map now as CyclOSM unfortunately became unusable for me

**Comment by jocelynj** [comment]
We did an upgrade of the OS last week, and I think it might be linked to this issue, as the installation incorrectly modified renderd configuration.

Could you check if it is working better now, or if it is still unusable?

**Comment by momentmal** [comment]
@jocelynj it never was the fastest tileserver, but it's now indeed back to working again - so glad to see! thanks for the update!

**Comment by NSaik** [comment]
I seem to be experiencing this issue again today. Basically the same issue as in September; tiles are loading slowly/not loading at all.

**Comment by fredgolightly** [comment]
Nothing loading here for me at any zoom level over the uk

**Comment by zhibek** [comment]
All requests to https://a.tile-cyclosm.openstreetmap.fr ( and b.tile-cyclosm, etc) are failing with HTTP **502 Bad Gateway** errors. This is connecting from the UK (but also via VPN in Netherlands). I've been aware of this since yesterday (2024-01-26) and its ongoing today.

**Comment by jocelynj** [comment]
@cquest: it looks like osm11 is no longer accessible. Is there an issue in your place?

**Comment by jcarignan** [comment]
It is now failling with HTTP 500 even on your own site! [https://www.cyclosm.org/](https://www.cyclosm.org/)

**Comment by jocelynj** [comment]
As the current rendering server is not available, I've changed the proxy to return error 503 immediately.

Sorry for the issue, and we will hopefully be able to fix this before Monday.

**Comment by jocelynj** [comment]
The access issue was resolved: we had a hardware issue on one of the switch connected to the server.

**Comment by martinschnurer** [comment]
any updates? Still too slow!

**Comment by momentmal** [comment]
> any updates? Still too slow!

agreed, unfortunately it has gotten unusably slow again 😕 This issue can be reopened I think..

**Comment by momentmal** [comment]
the alternative URL seems to work faster:
`https://dev.{s}.tile.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png`

**Comment by momentmal** [comment]
Main CyclOSM layer is super slow right now and the alternative URL does not work at all for me anymore 😕

**Comment by momentmal** [comment]
Still super slow, any updates? @jocelynj

**Comment by mappingmilwaukee** [comment]
@jocelynj bumping. Tiles are loading _extremely_ slowly, and sometimes not at all. Between this and OCM's dropped API key, it's not a good time for OSM bike maps :( Can we reopen this issue?

**Comment by bcroq** [comment]
Today it seems to work fine 🎉

**Comment by Cyrille37** [comment]
Hi
It's very slow again now.

**Comment by momentmal** [comment]
Seems like tiles are not loading in at all at the moment.

**Comment by momentmal** [comment]
CyclOSM is back offline.

**Comment by momentmal** [comment]
With spring weather around in Europe, bandwith /  performance seems to be taking a hit again.

**Comment by momentmal** [comment]
tile loading is EXTREMELY slow at the moment.

**Comment by momentmal** [comment]
again, tile loading very slow today. seems like it has daily slowdowns now?
