### ISSUE TITLE
cycling app using your map

### ISSUE THREAD

**Issue by time4tea** [cyclosm/cyclosm-cartocss-style#661]
Hey, just thought you might like to know that cyclosm map style is now fully supported in https://github.com/time4tea/gopro-dashboard-overlay - which generates movies based on GoPro or GPX/FIT recordings.

We have a strong caching mechanism, so users will only request each tile one time generally... 

Thanks for making a nice thing!

**Comment by Phyks** [comment]
Hi,

Thanks a lot for sharing the info and for taking extra measures to ensure reduced load on our tileservers!
