### ISSUE TITLE
access=destination is wrongly rendered ?

### ISSUE THREAD

**Issue by pdfext** [cyclosm/cyclosm-cartocss-style#662]
Hello

 "Impasse de l'Oisans" can be seen here  https://www.cyclosm.org/#map=19/45.19343/5.69030/cyclosm
 
 As far as I  can see, the "Impasse de l'Oisans" is rendered (green) as a street where no motor vehicles are authorized.  
 But I believe the rendering is badly computed from the 'access=destination'  which is set on this street.
 As a matter of fact, motor vehicles can take this street, but only the ones of people which are inhabitants in this street : this is the meaning of 'access=destination' isn't it ? 

 The very next street which is "Rue Yves Farge" has same issue, and is as well set with  'access=destination' 
 
  Can you please verify this point ?
  Thanks

**Comment by Phyks** [comment]
This is correct and this is the expected render. Access=destination means that only motor vehicles ending their way in the street can use it. Therefore:
1/ There should be very few vehicles. 
2/ The drivers should be neighbours at the end of their way. They usually are calmer and want the street to be peaceful.
