### ISSUE TITLE
Map Currently Down

### ISSUE THREAD

**Issue by leetmaster** [cyclosm/cyclosm-cartocss-style#669]
First of all, thank you for your great work!

The issue is that with provider https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png the tiles are not loading.

Thanks in advance.

**Comment by divulgacheur** [comment]
True :+1:

**Comment by Phyks** [comment]
Thanks, I reported it to osm-fr (hoster of the service).

**Comment by Phyks** [comment]
There was a blocking due to another render hosted on the same infrastructure. This should now be fixed.
