### ISSUE TITLE
Extra false diagonal lines shown at certain zoom level

### ISSUE THREAD

**Issue by xxyxxyxyx1** [cyclosm/cyclosm-cartocss-style#670]
At an intermediate zoom, I see many straight lines that are not related to any real roads or bicycle paths. They disappear at higher zoom. 

For example, in Berlin, I see this:
![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/25559220/a8806026-82ff-47e5-85d3-780c597e73db)

Those straight diagonal lines are unrelated to anything real, as far as I can tell. If I zoom in, they disappear:
![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/25559220/4635387c-f760-45d8-83bd-cee17c1b00c6)

This seems to be some kind of rendering artifact. You can see that all of the lines terminate at the same place on the left side of the screen; below, I have drawn a red box on the screenshot to show this. To the left of the red box, the map is shown correctly. 
![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/25559220/27f0edf2-5dda-4895-9f1f-c4ca12f044a9)

I observe the same problem on cyclosm.org on a computer, and when I access cyclosm using the OsmAnd android app. I observe the problem in various locations, not just Berlin.

**Comment by momentmal** [comment]
i can reproduce this. it seems only to occur on zoom level 14.

**Comment by chinook07** [comment]
I get this too at the most random places!

**Comment by kaneap** [comment]
I believe this is a result of one special OSM vandal. The vandalism is usually quickly reverted, but for some tiles, it can still be visible. In my experience, refreshing the page (and possibly clearing the cache) makes this disappear.

**Comment by chinook07** [comment]
Ah yes, when visible enough to see street names, it becomes clear!

**Comment by Phyks** [comment]
This looks indeed like vandalism. This usually does not last long, however it was seeable at zoom 14 while the tiles were generated. This zoom level is quite computer intensive to compute and is then aggressively cached. This should disappear in a couple days with cache expiration.

**Comment by Phyks** [comment]
Solved by now :)

**Comment by maqiv** [comment]
Hello

Unfortunately, I found the same issue on Zoom level 15 (https://www.cyclosm.org/#map=16/47.3160/8.1065/cyclosm):
![image](https://github.com/user-attachments/assets/5324251e-c7f7-4b4a-995f-ac9148f7b5d4)

How can we support the OSM community preventing such vandalism to not spam unnecessarily places like this GitHub repository?

I also tried to edit the area on the official OSM map editor to remove these invalid entries, but unfortunately on Zoom level 15 there is no edit possible in the editor:
![image](https://github.com/user-attachments/assets/96bea6a9-fb18-4016-83d5-bff656564965)


Thanks in advance and for your awesome work, and best regards,
Sebastian
