### ISSUE TITLE
Incorrect Road and Line Data on CyclOSM Map

### ISSUE THREAD

**Issue by crazyjack123** [cyclosm/cyclosm-cartocss-style#676]
I'm seeing this error on CyclOSM map. The map shows numerous roads and lines that appear to be incorrect or misplaced. This issue affects the readability and usability of the map.
![Uploading Screenshot 2024-06-17 at 16.22.47 (1).png…]()

**Comment by Phyks** [comment]
See https://github.com/cyclosm/cyclosm-cartocss-style/issues/675, OSM is facing waves of vandalism.

**Comment by crazyjack123** [comment]
Thank You
