### ISSUE TITLE
Mixed layers

### ISSUE THREAD

**Issue by myadzel** [cyclosm/cyclosm-cartocss-style#678]
Today I found (on another website) place with mixed layers from different countries:

https://www.cyclosm.org/#map=15/56.4994/37.3771/cyclosm

**Comment by Phyks** [comment]
Not sure to understand what mixed layers are and the issue in the given link?

**Comment by myadzel** [comment]
Zoom 15, problems: 

https://www.cyclosm.org/#map=15/56.3770/37.3420/cyclosm

![Screenshot_2024-06-24-07-04-37-65_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/cyclosm/cyclosm-cartocss-style/assets/873432/bce786d9-21b3-4127-be9a-bb4d11250c8c)

**Comment by myadzel** [comment]
Zoom 14, no problems:

https://www.cyclosm.org/#map=14/56.3770/37.3420/cyclosm

![Screenshot_2024-06-24-07-07-05-19_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/cyclosm/cyclosm-cartocss-style/assets/873432/28dfbf3a-58d1-4b26-8184-d96a371cff25)

**Comment by Phyks** [comment]
This is an extra occurrence of https://github.com/cyclosm/cyclosm-cartocss-style/issues/670 which is being worked upon.
