### ISSUE TITLE
Postgres DB Tables needs proper Indexing

### ISSUE THREAD

**Issue by hbsandeepj** [cyclosm/cyclosm-cartocss-style#680]
I believe that the Database tables should be indexed properly so that the db operations could be smoothened. If we try to load whole Europe which is approx of 29 GB, it dies. I additionally added Varnish cache to overcome this. However, the problem arises when a bunch of users tries to request for tiles, the database goes into bottleneck, I then manually added indexing to some of the tables, and now it is much better than the existing version.

**Comment by Phyks** [comment]
Hi,

I'm not sure to understand the issue you describe. Are you talking about setting up your own local copy of CyclOSM render on top of a local osm2pgsql database? 

In this case, https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md#openstreetmap-data should be up to date. You need to explicitly create some views in your psql database (https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/views.sql) and it's worth adding a few extra indices (https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md#useful-tweaks-for-production-setup).

I've not seen the issue you mention, so really eager to know more about your setup and the extra indices you added!

**Comment by hbsandeepj** [comment]
@Phyks 
Yes I have tried to setup my own space for hosting this. However, I had tuned the database by adding up few indexes to the db tables so that it could be speeded up. Is there any way by which I can simply extract the tiles out in PNG format in a directory so that I need not to utilise the database every time while requesting for a tile?

**Comment by Phyks** [comment]
This is rather about tooling and beyond the scope of this repo, I'll close the issue since there is no direct action for cyclosm.

For pre-generating a set of tiles and export them as PNG, you can have a look at Kosmtik export plugins: https://github.com/kosmtik/kosmtik?tab=readme-ov-file#known-plugins.

**Comment by hbsandeepj** [comment]
@Phyks thanks for the reply, however, I'm unable to setup the export library in this repository. I'm using the docker version can you please help with this?
