### ISSUE TITLE
Install.md Downloading elevation data-  Instructions don't work.

### ISSUE THREAD

**Issue by rkarikari** [cyclosm/cyclosm-cartocss-style#682]
Hello,

As seen below, the file does not exist on their servers.

<img width="1135" alt="Screenshot 2024-07-06 at 10 12 08 PM" src="https://github.com/cyclosm/cyclosm-cartocss-style/assets/115777368/68090841-b9f3-47b1-beb7-ad0b79d5318a">

Are there any other solutions please ?

**Comment by Phyks** [comment]
You get an HTTP error 401 : Unauthorized. Are you sure you are using a valid NASA EarthData account? NASA-USERNAME and NASA-PASSWORD should be replaced with your own account in the command line listed in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md#download-some-elevation-data.

Anyways, this is beyond CyclOSM scope so please report the bug (if any) to Panarchos user on OSM, see https://wiki.openstreetmap.org/wiki/Phyghtmap.
