### ISSUE TITLE
Weird foreign features 

### ISSUE THREAD

**Issue by jidanni** [cyclosm/cyclosm-cartocss-style#687]
Weird foreign features seen [here](https://www.openstreetmap.org/query?lat=24.18292&lon=120.86603#map=18/24.18323/120.86342&layers=Y)
![20240804T082510](https://github.com/user-attachments/assets/615d3feb-920b-4c05-af55-85bf32722305)

**Comment by stigermunk** [comment]
https://www.openstreetmap.org/#map=18/53.17596/13.14344&layers=Y
Also here... also reported;https://github.com/cyclosm/cyclosm-cartocss-style/issues/688
only on one zoom level (inward or outward and it disappears) and random street scratches over the city.

**Comment by Phyks** [comment]
That was vandalism now reverted and purged from cache.
