### ISSUE TITLE
Bike box (cycleway=asl) icon should be oriented along street.

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#73]

**Comment by Florimondable** [comment]
traffic_calming should be oriented too

**Comment by Phyks** [comment]
Problem is I'm not sure the information about the way it belongs to is accessible from a node in the osm2pgsql default db schema. :/ Therefore, I'm not sure we can infer the rotation to apply to the marker (if the marker is from an OSM node).

To be investigated more in depth.

**Comment by Phyks** [comment]
Quick and dirty SQL command:

Assuming you are interested in the bike box with id `4611634384`,

```
SELECT nodes[GREATEST(pos - 1, 0):LEAST(pos + 1, length)] FROM (SELECT array_position(nodes, 4611634384) AS pos, array_length(nodes, 1) AS length, nodes FROM planet_osm_ways WHERE nodes @> '{4611634384}' LIMIT 1) AS data;
```

returns the previous and next node in line. Then, looking at the `planet_osm_points` table, we can get previous and next coordinates and infer a direction. To be completed and timed.
