### ISSUE TITLE
Improve render of roads with limited motor vehicle access

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#74]
access=destination/delivery/(customers?)
or
motor_vehicle=no/destination/delivery/(customers?)

**Comment by Phyks** [comment]
➕ 

We might add an extra check that `bicycle` is explicitly authorized, no?

(Typically, an `access=destination` road should legally not be used by cars nor bikes as a transit street, so we should probably not show it with extra emphasis as being bike frienldy)

**Comment by Phyks** [comment]
Partially done in #88. There is still room for improvement though, but access tags in OSM are very complicated to use and easy to mess up. We can probably close this one for now and see later on with a basis of examples.

**Comment by Florimondable** [comment]
Not sure it's a good idea to close a ticket before full implementation.

For the moment a road with forbidden access to cars is only rendered with a cyan color, which cannot be distinguish from a slow speed road.
Idea : add a cross icon X like we do with arrows for oneway roads ? (but may be this leads to a conflict with oneway arrow :/)

**Comment by Phyks** [comment]
Provided barriers etc have been mapped, these should be visible. Not much ideas otherwise :/

**Comment by Phyks** [comment]
> Idea : add a cross icon X like we do with arrows for oneway roads ? (but may be this leads to a conflict with oneway arrow :/)

I would personally read the X icon as applying to bikes, not cars, by default :/

A road without cars should have something to prevent cars from accessing (typically barriers), which should be rendered on the map. Do you have an example of a place where this would not be enough?

**Comment by Florimondable** [comment]
For the moment we use the highway=pedestrian cyan color which is ok I think, I plan to use it also for almost no traffic road with #320  (as soon as we solve the issue #324 )

**Comment by Phyks** [comment]
Ok. So closing this one. Feel free to reopen if you think it should stay open.
