### ISSUE TITLE
Rework bicycle parking rendering

### ISSUE THREAD

**Issue by natolh** [cyclosm/cyclosm-cartocss-style#79]
Bike parking is a key component of the cycling infrastructure (at least for me, I often search for them on maps). Yet we use dots to render them.
- Some "less important" features use icons (traffic lights for example).
- Dots might be used in the future to represents POI for which we do not have / want an icon (like on openstreetmap).

If we decide to use an icon for rendering bicycle parkings, I suggest we use something that look like parking signs for cars because it is straightforward. This is the strategy used by openstreetmap. Plus they append to it a bike icon, but as this is a cycling map I think we can drop it.

Concerning the capacity, what is the use case for displaying the capacity ? My initial thoughts are (1) more capacity => more chances to have a place and (2) more capacity => better infrastructure (perhaps covered, perhaps secured). But is it true ? And if it is maybe we can use a threshold to display capacity only for high capacity parking (just like opencyclemap).

**Comment by Phyks** [comment]
Hi,

Thanks for the feedback on this! I totally agree bike parking is a key infrastructure, especially in urban area or around a touristic place. The initial reason that lead me to using dots for bicycle parking is mostly to be able to display as much as possible. In urban areas, there are often a lot of small bicycle parking (capacity of 2 to 4 bikes, very sparse) and they could easily conflict with other icons (typically shops). I wanted to be able to display as much bicycle parkings as possible, hence the dots.

This is probably far from being optimal though.

> If we decide to use an icon for rendering bicycle parkings, I suggest we use something that look like parking signs for cars because it is straightforward. This is the strategy used by openstreetmap. Plus they append to it a bike icon, but as this is a cycling map I think we can drop it.

Using an icon would be totally fine I think. We should probably just keep in mind two things:
- First, the issue that the icon should probably be small somehow, to fit easily on the map and not conflict with shop icons or other amenities (in which case only one icon would be shown, be it the bicycle parking or the shop).
- Then, there are "bicycle parkings" (dedicated to bikes) and "shared motorcycle parkings" (dedicated to motorcycles, not very good infrastructure for a bike, but open to bikes as well). The two icons should probably have a link?

> Concerning the capacity, what is the use case for displaying the capacity ? My initial thoughts are (1) more capacity => more chances to have a place

In urban area (in France), there could be a lot of very small parking spots (capacity of 2 or 4 bikes) coupled with some larger ones (capacity of 10 bikes for instance) on main road / crossings. I wanted to introduce a distinction between them, as it will probably not be easy to find a free spot in a small parking. Hence the capacity, but there might be better means.

> (2) more capacity => better infrastructure (perhaps covered, perhaps secured)

This is usually the case (France experience again) for very large bicycle parkings (capacity of the order of a few tens). Some of these are operated by SNCF (railways) for instance and target people leaving their bike at the train station all day long.

> if it is maybe we can use a threshold to display capacity only for high capacity parking (just like opencyclemap).

Only the largest capacity numbers (more than 10) are shown at medium zoom. The capacity of all bikes parkings is only shown at full zoom. You are right, we should probably put a threshold here. Maybe something between 6 and 10 as a minimum capacity to display a number?

**Comment by natolh** [comment]
> First, the issue that the icon should probably be small somehow, to fit easily on the map and not conflict with shop icons or other amenities (in which case only one icon would be shown, be it the bicycle parking or the shop).

Well, I think we can attribute them an icon that is roughly the same size that other icons. In case of conflicts, I strongly suggest that we favour rendering of bicycle parking, the main purpose of a bicycle map is to display bicycle infrastructure.

> Then, there are "bicycle parkings" (dedicated to bikes) and "shared motorcycle parkings" (dedicated to motorcycles, not very good infrastructure for a bike, but open to bikes as well). The two icons should probably have a link?

Yes, definitely.

> as it will probably not be easy to find a free spot in a small parking
Well maybe we should check if it's the case ? And estimate what's the threshold of capacity at which it's easier to find a free spot ?

Concerning the quality of the infrastructure I think we have already data in the other tags to think about something without displaying the capacity. We should render secured bike parking differently.

**Comment by Phyks** [comment]
> Concerning the quality of the infrastructure I think we have already data in the other tags to think about something without displaying the capacity. We should render secured bike parking differently.

This is already the case (although the current rendering is not documented in the legend nor very nice). You can have a look at [these ones](https://tiles.phyks.me/#18/48.87629/2.36035) in front of Gare de l'Est for instance.

**Comment by Florimondable** [comment]
My point of view :
Displaying bicycle parking as dot is fine for me : small but very simple to see, using an icon means bigger icons because there is lot of blank in a 'P' for instance.

About capacity : I don't like the idea of displaying some parking but not all, it's something I don't like in OCM. As a user I shouldn't be aware that the map is not drawing everything but a small part of all the parking, it is disturbing and brings not much.
